
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: Feb 25 2025 09:03:58 EST (Feb 25 2025 14:03:58 UTC)

// Verification Directory fv/or1200_ctrl 

module or1200_ctrl(clk, rst, except_flushpipe, extend_flush, id_freeze,
     ex_freeze, wb_freeze, if_insn_31, if_insn_30, if_insn_29,
     if_insn_28, if_insn_27, if_insn_26, if_insn_25, if_insn_24,
     if_insn_23, if_insn_22, if_insn_21, if_insn_20, if_insn_19,
     if_insn_18, if_insn_17, if_insn_16, if_insn_15, if_insn_14,
     if_insn_13, if_insn_12, if_insn_11, if_insn_10, if_insn_9,
     if_insn_8, if_insn_7, if_insn_6, if_insn_5, if_insn_4, if_insn_3,
     if_insn_2, if_insn_1, if_insn_0, abort_mvspr, ex_branch_taken,
     pc_we, id_pc_31, id_pc_30, id_pc_29, id_pc_28, id_pc_27, id_pc_26,
     id_pc_25, id_pc_24, id_pc_23, id_pc_22, id_pc_21, id_pc_20,
     id_pc_19, id_pc_18, id_pc_17, id_pc_16, id_pc_15, id_pc_14,
     id_pc_13, id_pc_12, id_pc_11, id_pc_10, id_pc_9, id_pc_8, id_pc_7,
     id_pc_6, id_pc_5, id_pc_4, id_pc_3, id_pc_2, id_pc_1, id_pc_0,
     ex_pc_31, ex_pc_30, ex_pc_29, ex_pc_28, ex_pc_27, ex_pc_26,
     ex_pc_25, ex_pc_24, ex_pc_23, ex_pc_22, ex_pc_21, ex_pc_20,
     ex_pc_19, ex_pc_18, ex_pc_17, ex_pc_16, ex_pc_15, ex_pc_14,
     ex_pc_13, ex_pc_12, ex_pc_11, ex_pc_10, ex_pc_9, ex_pc_8, ex_pc_7,
     ex_pc_6, ex_pc_5, ex_pc_4, ex_pc_3, ex_pc_2, ex_pc_1, ex_pc_0,
     du_hwbkpt, wbforw_valid, du_flush_pipe, if_flushpipe,
     id_flushpipe, ex_flushpipe, wb_flushpipe, id_insn_31, id_insn_30,
     id_insn_29, id_insn_28, id_insn_27, id_insn_26, id_insn_25,
     id_insn_24, id_insn_23, id_insn_22, id_insn_21, id_insn_20,
     id_insn_19, id_insn_18, id_insn_17, id_insn_16, id_insn_15,
     id_insn_14, id_insn_13, id_insn_12, id_insn_11, id_insn_10,
     id_insn_9, id_insn_8, id_insn_7, id_insn_6, id_insn_5, id_insn_4,
     id_insn_3, id_insn_2, id_insn_1, id_insn_0, ex_insn_31,
     ex_insn_30, ex_insn_29, ex_insn_28, ex_insn_27, ex_insn_26,
     ex_insn_25, ex_insn_24, ex_insn_23, ex_insn_22, ex_insn_21,
     ex_insn_20, ex_insn_19, ex_insn_18, ex_insn_17, ex_insn_16,
     ex_insn_15, ex_insn_14, ex_insn_13, ex_insn_12, ex_insn_11,
     ex_insn_10, ex_insn_9, ex_insn_8, ex_insn_7, ex_insn_6, ex_insn_5,
     ex_insn_4, ex_insn_3, ex_insn_2, ex_insn_1, ex_insn_0,
     id_branch_op_2, id_branch_op_1, id_branch_op_0, ex_branch_op_2,
     ex_branch_op_1, ex_branch_op_0, rf_addra_4, rf_addra_3,
     rf_addra_2, rf_addra_1, rf_addra_0, rf_addrb_4, rf_addrb_3,
     rf_addrb_2, rf_addrb_1, rf_addrb_0, rf_rda, rf_rdb, alu_op_4,
     alu_op_3, alu_op_2, alu_op_1, alu_op_0, alu_op2_3, alu_op2_2,
     alu_op2_1, alu_op2_0, mac_op_2, mac_op_1, mac_op_0, comp_op_3,
     comp_op_2, comp_op_1, comp_op_0, rf_addrw_4, rf_addrw_3,
     rf_addrw_2, rf_addrw_1, rf_addrw_0, rfwb_op_3, rfwb_op_2,
     rfwb_op_1, rfwb_op_0, fpu_op_7, fpu_op_6, fpu_op_5, fpu_op_4,
     fpu_op_3, fpu_op_2, fpu_op_1, fpu_op_0, wb_insn_31, wb_insn_30,
     wb_insn_29, wb_insn_28, wb_insn_27, wb_insn_26, wb_insn_25,
     wb_insn_24, wb_insn_23, wb_insn_22, wb_insn_21, wb_insn_20,
     wb_insn_19, wb_insn_18, wb_insn_17, wb_insn_16, wb_insn_15,
     wb_insn_14, wb_insn_13, wb_insn_12, wb_insn_11, wb_insn_10,
     wb_insn_9, wb_insn_8, wb_insn_7, wb_insn_6, wb_insn_5, wb_insn_4,
     wb_insn_3, wb_insn_2, wb_insn_1, wb_insn_0, id_simm_31,
     id_simm_30, id_simm_29, id_simm_28, id_simm_27, id_simm_26,
     id_simm_25, id_simm_24, id_simm_23, id_simm_22, id_simm_21,
     id_simm_20, id_simm_19, id_simm_18, id_simm_17, id_simm_16,
     id_simm_15, id_simm_14, id_simm_13, id_simm_12, id_simm_11,
     id_simm_10, id_simm_9, id_simm_8, id_simm_7, id_simm_6, id_simm_5,
     id_simm_4, id_simm_3, id_simm_2, id_simm_1, id_simm_0, ex_simm_31,
     ex_simm_30, ex_simm_29, ex_simm_28, ex_simm_27, ex_simm_26,
     ex_simm_25, ex_simm_24, ex_simm_23, ex_simm_22, ex_simm_21,
     ex_simm_20, ex_simm_19, ex_simm_18, ex_simm_17, ex_simm_16,
     ex_simm_15, ex_simm_14, ex_simm_13, ex_simm_12, ex_simm_11,
     ex_simm_10, ex_simm_9, ex_simm_8, ex_simm_7, ex_simm_6, ex_simm_5,
     ex_simm_4, ex_simm_3, ex_simm_2, ex_simm_1, ex_simm_0,
     id_branch_addrtarget_31, id_branch_addrtarget_30,
     id_branch_addrtarget_29, id_branch_addrtarget_28,
     id_branch_addrtarget_27, id_branch_addrtarget_26,
     id_branch_addrtarget_25, id_branch_addrtarget_24,
     id_branch_addrtarget_23, id_branch_addrtarget_22,
     id_branch_addrtarget_21, id_branch_addrtarget_20,
     id_branch_addrtarget_19, id_branch_addrtarget_18,
     id_branch_addrtarget_17, id_branch_addrtarget_16,
     id_branch_addrtarget_15, id_branch_addrtarget_14,
     id_branch_addrtarget_13, id_branch_addrtarget_12,
     id_branch_addrtarget_11, id_branch_addrtarget_10,
     id_branch_addrtarget_9, id_branch_addrtarget_8,
     id_branch_addrtarget_7, id_branch_addrtarget_6,
     id_branch_addrtarget_5, id_branch_addrtarget_4,
     id_branch_addrtarget_3, id_branch_addrtarget_2,
     ex_branch_addrtarget_31, ex_branch_addrtarget_30,
     ex_branch_addrtarget_29, ex_branch_addrtarget_28,
     ex_branch_addrtarget_27, ex_branch_addrtarget_26,
     ex_branch_addrtarget_25, ex_branch_addrtarget_24,
     ex_branch_addrtarget_23, ex_branch_addrtarget_22,
     ex_branch_addrtarget_21, ex_branch_addrtarget_20,
     ex_branch_addrtarget_19, ex_branch_addrtarget_18,
     ex_branch_addrtarget_17, ex_branch_addrtarget_16,
     ex_branch_addrtarget_15, ex_branch_addrtarget_14,
     ex_branch_addrtarget_13, ex_branch_addrtarget_12,
     ex_branch_addrtarget_11, ex_branch_addrtarget_10,
     ex_branch_addrtarget_9, ex_branch_addrtarget_8,
     ex_branch_addrtarget_7, ex_branch_addrtarget_6,
     ex_branch_addrtarget_5, ex_branch_addrtarget_4,
     ex_branch_addrtarget_3, ex_branch_addrtarget_2, sel_a_1, sel_a_0,
     sel_b_1, sel_b_0, id_lsu_op_3, id_lsu_op_2, id_lsu_op_1,
     id_lsu_op_0, cust5_op_4, cust5_op_3, cust5_op_2, cust5_op_1,
     cust5_op_0, cust5_limm_5, cust5_limm_4, cust5_limm_3,
     cust5_limm_2, cust5_limm_1, cust5_limm_0, multicycle_2,
     multicycle_1, multicycle_0, wait_on_1, wait_on_0, sig_syscall,
     sig_trap, force_dslot_fetch, no_more_dslot, id_void, ex_void,
     ex_spr_read, ex_spr_write, id_mac_op_2, id_mac_op_1, id_mac_op_0,
     id_macrc_op, ex_macrc_op, rfe, except_illegal, dc_no_writethrough);
  input clk, rst, except_flushpipe, extend_flush, id_freeze, ex_freeze,
       wb_freeze, if_insn_31, if_insn_30, if_insn_29, if_insn_28,
       if_insn_27, if_insn_26, if_insn_25, if_insn_24, if_insn_23,
       if_insn_22, if_insn_21, if_insn_20, if_insn_19, if_insn_18,
       if_insn_17, if_insn_16, if_insn_15, if_insn_14, if_insn_13,
       if_insn_12, if_insn_11, if_insn_10, if_insn_9, if_insn_8,
       if_insn_7, if_insn_6, if_insn_5, if_insn_4, if_insn_3,
       if_insn_2, if_insn_1, if_insn_0, abort_mvspr, ex_branch_taken,
       pc_we, id_pc_31, id_pc_30, id_pc_29, id_pc_28, id_pc_27,
       id_pc_26, id_pc_25, id_pc_24, id_pc_23, id_pc_22, id_pc_21,
       id_pc_20, id_pc_19, id_pc_18, id_pc_17, id_pc_16, id_pc_15,
       id_pc_14, id_pc_13, id_pc_12, id_pc_11, id_pc_10, id_pc_9,
       id_pc_8, id_pc_7, id_pc_6, id_pc_5, id_pc_4, id_pc_3, id_pc_2,
       id_pc_1, id_pc_0, ex_pc_31, ex_pc_30, ex_pc_29, ex_pc_28,
       ex_pc_27, ex_pc_26, ex_pc_25, ex_pc_24, ex_pc_23, ex_pc_22,
       ex_pc_21, ex_pc_20, ex_pc_19, ex_pc_18, ex_pc_17, ex_pc_16,
       ex_pc_15, ex_pc_14, ex_pc_13, ex_pc_12, ex_pc_11, ex_pc_10,
       ex_pc_9, ex_pc_8, ex_pc_7, ex_pc_6, ex_pc_5, ex_pc_4, ex_pc_3,
       ex_pc_2, ex_pc_1, ex_pc_0, du_hwbkpt, wbforw_valid,
       du_flush_pipe;
  output if_flushpipe, id_flushpipe, ex_flushpipe, wb_flushpipe,
       id_insn_31, id_insn_30, id_insn_29, id_insn_28, id_insn_27,
       id_insn_26, id_insn_25, id_insn_24, id_insn_23, id_insn_22,
       id_insn_21, id_insn_20, id_insn_19, id_insn_18, id_insn_17,
       id_insn_16, id_insn_15, id_insn_14, id_insn_13, id_insn_12,
       id_insn_11, id_insn_10, id_insn_9, id_insn_8, id_insn_7,
       id_insn_6, id_insn_5, id_insn_4, id_insn_3, id_insn_2,
       id_insn_1, id_insn_0, ex_insn_31, ex_insn_30, ex_insn_29,
       ex_insn_28, ex_insn_27, ex_insn_26, ex_insn_25, ex_insn_24,
       ex_insn_23, ex_insn_22, ex_insn_21, ex_insn_20, ex_insn_19,
       ex_insn_18, ex_insn_17, ex_insn_16, ex_insn_15, ex_insn_14,
       ex_insn_13, ex_insn_12, ex_insn_11, ex_insn_10, ex_insn_9,
       ex_insn_8, ex_insn_7, ex_insn_6, ex_insn_5, ex_insn_4,
       ex_insn_3, ex_insn_2, ex_insn_1, ex_insn_0, id_branch_op_2,
       id_branch_op_1, id_branch_op_0, ex_branch_op_2, ex_branch_op_1,
       ex_branch_op_0, rf_addra_4, rf_addra_3, rf_addra_2, rf_addra_1,
       rf_addra_0, rf_addrb_4, rf_addrb_3, rf_addrb_2, rf_addrb_1,
       rf_addrb_0, rf_rda, rf_rdb, alu_op_4, alu_op_3, alu_op_2,
       alu_op_1, alu_op_0, alu_op2_3, alu_op2_2, alu_op2_1, alu_op2_0,
       mac_op_2, mac_op_1, mac_op_0, comp_op_3, comp_op_2, comp_op_1,
       comp_op_0, rf_addrw_4, rf_addrw_3, rf_addrw_2, rf_addrw_1,
       rf_addrw_0, rfwb_op_3, rfwb_op_2, rfwb_op_1, rfwb_op_0,
       fpu_op_7, fpu_op_6, fpu_op_5, fpu_op_4, fpu_op_3, fpu_op_2,
       fpu_op_1, fpu_op_0, wb_insn_31, wb_insn_30, wb_insn_29,
       wb_insn_28, wb_insn_27, wb_insn_26, wb_insn_25, wb_insn_24,
       wb_insn_23, wb_insn_22, wb_insn_21, wb_insn_20, wb_insn_19,
       wb_insn_18, wb_insn_17, wb_insn_16, wb_insn_15, wb_insn_14,
       wb_insn_13, wb_insn_12, wb_insn_11, wb_insn_10, wb_insn_9,
       wb_insn_8, wb_insn_7, wb_insn_6, wb_insn_5, wb_insn_4,
       wb_insn_3, wb_insn_2, wb_insn_1, wb_insn_0, id_simm_31,
       id_simm_30, id_simm_29, id_simm_28, id_simm_27, id_simm_26,
       id_simm_25, id_simm_24, id_simm_23, id_simm_22, id_simm_21,
       id_simm_20, id_simm_19, id_simm_18, id_simm_17, id_simm_16,
       id_simm_15, id_simm_14, id_simm_13, id_simm_12, id_simm_11,
       id_simm_10, id_simm_9, id_simm_8, id_simm_7, id_simm_6,
       id_simm_5, id_simm_4, id_simm_3, id_simm_2, id_simm_1,
       id_simm_0, ex_simm_31, ex_simm_30, ex_simm_29, ex_simm_28,
       ex_simm_27, ex_simm_26, ex_simm_25, ex_simm_24, ex_simm_23,
       ex_simm_22, ex_simm_21, ex_simm_20, ex_simm_19, ex_simm_18,
       ex_simm_17, ex_simm_16, ex_simm_15, ex_simm_14, ex_simm_13,
       ex_simm_12, ex_simm_11, ex_simm_10, ex_simm_9, ex_simm_8,
       ex_simm_7, ex_simm_6, ex_simm_5, ex_simm_4, ex_simm_3,
       ex_simm_2, ex_simm_1, ex_simm_0, id_branch_addrtarget_31,
       id_branch_addrtarget_30, id_branch_addrtarget_29,
       id_branch_addrtarget_28, id_branch_addrtarget_27,
       id_branch_addrtarget_26, id_branch_addrtarget_25,
       id_branch_addrtarget_24, id_branch_addrtarget_23,
       id_branch_addrtarget_22, id_branch_addrtarget_21,
       id_branch_addrtarget_20, id_branch_addrtarget_19,
       id_branch_addrtarget_18, id_branch_addrtarget_17,
       id_branch_addrtarget_16, id_branch_addrtarget_15,
       id_branch_addrtarget_14, id_branch_addrtarget_13,
       id_branch_addrtarget_12, id_branch_addrtarget_11,
       id_branch_addrtarget_10, id_branch_addrtarget_9,
       id_branch_addrtarget_8, id_branch_addrtarget_7,
       id_branch_addrtarget_6, id_branch_addrtarget_5,
       id_branch_addrtarget_4, id_branch_addrtarget_3,
       id_branch_addrtarget_2, ex_branch_addrtarget_31,
       ex_branch_addrtarget_30, ex_branch_addrtarget_29,
       ex_branch_addrtarget_28, ex_branch_addrtarget_27,
       ex_branch_addrtarget_26, ex_branch_addrtarget_25,
       ex_branch_addrtarget_24, ex_branch_addrtarget_23,
       ex_branch_addrtarget_22, ex_branch_addrtarget_21,
       ex_branch_addrtarget_20, ex_branch_addrtarget_19,
       ex_branch_addrtarget_18, ex_branch_addrtarget_17,
       ex_branch_addrtarget_16, ex_branch_addrtarget_15,
       ex_branch_addrtarget_14, ex_branch_addrtarget_13,
       ex_branch_addrtarget_12, ex_branch_addrtarget_11,
       ex_branch_addrtarget_10, ex_branch_addrtarget_9,
       ex_branch_addrtarget_8, ex_branch_addrtarget_7,
       ex_branch_addrtarget_6, ex_branch_addrtarget_5,
       ex_branch_addrtarget_4, ex_branch_addrtarget_3,
       ex_branch_addrtarget_2, sel_a_1, sel_a_0, sel_b_1, sel_b_0,
       id_lsu_op_3, id_lsu_op_2, id_lsu_op_1, id_lsu_op_0, cust5_op_4,
       cust5_op_3, cust5_op_2, cust5_op_1, cust5_op_0, cust5_limm_5,
       cust5_limm_4, cust5_limm_3, cust5_limm_2, cust5_limm_1,
       cust5_limm_0, multicycle_2, multicycle_1, multicycle_0,
       wait_on_1, wait_on_0, sig_syscall, sig_trap, force_dslot_fetch,
       no_more_dslot, id_void, ex_void, ex_spr_read, ex_spr_write,
       id_mac_op_2, id_mac_op_1, id_mac_op_0, id_macrc_op, ex_macrc_op,
       rfe, except_illegal, dc_no_writethrough;
  wire add_321_65_n_558, add_321_65_n_560, add_321_65_n_563,
       add_321_65_n_565, add_321_65_n_567, add_321_65_n_569,
       add_321_65_n_571, add_321_65_n_573;
  wire add_321_65_n_575, add_321_65_n_577, add_321_65_n_579,
       add_321_65_n_581, add_321_65_n_583, add_321_65_n_585,
       add_321_65_n_587, add_321_65_n_589;
  wire add_321_65_n_591, add_321_65_n_593, add_321_65_n_595,
       add_321_65_n_597, add_321_65_n_599, add_321_65_n_601,
       add_321_65_n_603, add_321_65_n_605;
  wire add_321_65_n_607, add_321_65_n_609, add_321_65_n_611,
       add_321_65_n_613, add_321_65_n_615, add_321_65_n_621, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  wire n_298, n_299, n_300, n_301, n_302, n_303, n_304, n_305;
  wire n_306, n_307, n_308, n_309, n_310, n_311, n_312, n_313;
  wire n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321;
  wire n_322, n_323, n_324, n_325, n_326, n_327, n_328, n_329;
  wire n_330, n_331, n_332, n_333, n_334, n_335, n_336, n_337;
  wire n_338, n_339, n_340, n_341, n_342, n_343, n_344, n_345;
  wire n_346, n_347, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_364, n_365, n_366, n_367, n_368, n_369;
  wire n_370, n_371, n_372, n_373, n_374, n_375, n_376, n_377;
  wire n_378, n_379, n_380, n_381, n_382, n_383, n_384, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_411, n_412, n_413, n_414, n_415, n_416, n_417;
  wire n_418, n_419, n_420, n_421, n_422, n_423, n_424, n_425;
  wire n_426, n_427, n_428, n_429, n_430, n_431, n_432, n_433;
  wire n_434, n_435, n_436, n_437, n_438, n_439, n_440, n_441;
  wire n_442, n_443, n_444, n_445, n_446, n_447, n_448, n_449;
  wire n_450, n_451, n_452, n_453, n_454, n_455, n_456, n_457;
  wire n_458, n_459, n_460, n_461, n_462, n_463, n_464, n_465;
  wire n_466, n_467, n_468, n_469, n_470, n_471, n_472, n_473;
  wire n_474, n_475, n_476, n_477, n_478, n_479, n_480, n_481;
  wire n_482, n_483, n_484, n_485, n_486, n_487, n_488, n_489;
  wire n_490, n_491, n_492, n_493, n_494, n_495, n_496, n_497;
  wire n_498, n_499, n_500, n_501, n_502, n_503, n_504, n_505;
  wire n_506, n_507, n_508, n_509, n_510, n_511, n_512, n_513;
  wire n_514, n_515, n_516, n_517, n_518, n_519, n_520, n_521;
  wire n_522, n_523, n_524, n_525, n_526, n_527, n_528, n_529;
  wire n_530, n_531, n_532, n_533, n_534, n_535, n_536, n_537;
  wire n_538, n_539, n_540, n_541, n_542, n_543, n_544, n_545;
  wire n_546, n_547, n_548, n_549, n_550, n_551, n_552, n_553;
  wire n_554, n_555, n_556, n_557, n_558, n_559, n_560, n_561;
  wire n_562, n_563, n_564, n_565, n_566, n_567, n_568, n_569;
  wire n_570, n_571, n_572, n_573, n_574, n_575, n_576, n_577;
  wire n_578, n_579, n_580, n_581, n_582, n_583, n_584, n_585;
  wire n_586, n_587, n_588, n_589, n_590, n_591, n_592, n_593;
  wire n_594, n_595, n_596, n_597, n_598, n_599, n_600, n_601;
  wire n_602, n_603, n_604, n_605, n_606, n_607, n_608, n_609;
  wire n_610, n_611, n_612, n_613, n_614, n_615, n_616, n_617;
  wire n_618, n_619, n_620, n_621, n_622, n_623, n_624, n_625;
  wire n_626, n_627, n_628, n_629, n_630, n_631, n_632, n_633;
  wire n_634, n_635, n_636, n_637, n_638, n_639, n_640, n_641;
  wire n_642, n_643, n_644, n_645, n_646, n_647, n_648, n_649;
  wire n_650, n_651, n_652, n_653, n_654, n_655, n_656, n_657;
  wire n_658, n_659, n_660, n_661, n_662, n_663, n_664, n_665;
  wire n_666, n_667, n_668, n_669, n_670, n_671, n_672, n_673;
  wire n_674, n_675, n_676, n_677, n_678, n_679, n_680, n_681;
  wire n_682, n_683, n_684, n_685, n_686, n_687, n_688, n_689;
  wire n_690, n_691, n_692, n_693, n_694, n_695, n_696, n_697;
  wire n_698, n_699, n_700, n_701, n_702, n_703, n_704, n_705;
  wire n_706, n_707, n_708, n_709, n_710, n_711, n_712, n_713;
  wire n_714, n_715, n_716, n_717, n_718, n_719, n_720, n_721;
  wire n_722, n_723, n_724, n_725, n_726, n_727, n_728, n_729;
  wire n_730, n_731, n_732, n_733, n_734, n_735, n_736, n_737;
  wire n_738, n_739, n_740, n_741, n_742, n_743, n_744, n_745;
  wire n_746, n_747, n_748, n_749, n_750, n_751, n_752, n_753;
  wire n_754, n_755, n_756, n_757, n_758, n_759, n_760, n_761;
  wire n_762, n_763, n_764, n_765, n_766, n_767, n_768, n_769;
  wire n_770, n_771, n_772, n_773, n_774, n_775, n_776, n_777;
  wire n_778, n_779, n_780, n_781, n_782, n_783, n_784, n_785;
  wire n_786, n_787, n_788, n_789, n_790, n_791, n_792, n_793;
  wire n_794, n_795, n_796, n_797, n_798, n_799, n_800, n_801;
  wire n_802, n_803, n_804, n_805, n_806, n_807, n_808, n_809;
  wire n_810, n_811, n_812, n_813, n_814, n_815, n_816, n_817;
  wire n_818, n_819, n_820, n_821, n_822, n_823, n_824, n_825;
  wire n_826, n_827, n_828, n_829, n_830, n_831, n_832, n_833;
  wire n_834, n_836, n_838, n_839, n_840, n_841, n_842, n_843;
  wire n_844, n_845, n_846, n_847, n_848, n_849, n_850, n_851;
  wire n_856, n_859, n_860, n_861, n_862, n_863, sel_imm, spr_read;
  wire spr_write, wb_rfaddrw0, wb_rfaddrw1, wb_rfaddrw2, wb_rfaddrw3,
       wb_rfaddrw4;
  assign dc_no_writethrough = 1'b0;
  assign ex_macrc_op = 1'b0;
  assign id_macrc_op = 1'b0;
  assign id_mac_op_0 = 1'b0;
  assign id_mac_op_1 = 1'b0;
  assign id_mac_op_2 = 1'b0;
  assign force_dslot_fetch = 1'b0;
  assign multicycle_1 = 1'b0;
  assign multicycle_2 = 1'b0;
  assign cust5_limm_0 = ex_insn_5;
  assign cust5_limm_1 = ex_insn_6;
  assign cust5_limm_2 = ex_insn_7;
  assign cust5_limm_3 = ex_insn_8;
  assign cust5_limm_4 = ex_insn_9;
  assign cust5_limm_5 = ex_insn_10;
  assign cust5_op_0 = ex_insn_0;
  assign cust5_op_1 = ex_insn_1;
  assign cust5_op_2 = ex_insn_2;
  assign cust5_op_3 = ex_insn_3;
  assign cust5_op_4 = ex_insn_4;
  assign ex_simm_16 = ex_simm_31;
  assign ex_simm_17 = ex_simm_31;
  assign ex_simm_18 = ex_simm_31;
  assign ex_simm_19 = ex_simm_31;
  assign ex_simm_20 = ex_simm_31;
  assign ex_simm_21 = ex_simm_31;
  assign ex_simm_22 = ex_simm_31;
  assign ex_simm_23 = ex_simm_31;
  assign ex_simm_24 = ex_simm_31;
  assign ex_simm_25 = ex_simm_31;
  assign ex_simm_26 = ex_simm_31;
  assign ex_simm_27 = ex_simm_31;
  assign ex_simm_28 = ex_simm_31;
  assign ex_simm_29 = ex_simm_31;
  assign ex_simm_30 = ex_simm_31;
  assign id_simm_0 = id_insn_0;
  assign id_simm_1 = id_insn_1;
  assign id_simm_2 = id_insn_2;
  assign id_simm_3 = id_insn_3;
  assign id_simm_4 = id_insn_4;
  assign id_simm_5 = id_insn_5;
  assign id_simm_6 = id_insn_6;
  assign id_simm_7 = id_insn_7;
  assign id_simm_8 = id_insn_8;
  assign id_simm_9 = id_insn_9;
  assign id_simm_10 = id_insn_10;
  assign id_simm_16 = id_simm_31;
  assign id_simm_17 = id_simm_31;
  assign id_simm_18 = id_simm_31;
  assign id_simm_19 = id_simm_31;
  assign id_simm_20 = id_simm_31;
  assign id_simm_21 = id_simm_31;
  assign id_simm_22 = id_simm_31;
  assign id_simm_23 = id_simm_31;
  assign id_simm_24 = id_simm_31;
  assign id_simm_25 = id_simm_31;
  assign id_simm_26 = id_simm_31;
  assign id_simm_27 = id_simm_31;
  assign id_simm_28 = id_simm_31;
  assign id_simm_29 = id_simm_31;
  assign id_simm_30 = id_simm_31;
  assign fpu_op_0 = 1'b0;
  assign fpu_op_1 = 1'b0;
  assign fpu_op_2 = 1'b0;
  assign fpu_op_3 = 1'b0;
  assign fpu_op_4 = 1'b0;
  assign fpu_op_5 = 1'b0;
  assign fpu_op_6 = 1'b0;
  assign fpu_op_7 = 1'b0;
  assign rfwb_op_3 = 1'b0;
  assign comp_op_0 = ex_insn_21;
  assign comp_op_2 = ex_insn_23;
  assign comp_op_3 = ex_insn_24;
  assign mac_op_0 = 1'b0;
  assign mac_op_1 = 1'b0;
  assign mac_op_2 = 1'b0;
  assign alu_op2_0 = ex_insn_6;
  assign alu_op2_1 = ex_insn_7;
  assign alu_op2_2 = ex_insn_8;
  assign alu_op2_3 = ex_insn_9;
  assign rf_rdb = if_insn_30;
  assign rf_rda = if_insn_31;
  assign rf_addrb_0 = if_insn_11;
  assign rf_addrb_1 = if_insn_12;
  assign rf_addrb_2 = if_insn_13;
  assign rf_addrb_3 = if_insn_14;
  assign rf_addrb_4 = if_insn_15;
  assign rf_addra_0 = if_insn_16;
  assign rf_addra_1 = if_insn_17;
  assign rf_addra_2 = if_insn_18;
  assign rf_addra_3 = if_insn_19;
  assign rf_addra_4 = if_insn_20;
  assign wb_flushpipe = if_flushpipe;
  assign ex_flushpipe = if_flushpipe;
  assign id_flushpipe = if_flushpipe;
  INVX1 g6947(.A (n_844), .Y (n_836));
  INVX1 g6948(.A (n_838), .Y (wait_on_1));
  INVX1 g6949(.A (du_hwbkpt), .Y (n_834));
  OAI21X1 g8933__2398(.A (sel_imm), .B (n_825), .C (n_833), .Y
       (sel_b_1));
  OR2X1 g8934__5107(.A (n_832), .B (sel_imm), .Y (sel_b_0));
  INVX1 g8935(.A (n_832), .Y (n_833));
  NOR3X1 g8936__6260(.A (sel_imm), .B (n_765), .C (n_711), .Y (n_832));
  INVX1 g8937(.A (n_686), .Y (id_lsu_op_2));
  NAND3X1 g8938__4319(.A (n_863), .B (n_708), .C (n_826), .Y (n_831));
  AND2X1 g8939__8428(.A (n_829), .B (n_828), .Y (sel_a_0));
  NAND2X1 g8940__5526(.A (n_827), .B (n_829), .Y (sel_a_1));
  AND2X1 g8941__6783(.A (n_826), .B (n_810), .Y (id_lsu_op_1));
  NAND3X1 g8942__3680(.A (n_843), .B (n_838), .C (n_824), .Y
       (wait_on_0));
  NAND3X1 g8943__1617(.A (wbforw_valid), .B (n_804), .C (n_825), .Y
       (n_830));
  INVX1 g8944(.A (n_827), .Y (n_828));
  OR2X1 g8945__2802(.A (n_823), .B (n_740), .Y (n_829));
  OR2X1 g8946__1705(.A (n_822), .B (n_742), .Y (n_827));
  OAI21X1 g8947__5122(.A (id_insn_30), .B (n_814), .C (n_688), .Y
       (id_simm_31));
  OR2X1 g8948__8246(.A (n_856), .B (id_lsu_op_3), .Y (n_826));
  OAI21X1 g8949__7098(.A (n_796), .B (id_void), .C (n_787), .Y
       (no_more_dslot));
  OR2X1 g8950__6131(.A (n_851), .B (n_812), .Y (n_824));
  OR2X1 g8951__1881(.A (n_704), .B (n_763), .Y (n_823));
  OR2X1 g8952__5115(.A (n_811), .B (n_740), .Y (n_825));
  OR2X1 g8953__7482(.A (id_lsu_op_0), .B (n_802), .Y (n_856));
  INVX1 g8954(.A (n_821), .Y (id_simm_15));
  INVX1 g8955(.A (n_820), .Y (id_simm_14));
  INVX1 g8956(.A (n_819), .Y (id_simm_13));
  INVX1 g8957(.A (n_818), .Y (id_simm_12));
  INVX1 g8958(.A (n_817), .Y (id_simm_11));
  OR2X1 g8959__4733(.A (n_700), .B (n_762), .Y (n_822));
  MUX2X1 g8960__6161(.A (id_insn_15), .B (id_insn_25), .S (n_809), .Y
       (n_821));
  MUX2X1 g8961__9315(.A (id_insn_14), .B (id_insn_24), .S (n_809), .Y
       (n_820));
  MUX2X1 g8962__9945(.A (id_insn_13), .B (id_insn_23), .S (n_809), .Y
       (n_819));
  MUX2X1 g8963__2883(.A (id_insn_12), .B (id_insn_22), .S (n_809), .Y
       (n_818));
  MUX2X1 g8964__2346(.A (id_insn_11), .B (id_insn_21), .S (n_809), .Y
       (n_817));
  NAND3X1 g8965__1666(.A (n_699), .B (n_710), .C (n_799), .Y (n_816));
  NAND3X1 g8966__7410(.A (n_702), .B (n_709), .C (n_791), .Y (n_815));
  OAI21X1 g8967__6417(.A (n_706), .B (n_793), .C (id_insn_15), .Y
       (n_814));
  AND2X1 g8968__5477(.A (n_808), .B (n_794), .Y (n_812));
  OR2X1 g8969__2398(.A (n_703), .B (n_685), .Y (n_811));
  OAI21X1 g8970__5107(.A (n_862), .B (n_784), .C (n_806), .Y (n_810));
  AOI21X1 g8971__6260(.A (n_860), .B (n_707), .C (id_insn_26), .Y
       (n_813));
  OR2X1 g8972__4319(.A (n_701), .B (id_insn_0), .Y (n_808));
  NAND2X1 g8973__8428(.A (id_insn_25), .B (id_lsu_op_3), .Y (n_807));
  AOI21X1 g8974__5526(.A (n_839), .B (n_861), .C (n_848), .Y
       (multicycle_0));
  NOR3X1 g8975__6783(.A (n_733), .B (n_848), .C (n_840), .Y (id_void));
  OR2X1 g8976__3680(.A (n_801), .B (n_783), .Y (n_809));
  OAI21X1 g8977__1617(.A (n_751), .B (n_860), .C (n_862), .Y (n_806));
  AOI22X1 g8978__2802(.A (n_786), .B (n_752), .C (n_760), .D (n_784),
       .Y (n_805));
  NOR3X1 g8979__1705(.A (n_761), .B (n_764), .C (n_713), .Y (n_804));
  NAND3X1 g8980__5122(.A (n_767), .B (n_766), .C (n_790), .Y (n_803));
  OAI21X1 g8981__8246(.A (n_848), .B (n_860), .C (n_687), .Y (n_802));
  OR2X1 g8982__7098(.A (n_789), .B (n_730), .Y (n_851));
  INVX1 g8983(.A (n_850), .Y (n_801));
  NAND2X1 g8984__6131(.A (id_insn_27), .B (n_786), .Y (n_800));
  AND2X1 g8985__1881(.A (n_697), .B (n_696), .Y (n_799));
  NAND2X1 g8986__5115(.A (n_692), .B (n_689), .Y (n_798));
  NAND2X1 g8987__7482(.A (id_insn_26), .B (n_786), .Y (n_797));
  OAI21X1 g8988__4733(.A (ex_branch_op_0), .B (n_748), .C
       (ex_branch_taken), .Y (n_796));
  OR2X1 g8989__6161(.A (n_785), .B (n_788), .Y (n_850));
  OR2X1 g8990__9315(.A (n_861), .B (n_863), .Y (n_843));
  OR2X1 g8991__9945(.A (n_849), .B (n_783), .Y (n_838));
  AND2X1 g8992__2883(.A (n_784), .B (n_788), .Y (id_lsu_op_3));
  AOI21X1 g8993__2346(.A (n_862), .B (n_863), .C (n_846), .Y (n_795));
  OR2X1 g8994__1666(.A (n_842), .B (n_714), .Y (n_794));
  AND2X1 g8995__7410(.A (n_849), .B (n_758), .Y (n_793));
  NAND2X1 g8996__6417(.A (id_insn_1), .B (n_779), .Y (n_792));
  AND2X1 g8997__5477(.A (n_694), .B (n_695), .Y (n_791));
  NAND2X1 g8998__2398(.A (n_787), .B (n_690), .Y (rfe));
  AND2X1 g8999__5107(.A (n_693), .B (n_698), .Y (n_790));
  NOR3X1 g9000__6260(.A (n_756), .B (n_755), .C (n_712), .Y (ex_void));
  OR2X1 g9001__4319(.A (n_849), .B (n_846), .Y (n_789));
  INVX1 g9002(.A (n_849), .Y (n_785));
  INVX1 g9003(.A (n_784), .Y (n_783));
  OR2X1 g9005__8428(.A (n_745), .B (n_750), .Y (if_flushpipe));
  AOI22X1 g9006__5526(.A (n_731), .B (wb_rfaddrw1), .C (wb_rfaddrw2),
       .D (n_716), .Y (n_782));
  AOI22X1 g9007__6783(.A (n_720), .B (wb_rfaddrw2), .C (wb_rfaddrw3),
       .D (n_738), .Y (n_781));
  AOI22X1 g9008__3680(.A (id_insn_17), .B (n_719), .C (n_723), .D
       (id_insn_20), .Y (n_780));
  NOR3X1 g9009__1617(.A (id_insn_3), .B (id_insn_4), .C (n_728), .Y
       (n_779));
  NAND3X1 g9010__2802(.A (id_branch_op_1), .B (id_branch_op_2), .C
       (n_743), .Y (n_778));
  NAND2X1 g9011__1705(.A (ex_insn_16), .B (n_691), .Y (n_777));
  OR2X1 g9012__5122(.A (n_859), .B (n_845), .Y (n_839));
  AND2X1 g9013__8246(.A (n_863), .B (id_insn_28), .Y (n_788));
  OR2X1 g9014__7098(.A (n_759), .B (n_844), .Y (n_840));
  OR2X1 g9015__6131(.A (n_705), .B (ex_branch_op_0), .Y (n_787));
  OR2X1 g9016__1881(.A (n_746), .B (n_741), .Y (n_842));
  AND2X1 g9017__5115(.A (n_753), .B (n_758), .Y (n_786));
  OR2X1 g9018__7482(.A (n_759), .B (n_846), .Y (n_861));
  OR2X1 g9019__4733(.A (n_759), .B (n_757), .Y (n_860));
  OR2X1 g9020__6161(.A (n_863), .B (id_insn_28), .Y (n_849));
  AND2X1 g9021__9315(.A (n_758), .B (id_insn_30), .Y (n_784));
  AOI22X1 g9022__9945(.A (id_insn_18), .B (n_736), .C (n_727), .D
       (id_insn_19), .Y (n_776));
  AOI22X1 g9023__2883(.A (n_724), .B (wb_rfaddrw1), .C (wb_rfaddrw4),
       .D (n_735), .Y (n_775));
  AOI22X1 g9024__2346(.A (n_724), .B (rf_addrw_1), .C (rf_addrw_2), .D
       (n_720), .Y (n_774));
  AOI22X1 g9025__1666(.A (n_738), .B (rf_addrw_3), .C (rf_addrw_4), .D
       (n_735), .Y (n_773));
  AOI22X1 g9026__7410(.A (n_734), .B (id_insn_19), .C (id_insn_20), .D
       (n_718), .Y (n_772));
  AOI22X1 g9027__6417(.A (n_725), .B (id_insn_17), .C (id_insn_18), .D
       (n_726), .Y (n_771));
  AOI22X1 g9028__5477(.A (n_731), .B (rf_addrw_1), .C (rf_addrw_3), .D
       (n_717), .Y (n_770));
  AOI22X1 g9029__2398(.A (id_insn_12), .B (n_725), .C (n_734), .D
       (id_insn_14), .Y (n_769));
  AOI22X1 g9030__5107(.A (id_insn_12), .B (n_719), .C (n_736), .D
       (id_insn_13), .Y (n_768));
  MUX2X1 g9031__6260(.A (n_716), .B (id_insn_13), .S (rf_addrw_2), .Y
       (n_767));
  XNOR2X1 g9032__4319(.A (id_insn_11), .B (rf_addrw_0), .Y (n_766));
  XOR2X1 g9033__8428(.A (id_insn_11), .B (wb_rfaddrw0), .Y (n_765));
  XOR2X1 g9034__5526(.A (id_insn_14), .B (wb_rfaddrw3), .Y (n_764));
  MUX2X1 g9035__6783(.A (id_insn_16), .B (n_733), .S (rf_addrw_0), .Y
       (n_763));
  MUX2X1 g9036__3680(.A (id_insn_16), .B (n_733), .S (wb_rfaddrw0), .Y
       (n_762));
  MUX2X1 g9037__1617(.A (wb_rfaddrw4), .B (n_723), .S (id_insn_15), .Y
       (n_761));
  INVX1 g9039(.A (n_847), .Y (n_760));
  INVX1 g9040(.A (n_758), .Y (n_757));
  OR2X1 g9041__2802(.A (n_729), .B (ex_insn_29), .Y (n_756));
  AND2X1 g9042__1705(.A (spr_write), .B (n_739), .Y (ex_spr_write));
  AND2X1 g9043__5122(.A (spr_read), .B (n_739), .Y (ex_spr_read));
  OR2X1 g9044__8246(.A (n_744), .B (ex_insn_27), .Y (n_755));
  OR2X1 g9045__7098(.A (id_insn_31), .B (id_insn_29), .Y (n_844));
  OR2X1 g9046__6131(.A (n_732), .B (id_insn_26), .Y (n_847));
  OR2X1 g9047__1881(.A (n_737), .B (id_insn_31), .Y (n_845));
  OR2X1 g9048__5115(.A (n_721), .B (id_insn_30), .Y (n_759));
  AND2X1 g9049__7482(.A (n_737), .B (id_insn_31), .Y (n_758));
  OR2X1 g9050__4733(.A (n_715), .B (id_insn_27), .Y (n_848));
  INVX1 g9052(.A (n_859), .Y (n_753));
  INVX1 g9053(.A (n_862), .Y (n_752));
  INVX1 g9054(.A (n_863), .Y (n_751));
  OR2X1 g9055__6161(.A (except_flushpipe), .B (extend_flush), .Y
       (n_750));
  NAND2X1 g9056__9315(.A (ex_branch_op_2), .B (ex_branch_op_1), .Y
       (n_749));
  OR2X1 g9057__9945(.A (ex_branch_op_1), .B (ex_branch_op_2), .Y
       (n_748));
  NOR2X1 g9058__2883(.A (ex_insn_30), .B (ex_insn_31), .Y (n_747));
  OR2X1 g9059__2346(.A (id_insn_4), .B (id_insn_2), .Y (n_746));
  OR2X1 g9060__1666(.A (pc_we), .B (du_flush_pipe), .Y (n_745));
  NOR2X1 g9061__7410(.A (id_insn_1), .B (id_insn_0), .Y (n_754));
  OR2X1 g9062__6417(.A (id_insn_30), .B (id_insn_28), .Y (n_859));
  OR2X1 g9063__5477(.A (n_722), .B (n_737), .Y (n_846));
  OR2X1 g9064__2398(.A (n_732), .B (n_715), .Y (n_862));
  OR2X1 g9065__5107(.A (id_insn_26), .B (id_insn_27), .Y (n_863));
  INVX1 g9066(.A (ex_insn_26), .Y (n_744));
  INVX1 g9067(.A (id_branch_op_0), .Y (n_743));
  INVX1 g9068(.A (wbforw_valid), .Y (n_742));
  INVX1 g9069(.A (id_insn_3), .Y (n_741));
  INVX1 g9070(.A (rfwb_op_0), .Y (n_740));
  INVX1 g9071(.A (abort_mvspr), .Y (n_739));
  INVX1 g9072(.A (id_insn_19), .Y (n_738));
  INVX1 g9073(.A (id_insn_29), .Y (n_737));
  INVX1 g9074(.A (wb_rfaddrw2), .Y (n_736));
  INVX1 g9075(.A (id_insn_20), .Y (n_735));
  INVX1 g9076(.A (rf_addrw_3), .Y (n_734));
  INVX1 g9077(.A (id_insn_16), .Y (n_733));
  INVX1 g9078(.A (id_insn_27), .Y (n_732));
  INVX1 g9079(.A (id_insn_12), .Y (n_731));
  INVX1 g9080(.A (id_insn_30), .Y (n_730));
  INVX1 g9082(.A (ex_insn_28), .Y (n_729));
  INVX1 g9083(.A (id_insn_2), .Y (n_728));
  INVX1 g9084(.A (wb_rfaddrw3), .Y (n_727));
  INVX1 g9085(.A (rf_addrw_2), .Y (n_726));
  INVX1 g9086(.A (rf_addrw_1), .Y (n_725));
  INVX1 g9087(.A (id_insn_17), .Y (n_724));
  INVX1 g9088(.A (wb_rfaddrw4), .Y (n_723));
  INVX1 g9089(.A (id_insn_31), .Y (n_722));
  INVX1 g9090(.A (id_insn_28), .Y (n_721));
  INVX1 g9091(.A (id_insn_18), .Y (n_720));
  INVX1 g9092(.A (wb_rfaddrw1), .Y (n_719));
  INVX1 g9093(.A (rf_addrw_4), .Y (n_718));
  INVX1 g9094(.A (id_insn_14), .Y (n_717));
  INVX1 g9095(.A (id_insn_13), .Y (n_716));
  INVX1 g9096(.A (id_insn_26), .Y (n_715));
  INVX1 drc_bufs9098(.A (n_714), .Y (n_841));
  BUFX2 drc_bufs9100(.A (n_798), .Y (n_713));
  BUFX2 drc_bufs9101(.A (n_777), .Y (n_712));
  BUFX2 drc_bufs9102(.A (n_830), .Y (n_711));
  BUFX2 drc_bufs9103(.A (n_780), .Y (n_710));
  BUFX2 drc_bufs9104(.A (n_773), .Y (n_709));
  BUFX2 drc_bufs9105(.A (n_805), .Y (n_708));
  BUFX2 drc_bufs9106(.A (n_800), .Y (n_707));
  BUFX2 drc_bufs9107(.A (n_795), .Y (n_706));
  BUFX2 drc_bufs9108(.A (n_749), .Y (n_705));
  BUFX2 drc_bufs9109(.A (n_815), .Y (n_704));
  BUFX2 drc_bufs9110(.A (n_803), .Y (n_703));
  BUFX2 drc_bufs9115(.A (n_774), .Y (n_702));
  BUFX2 drc_bufs9116(.A (n_792), .Y (n_701));
  BUFX2 drc_bufs9117(.A (n_816), .Y (n_700));
  BUFX2 drc_bufs9118(.A (n_781), .Y (n_699));
  BUFX2 drc_bufs9119(.A (n_769), .Y (n_698));
  BUFX2 drc_bufs9120(.A (n_776), .Y (n_697));
  BUFX2 drc_bufs9121(.A (n_775), .Y (n_696));
  BUFX2 drc_bufs9122(.A (n_772), .Y (n_695));
  BUFX2 drc_bufs9123(.A (n_771), .Y (n_694));
  BUFX2 drc_bufs9124(.A (n_770), .Y (n_693));
  BUFX2 drc_bufs9125(.A (n_782), .Y (n_692));
  BUFX2 drc_bufs9126(.A (n_747), .Y (n_691));
  BUFX2 drc_bufs9127(.A (n_778), .Y (n_690));
  BUFX2 drc_bufs9128(.A (n_768), .Y (n_689));
  BUFX2 drc_bufs9129(.A (n_807), .Y (n_688));
  BUFX2 drc_bufs9130(.A (n_797), .Y (n_687));
  BUFX2 drc_bufs9131(.A (n_831), .Y (n_686));
  BUFX2 drc_bufs9132(.A (n_813), .Y (id_lsu_op_0));
  BUFX2 drc_bufs9133(.A (n_754), .Y (n_714));
  XOR2X1 g2__6260(.A (id_insn_15), .B (rf_addrw_4), .Y (n_685));
  DFFPOSX1 \alu_op2_reg[0] (.CLK (clk), .D (n_610), .Q (ex_insn_6));
  DFFPOSX1 \alu_op2_reg[1] (.CLK (clk), .D (n_604), .Q (ex_insn_7));
  DFFPOSX1 \alu_op2_reg[2] (.CLK (clk), .D (n_598), .Q (ex_insn_8));
  DFFPOSX1 \alu_op2_reg[3] (.CLK (clk), .D (n_596), .Q (ex_insn_9));
  DFFPOSX1 \alu_op_reg[0] (.CLK (clk), .D (n_649), .Q (alu_op_0));
  DFFPOSX1 \alu_op_reg[1] (.CLK (clk), .D (n_126), .Q (alu_op_1));
  DFFPOSX1 \alu_op_reg[2] (.CLK (clk), .D (n_163), .Q (alu_op_2));
  DFFPOSX1 \alu_op_reg[3] (.CLK (clk), .D (n_644), .Q (alu_op_3));
  DFFPOSX1 \alu_op_reg[4] (.CLK (clk), .D (n_652), .Q (alu_op_4));
  DFFPOSX1 \comp_op_reg[0] (.CLK (clk), .D (n_586), .Q (ex_insn_21));
  DFFPOSX1 \comp_op_reg[1] (.CLK (clk), .D (n_614), .Q (comp_op_1));
  DFFPOSX1 \comp_op_reg[2] (.CLK (clk), .D (n_585), .Q (ex_insn_23));
  DFFPOSX1 \comp_op_reg[3] (.CLK (clk), .D (n_584), .Q (ex_insn_24));
  DFFPOSX1 \ex_branch_addrtarget_reg[2] (.CLK (clk), .D (n_152), .Q
       (ex_branch_addrtarget_2));
  DFFPOSX1 \ex_branch_addrtarget_reg[3] (.CLK (clk), .D (n_153), .Q
       (ex_branch_addrtarget_3));
  DFFPOSX1 \ex_branch_addrtarget_reg[4] (.CLK (clk), .D (n_124), .Q
       (ex_branch_addrtarget_4));
  DFFPOSX1 \ex_branch_addrtarget_reg[5] (.CLK (clk), .D (n_122), .Q
       (ex_branch_addrtarget_5));
  DFFPOSX1 \ex_branch_addrtarget_reg[6] (.CLK (clk), .D (n_157), .Q
       (ex_branch_addrtarget_6));
  DFFPOSX1 \ex_branch_addrtarget_reg[7] (.CLK (clk), .D (n_114), .Q
       (ex_branch_addrtarget_7));
  DFFPOSX1 \ex_branch_addrtarget_reg[8] (.CLK (clk), .D (n_113), .Q
       (ex_branch_addrtarget_8));
  DFFPOSX1 \ex_branch_addrtarget_reg[9] (.CLK (clk), .D (n_115), .Q
       (ex_branch_addrtarget_9));
  DFFPOSX1 \ex_branch_addrtarget_reg[10] (.CLK (clk), .D (n_161), .Q
       (ex_branch_addrtarget_10));
  DFFPOSX1 \ex_branch_addrtarget_reg[11] (.CLK (clk), .D (n_112), .Q
       (ex_branch_addrtarget_11));
  DFFPOSX1 \ex_branch_addrtarget_reg[12] (.CLK (clk), .D (n_111), .Q
       (ex_branch_addrtarget_12));
  DFFPOSX1 \ex_branch_addrtarget_reg[13] (.CLK (clk), .D (n_110), .Q
       (ex_branch_addrtarget_13));
  DFFPOSX1 \ex_branch_addrtarget_reg[14] (.CLK (clk), .D (n_108), .Q
       (ex_branch_addrtarget_14));
  DFFPOSX1 \ex_branch_addrtarget_reg[15] (.CLK (clk), .D (n_109), .Q
       (ex_branch_addrtarget_15));
  DFFPOSX1 \ex_branch_addrtarget_reg[16] (.CLK (clk), .D (n_107), .Q
       (ex_branch_addrtarget_16));
  DFFPOSX1 \ex_branch_addrtarget_reg[17] (.CLK (clk), .D (n_156), .Q
       (ex_branch_addrtarget_17));
  DFFPOSX1 \ex_branch_addrtarget_reg[18] (.CLK (clk), .D (n_79), .Q
       (ex_branch_addrtarget_18));
  DFFPOSX1 \ex_branch_addrtarget_reg[19] (.CLK (clk), .D (n_95), .Q
       (ex_branch_addrtarget_19));
  DFFPOSX1 \ex_branch_addrtarget_reg[20] (.CLK (clk), .D (n_104), .Q
       (ex_branch_addrtarget_20));
  DFFPOSX1 \ex_branch_addrtarget_reg[21] (.CLK (clk), .D (n_105), .Q
       (ex_branch_addrtarget_21));
  DFFPOSX1 \ex_branch_addrtarget_reg[22] (.CLK (clk), .D (n_119), .Q
       (ex_branch_addrtarget_22));
  DFFPOSX1 \ex_branch_addrtarget_reg[23] (.CLK (clk), .D (n_101), .Q
       (ex_branch_addrtarget_23));
  DFFPOSX1 \ex_branch_addrtarget_reg[24] (.CLK (clk), .D (n_100), .Q
       (ex_branch_addrtarget_24));
  DFFPOSX1 \ex_branch_addrtarget_reg[25] (.CLK (clk), .D (n_118), .Q
       (ex_branch_addrtarget_25));
  DFFPOSX1 \ex_branch_addrtarget_reg[26] (.CLK (clk), .D (n_94), .Q
       (ex_branch_addrtarget_26));
  DFFPOSX1 \ex_branch_addrtarget_reg[27] (.CLK (clk), .D (n_129), .Q
       (ex_branch_addrtarget_27));
  DFFPOSX1 \ex_branch_addrtarget_reg[28] (.CLK (clk), .D (n_84), .Q
       (ex_branch_addrtarget_28));
  DFFPOSX1 \ex_branch_addrtarget_reg[29] (.CLK (clk), .D (n_93), .Q
       (ex_branch_addrtarget_29));
  DFFPOSX1 \ex_branch_addrtarget_reg[30] (.CLK (clk), .D (n_92), .Q
       (ex_branch_addrtarget_30));
  DFFPOSX1 \ex_branch_addrtarget_reg[31] (.CLK (clk), .D (n_89), .Q
       (ex_branch_addrtarget_31));
  DFFPOSX1 \ex_branch_op_reg[0] (.CLK (clk), .D (n_583), .Q
       (ex_branch_op_0));
  DFFPOSX1 \ex_branch_op_reg[1] (.CLK (clk), .D (n_613), .Q
       (ex_branch_op_1));
  DFFPOSX1 \ex_branch_op_reg[2] (.CLK (clk), .D (n_612), .Q
       (ex_branch_op_2));
  DFFPOSX1 \ex_insn_reg[0] (.CLK (clk), .D (n_611), .Q (ex_insn_0));
  DFFPOSX1 \ex_insn_reg[1] (.CLK (clk), .D (n_609), .Q (ex_insn_1));
  DFFPOSX1 \ex_insn_reg[2] (.CLK (clk), .D (n_608), .Q (ex_insn_2));
  DFFPOSX1 \ex_insn_reg[3] (.CLK (clk), .D (n_607), .Q (ex_insn_3));
  DFFPOSX1 \ex_insn_reg[4] (.CLK (clk), .D (n_606), .Q (ex_insn_4));
  DFFPOSX1 \ex_insn_reg[5] (.CLK (clk), .D (n_605), .Q (ex_insn_5));
  DFFPOSX1 \ex_insn_reg[10] (.CLK (clk), .D (n_603), .Q (ex_insn_10));
  DFFPOSX1 \ex_insn_reg[11] (.CLK (clk), .D (n_602), .Q (ex_insn_11));
  DFFPOSX1 \ex_insn_reg[12] (.CLK (clk), .D (n_601), .Q (ex_insn_12));
  DFFPOSX1 \ex_insn_reg[13] (.CLK (clk), .D (n_600), .Q (ex_insn_13));
  DFFPOSX1 \ex_insn_reg[14] (.CLK (clk), .D (n_599), .Q (ex_insn_14));
  DFFPOSX1 \ex_insn_reg[15] (.CLK (clk), .D (n_597), .Q (ex_insn_15));
  DFFPOSX1 \ex_insn_reg[16] (.CLK (clk), .D (n_72), .Q (ex_insn_16));
  DFFPOSX1 \ex_insn_reg[17] (.CLK (clk), .D (n_595), .Q (ex_insn_17));
  DFFPOSX1 \ex_insn_reg[18] (.CLK (clk), .D (n_594), .Q (ex_insn_18));
  DFFPOSX1 \ex_insn_reg[19] (.CLK (clk), .D (n_593), .Q (ex_insn_19));
  DFFPOSX1 \ex_insn_reg[20] (.CLK (clk), .D (n_592), .Q (ex_insn_20));
  DFFPOSX1 \ex_insn_reg[22] (.CLK (clk), .D (n_159), .Q (ex_insn_22));
  DFFPOSX1 \ex_insn_reg[25] (.CLK (clk), .D (n_591), .Q (ex_insn_25));
  DFFPOSX1 \ex_insn_reg[26] (.CLK (clk), .D (n_76), .Q (ex_insn_26));
  DFFPOSX1 \ex_insn_reg[27] (.CLK (clk), .D (n_590), .Q (ex_insn_27));
  DFFPOSX1 \ex_insn_reg[28] (.CLK (clk), .D (n_77), .Q (ex_insn_28));
  DFFPOSX1 \ex_insn_reg[29] (.CLK (clk), .D (n_589), .Q (ex_insn_29));
  DFFPOSX1 \ex_insn_reg[30] (.CLK (clk), .D (n_588), .Q (ex_insn_30));
  DFFPOSX1 \ex_insn_reg[31] (.CLK (clk), .D (n_587), .Q (ex_insn_31));
  DFFPOSX1 \ex_simm_reg[0] (.CLK (clk), .D (n_143), .Q (ex_simm_0));
  DFFPOSX1 \ex_simm_reg[1] (.CLK (clk), .D (n_142), .Q (ex_simm_1));
  DFFPOSX1 \ex_simm_reg[2] (.CLK (clk), .D (n_140), .Q (ex_simm_2));
  DFFPOSX1 \ex_simm_reg[3] (.CLK (clk), .D (n_139), .Q (ex_simm_3));
  DFFPOSX1 \ex_simm_reg[4] (.CLK (clk), .D (n_138), .Q (ex_simm_4));
  DFFPOSX1 \ex_simm_reg[5] (.CLK (clk), .D (n_137), .Q (ex_simm_5));
  DFFPOSX1 \ex_simm_reg[6] (.CLK (clk), .D (n_135), .Q (ex_simm_6));
  DFFPOSX1 \ex_simm_reg[7] (.CLK (clk), .D (n_134), .Q (ex_simm_7));
  DFFPOSX1 \ex_simm_reg[8] (.CLK (clk), .D (n_133), .Q (ex_simm_8));
  DFFPOSX1 \ex_simm_reg[9] (.CLK (clk), .D (n_132), .Q (ex_simm_9));
  DFFPOSX1 \ex_simm_reg[10] (.CLK (clk), .D (n_131), .Q (ex_simm_10));
  DFFPOSX1 \ex_simm_reg[11] (.CLK (clk), .D (n_415), .Q (ex_simm_11));
  DFFPOSX1 \ex_simm_reg[12] (.CLK (clk), .D (n_414), .Q (ex_simm_12));
  DFFPOSX1 \ex_simm_reg[13] (.CLK (clk), .D (n_413), .Q (ex_simm_13));
  DFFPOSX1 \ex_simm_reg[14] (.CLK (clk), .D (n_412), .Q (ex_simm_14));
  DFFPOSX1 \ex_simm_reg[15] (.CLK (clk), .D (n_411), .Q (ex_simm_15));
  DFFPOSX1 \ex_simm_reg[16] (.CLK (clk), .D (n_410), .Q (ex_simm_31));
  DFFPOSX1 except_illegal_reg(.CLK (clk), .D (n_682), .Q
       (except_illegal));
  DFFPOSX1 \id_branch_op_reg[0] (.CLK (clk), .D (n_630), .Q
       (id_branch_op_0));
  DFFPOSX1 \id_branch_op_reg[1] (.CLK (clk), .D (n_86), .Q
       (id_branch_op_1));
  DFFPOSX1 \id_branch_op_reg[2] (.CLK (clk), .D (n_78), .Q
       (id_branch_op_2));
  DFFPOSX1 \id_insn_reg[0] (.CLK (clk), .D (n_524), .Q (id_insn_0));
  DFFPOSX1 \id_insn_reg[1] (.CLK (clk), .D (n_523), .Q (id_insn_1));
  DFFPOSX1 \id_insn_reg[2] (.CLK (clk), .D (n_522), .Q (id_insn_2));
  DFFPOSX1 \id_insn_reg[3] (.CLK (clk), .D (n_521), .Q (id_insn_3));
  DFFPOSX1 \id_insn_reg[4] (.CLK (clk), .D (n_520), .Q (id_insn_4));
  DFFPOSX1 \id_insn_reg[5] (.CLK (clk), .D (n_519), .Q (id_insn_5));
  DFFPOSX1 \id_insn_reg[6] (.CLK (clk), .D (n_518), .Q (id_insn_6));
  DFFPOSX1 \id_insn_reg[7] (.CLK (clk), .D (n_517), .Q (id_insn_7));
  DFFPOSX1 \id_insn_reg[8] (.CLK (clk), .D (n_525), .Q (id_insn_8));
  DFFPOSX1 \id_insn_reg[9] (.CLK (clk), .D (n_526), .Q (id_insn_9));
  DFFPOSX1 \id_insn_reg[10] (.CLK (clk), .D (n_527), .Q (id_insn_10));
  DFFPOSX1 \id_insn_reg[11] (.CLK (clk), .D (n_529), .Q (id_insn_11));
  DFFPOSX1 \id_insn_reg[12] (.CLK (clk), .D (n_530), .Q (id_insn_12));
  DFFPOSX1 \id_insn_reg[13] (.CLK (clk), .D (n_531), .Q (id_insn_13));
  DFFPOSX1 \id_insn_reg[14] (.CLK (clk), .D (n_532), .Q (id_insn_14));
  DFFPOSX1 \id_insn_reg[15] (.CLK (clk), .D (n_533), .Q (id_insn_15));
  DFFPOSX1 \id_insn_reg[16] (.CLK (clk), .D (n_141), .Q (id_insn_16));
  DFFPOSX1 \id_insn_reg[17] (.CLK (clk), .D (n_534), .Q (id_insn_17));
  DFFPOSX1 \id_insn_reg[18] (.CLK (clk), .D (n_535), .Q (id_insn_18));
  DFFPOSX1 \id_insn_reg[19] (.CLK (clk), .D (n_536), .Q (id_insn_19));
  DFFPOSX1 \id_insn_reg[20] (.CLK (clk), .D (n_537), .Q (id_insn_20));
  DFFPOSX1 \id_insn_reg[21] (.CLK (clk), .D (n_538), .Q (id_insn_21));
  DFFPOSX1 \id_insn_reg[22] (.CLK (clk), .D (n_146), .Q (id_insn_22));
  DFFPOSX1 \id_insn_reg[23] (.CLK (clk), .D (n_539), .Q (id_insn_23));
  DFFPOSX1 \id_insn_reg[24] (.CLK (clk), .D (n_540), .Q (id_insn_24));
  DFFPOSX1 \id_insn_reg[25] (.CLK (clk), .D (n_541), .Q (id_insn_25));
  DFFPOSX1 \id_insn_reg[26] (.CLK (clk), .D (n_150), .Q (id_insn_26));
  DFFPOSX1 \id_insn_reg[27] (.CLK (clk), .D (n_542), .Q (id_insn_27));
  DFFPOSX1 \id_insn_reg[28] (.CLK (clk), .D (n_128), .Q (id_insn_28));
  DFFPOSX1 \id_insn_reg[29] (.CLK (clk), .D (n_481), .Q (id_insn_29));
  DFFPOSX1 \id_insn_reg[30] (.CLK (clk), .D (n_543), .Q (id_insn_30));
  DFFPOSX1 \id_insn_reg[31] (.CLK (clk), .D (n_544), .Q (id_insn_31));
  DFFPOSX1 \rf_addrw_reg[0] (.CLK (clk), .D (n_106), .Q (rf_addrw_0));
  DFFPOSX1 \rf_addrw_reg[1] (.CLK (clk), .D (n_662), .Q (rf_addrw_1));
  DFFPOSX1 \rf_addrw_reg[2] (.CLK (clk), .D (n_661), .Q (rf_addrw_2));
  DFFPOSX1 \rf_addrw_reg[3] (.CLK (clk), .D (n_136), .Q (rf_addrw_3));
  DFFPOSX1 \rf_addrw_reg[4] (.CLK (clk), .D (n_663), .Q (rf_addrw_4));
  DFFPOSX1 \rfwb_op_reg[0] (.CLK (clk), .D (n_103), .Q (rfwb_op_0));
  DFFPOSX1 \rfwb_op_reg[1] (.CLK (clk), .D (n_670), .Q (rfwb_op_1));
  DFFPOSX1 \rfwb_op_reg[2] (.CLK (clk), .D (n_669), .Q (rfwb_op_2));
  DFFPOSX1 sel_imm_reg(.CLK (clk), .D (n_91), .Q (sel_imm));
  DFFPOSX1 sig_syscall_reg(.CLK (clk), .D (n_635), .Q (sig_syscall));
  DFFPOSX1 sig_trap_reg(.CLK (clk), .D (n_646), .Q (sig_trap));
  DFFPOSX1 spr_read_reg(.CLK (clk), .D (n_120), .Q (spr_read));
  DFFPOSX1 spr_write_reg(.CLK (clk), .D (n_116), .Q (spr_write));
  DFFPOSX1 \wb_insn_reg[0] (.CLK (clk), .D (n_90), .Q (wb_insn_0));
  DFFPOSX1 \wb_insn_reg[1] (.CLK (clk), .D (n_165), .Q (wb_insn_1));
  DFFPOSX1 \wb_insn_reg[2] (.CLK (clk), .D (n_117), .Q (wb_insn_2));
  DFFPOSX1 \wb_insn_reg[3] (.CLK (clk), .D (n_75), .Q (wb_insn_3));
  DFFPOSX1 \wb_insn_reg[4] (.CLK (clk), .D (n_85), .Q (wb_insn_4));
  DFFPOSX1 \wb_insn_reg[5] (.CLK (clk), .D (n_74), .Q (wb_insn_5));
  DFFPOSX1 \wb_insn_reg[6] (.CLK (clk), .D (n_73), .Q (wb_insn_6));
  DFFPOSX1 \wb_insn_reg[7] (.CLK (clk), .D (n_121), .Q (wb_insn_7));
  DFFPOSX1 \wb_insn_reg[8] (.CLK (clk), .D (n_71), .Q (wb_insn_8));
  DFFPOSX1 \wb_insn_reg[9] (.CLK (clk), .D (n_162), .Q (wb_insn_9));
  DFFPOSX1 \wb_insn_reg[10] (.CLK (clk), .D (n_123), .Q (wb_insn_10));
  DFFPOSX1 \wb_insn_reg[11] (.CLK (clk), .D (n_70), .Q (wb_insn_11));
  DFFPOSX1 \wb_insn_reg[12] (.CLK (clk), .D (n_87), .Q (wb_insn_12));
  DFFPOSX1 \wb_insn_reg[13] (.CLK (clk), .D (n_83), .Q (wb_insn_13));
  DFFPOSX1 \wb_insn_reg[14] (.CLK (clk), .D (n_125), .Q (wb_insn_14));
  DFFPOSX1 \wb_insn_reg[15] (.CLK (clk), .D (n_151), .Q (wb_insn_15));
  DFFPOSX1 \wb_insn_reg[16] (.CLK (clk), .D (n_144), .Q (wb_insn_16));
  DFFPOSX1 \wb_insn_reg[17] (.CLK (clk), .D (n_145), .Q (wb_insn_17));
  DFFPOSX1 \wb_insn_reg[18] (.CLK (clk), .D (n_158), .Q (wb_insn_18));
  DFFPOSX1 \wb_insn_reg[19] (.CLK (clk), .D (n_155), .Q (wb_insn_19));
  DFFPOSX1 \wb_insn_reg[20] (.CLK (clk), .D (n_160), .Q (wb_insn_20));
  DFFPOSX1 \wb_insn_reg[21] (.CLK (clk), .D (n_96), .Q (wb_insn_21));
  DFFPOSX1 \wb_insn_reg[22] (.CLK (clk), .D (n_82), .Q (wb_insn_22));
  DFFPOSX1 \wb_insn_reg[23] (.CLK (clk), .D (n_97), .Q (wb_insn_23));
  DFFPOSX1 \wb_insn_reg[24] (.CLK (clk), .D (n_148), .Q (wb_insn_24));
  DFFPOSX1 \wb_insn_reg[25] (.CLK (clk), .D (n_127), .Q (wb_insn_25));
  DFFPOSX1 \wb_insn_reg[26] (.CLK (clk), .D (n_80), .Q (wb_insn_26));
  DFFPOSX1 \wb_insn_reg[27] (.CLK (clk), .D (n_102), .Q (wb_insn_27));
  DFFPOSX1 \wb_insn_reg[28] (.CLK (clk), .D (n_81), .Q (wb_insn_28));
  DFFPOSX1 \wb_insn_reg[29] (.CLK (clk), .D (n_130), .Q (wb_insn_29));
  DFFPOSX1 \wb_insn_reg[30] (.CLK (clk), .D (n_154), .Q (wb_insn_30));
  DFFPOSX1 \wb_insn_reg[31] (.CLK (clk), .D (n_99), .Q (wb_insn_31));
  DFFPOSX1 \wb_rfaddrw_reg[0] (.CLK (clk), .D (n_88), .Q (wb_rfaddrw0));
  DFFPOSX1 \wb_rfaddrw_reg[1] (.CLK (clk), .D (n_149), .Q
       (wb_rfaddrw1));
  DFFPOSX1 \wb_rfaddrw_reg[2] (.CLK (clk), .D (n_147), .Q
       (wb_rfaddrw2));
  DFFPOSX1 \wb_rfaddrw_reg[3] (.CLK (clk), .D (n_164), .Q
       (wb_rfaddrw3));
  DFFPOSX1 \wb_rfaddrw_reg[4] (.CLK (clk), .D (n_98), .Q (wb_rfaddrw4));
  AOI21X1 g9683__4319(.A (n_193), .B (n_681), .C (rst), .Y (n_684));
  NAND3X1 g9684__8428(.A (n_354), .B (n_203), .C (n_205), .Y (n_683));
  OAI21X1 g9686__5526(.A (id_insn_9), .B (n_667), .C (n_179), .Y
       (n_682));
  OAI21X1 g9687__6783(.A (n_357), .B (n_671), .C (n_254), .Y (n_681));
  AOI21X1 g9688__3680(.A (n_192), .B (n_196), .C (rst), .Y (n_680));
  AOI22X1 g9689__1617(.A (n_668), .B (n_465), .C (except_illegal), .D
       (n_211), .Y (n_679));
  AOI22X1 g9690__2802(.A (n_677), .B (n_512), .C (alu_op_2), .D
       (n_211), .Y (n_678));
  OR2X1 g9697__1705(.A (n_664), .B (n_358), .Y (n_677));
  NAND2X1 g9698__5122(.A (n_185), .B (n_582), .Y (n_676));
  NAND2X1 g9699__8246(.A (n_186), .B (n_582), .Y (n_675));
  NAND3X1 g9703__7098(.A (n_217), .B (n_639), .C (n_204), .Y (n_674));
  NAND2X1 g9704__6131(.A (n_207), .B (n_184), .Y (n_673));
  NAND2X1 g9705__1881(.A (n_207), .B (n_181), .Y (n_672));
  OAI21X1 g9706__5115(.A (n_240), .B (n_645), .C (n_640), .Y (n_671));
  AND2X1 g9707__7482(.A (n_655), .B (n_216), .Y (n_670));
  AND2X1 g9708__4733(.A (n_654), .B (n_216), .Y (n_669));
  OR2X1 g9709__6161(.A (n_653), .B (n_189), .Y (n_668));
  OR2X1 g9710__9315(.A (n_191), .B (id_insn_8), .Y (n_667));
  AOI22X1 g9711__9945(.A (n_351), .B (n_199), .C (id_branch_op_2), .D
       (n_353), .Y (n_666));
  AOI22X1 g9712__2883(.A (n_351), .B (n_638), .C (id_branch_op_1), .D
       (n_353), .Y (n_665));
  OAI21X1 g9713__2346(.A (n_515), .B (n_642), .C (n_843), .Y (n_664));
  INVX1 g9718(.A (n_23), .Y (n_663));
  INVX1 g9719(.A (n_40), .Y (n_662));
  INVX1 g9720(.A (n_12), .Y (n_661));
  AOI22X1 g9721__1666(.A (n_637), .B (id_insn_25), .C (n_253), .D
       (rf_addrw_4), .Y (n_660));
  AOI22X1 g9722__7410(.A (n_637), .B (id_insn_22), .C (n_253), .D
       (rf_addrw_1), .Y (n_659));
  AOI22X1 g9723__6417(.A (n_637), .B (id_insn_23), .C (n_253), .D
       (rf_addrw_2), .Y (n_658));
  AOI22X1 g9724__5477(.A (n_637), .B (id_insn_24), .C (n_253), .D
       (rf_addrw_3), .Y (n_657));
  AOI22X1 g9725__2398(.A (n_637), .B (id_insn_21), .C (n_253), .D
       (rf_addrw_0), .Y (n_656));
  OAI21X1 g9726__5107(.A (n_255), .B (n_640), .C (n_171), .Y (n_655));
  OAI21X1 g9727__6260(.A (n_255), .B (n_202), .C (n_174), .Y (n_654));
  MUX2X1 g9728__4319(.A (n_636), .B (n_197), .S (id_insn_31), .Y
       (n_653));
  INVX1 g9736(.A (n_16), .Y (n_652));
  AOI22X1 g9737__8428(.A (n_201), .B (n_367), .C (if_insn_29), .D
       (n_580), .Y (n_651));
  NAND2X1 g9738__5526(.A (n_187), .B (n_170), .Y (n_650));
  OAI21X1 g9739__6783(.A (n_236), .B (n_213), .C (n_173), .Y (n_649));
  AOI22X1 g9740__3680(.A (n_512), .B (n_620), .C (alu_op_4), .D
       (n_211), .Y (n_648));
  NAND3X1 g9741__1617(.A (id_insn_7), .B (id_insn_6), .C (n_581), .Y
       (n_647));
  OAI21X1 g9742__2802(.A (n_834), .B (n_464), .C (n_169), .Y (n_646));
  AND2X1 g9743__1705(.A (n_641), .B (n_851), .Y (n_645));
  INVX1 g9772(.A (n_45), .Y (n_644));
  INVX1 g9773(.A (n_641), .Y (n_642));
  INVX1 g9774(.A (n_638), .Y (n_639));
  MUX2X1 g9775__5122(.A (n_359), .B (n_482), .S (id_insn_30), .Y
       (n_636));
  OAI21X1 g9776__8246(.A (id_insn_24), .B (n_208), .C (n_166), .Y
       (n_635));
  AOI22X1 g9777__7098(.A (n_512), .B (n_528), .C (alu_op_0), .D
       (n_211), .Y (n_634));
  AOI22X1 g9778__6131(.A (n_511), .B (id_insn_3), .C (alu_op_3), .D
       (n_211), .Y (n_633));
  AOI22X1 g9779__1881(.A (n_511), .B (id_insn_1), .C (alu_op_1), .D
       (n_211), .Y (n_632));
  AOI22X1 g9780__5115(.A (n_214), .B (id_insn_24), .C (sig_trap), .D
       (n_211), .Y (n_631));
  OAI21X1 g9781__7482(.A (n_478), .B (n_350), .C (n_167), .Y (n_630));
  AOI21X1 g9782__4733(.A (n_210), .B (n_513), .C (n_357), .Y (n_629));
  AOI21X1 g9783__6161(.A (n_366), .B (n_195), .C (if_insn_29), .Y
       (n_628));
  NAND2X1 g9784__9315(.A (n_354), .B (n_182), .Y (n_627));
  NAND2X1 g9785__9945(.A (n_354), .B (n_183), .Y (n_626));
  NAND2X1 g9786__2883(.A (n_354), .B (n_168), .Y (n_625));
  NAND3X1 g9787__2346(.A (n_354), .B (n_198), .C (n_514), .Y (n_624));
  NAND3X1 g9788__1666(.A (n_217), .B (n_237), .C (n_513), .Y (n_643));
  NOR3X1 g9789__7410(.A (n_358), .B (n_408), .C (n_488), .Y (n_641));
  OAI21X1 g9790__6417(.A (n_513), .B (n_856), .C (n_210), .Y (n_640));
  NOR3X1 g9792__5477(.A (if_insn_28), .B (if_insn_29), .C (n_486), .Y
       (n_638));
  NOR3X1 g9800__2398(.A (id_freeze), .B (n_238), .C (n_513), .Y
       (n_637));
  NAND2X1 g9803__5107(.A (n_239), .B (n_176), .Y (n_623));
  NAND2X1 g9804__6260(.A (n_239), .B (n_175), .Y (n_622));
  NAND2X1 g9805__4319(.A (n_239), .B (n_172), .Y (n_621));
  OR2X1 g9806__8428(.A (n_515), .B (n_209), .Y (n_620));
  NAND2X1 g9807__5526(.A (id_insn_2), .B (n_511), .Y (n_619));
  NAND2X1 g9808__6783(.A (n_408), .B (n_512), .Y (n_618));
  NAND2X1 g9809__3680(.A (n_239), .B (n_177), .Y (n_617));
  NOR2X1 g9810__1617(.A (rst), .B (n_479), .Y (n_616));
  NOR2X1 g9811__2802(.A (rst), .B (n_485), .Y (n_615));
  OAI21X1 g9812__1705(.A (n_229), .B (n_349), .C (n_514), .Y (n_614));
  INVX1 g9841(.A (n_30), .Y (n_613));
  INVX1 g9842(.A (n_18), .Y (n_612));
  INVX1 g9843(.A (n_46), .Y (n_611));
  INVX1 g9844(.A (n_22), .Y (n_610));
  INVX1 g9845(.A (n_62), .Y (n_609));
  INVX1 g9846(.A (n_1), .Y (n_608));
  INVX1 g9847(.A (n_61), .Y (n_607));
  INVX1 g9848(.A (n_60), .Y (n_606));
  INVX1 g9849(.A (n_3), .Y (n_605));
  INVX1 g9850(.A (n_20), .Y (n_604));
  INVX1 g9851(.A (n_33), .Y (n_603));
  INVX1 g9852(.A (n_31), .Y (n_602));
  INVX1 g9853(.A (n_51), .Y (n_601));
  INVX1 g9854(.A (n_52), .Y (n_600));
  INVX1 g9855(.A (n_53), .Y (n_599));
  INVX1 g9856(.A (n_55), .Y (n_598));
  INVX1 g9857(.A (n_26), .Y (n_597));
  INVX1 g9858(.A (n_39), .Y (n_596));
  INVX1 g9859(.A (n_38), .Y (n_595));
  INVX1 g9860(.A (n_58), .Y (n_594));
  INVX1 g9861(.A (n_2), .Y (n_593));
  INVX1 g9862(.A (n_7), .Y (n_592));
  INVX1 g9863(.A (n_17), .Y (n_591));
  INVX1 g9864(.A (n_36), .Y (n_590));
  INVX1 g9865(.A (n_35), .Y (n_589));
  INVX1 g9866(.A (n_13), .Y (n_588));
  INVX1 g9867(.A (n_5), .Y (n_587));
  INVX1 g9868(.A (n_15), .Y (n_586));
  INVX1 g9869(.A (n_69), .Y (n_585));
  INVX1 g9870(.A (n_68), .Y (n_584));
  INVX1 g9871(.A (n_34), .Y (n_583));
  NOR3X1 g9872__5122(.A (n_841), .B (n_842), .C (n_213), .Y (n_581));
  OAI21X1 g9873__8246(.A (if_insn_27), .B (n_356), .C (n_178), .Y
       (n_580));
  AOI22X1 g9874__7098(.A (n_465), .B (id_branch_op_1), .C
       (ex_branch_op_1), .D (n_211), .Y (n_579));
  AOI22X1 g9875__6131(.A (n_465), .B (id_branch_op_2), .C
       (ex_branch_op_2), .D (n_211), .Y (n_578));
  AOI22X1 g9876__1881(.A (n_465), .B (id_insn_0), .C (ex_insn_0), .D
       (n_211), .Y (n_577));
  AOI22X1 g9877__5115(.A (n_465), .B (id_insn_6), .C (ex_insn_6), .D
       (n_211), .Y (n_576));
  AOI22X1 g9878__7482(.A (n_465), .B (id_insn_1), .C (ex_insn_1), .D
       (n_211), .Y (n_575));
  AOI22X1 g9879__4733(.A (n_465), .B (id_insn_2), .C (ex_insn_2), .D
       (n_211), .Y (n_574));
  AOI22X1 g9880__6161(.A (n_465), .B (id_insn_3), .C (ex_insn_3), .D
       (n_211), .Y (n_573));
  AOI22X1 g9881__9315(.A (n_465), .B (id_insn_4), .C (ex_insn_4), .D
       (n_211), .Y (n_572));
  AOI22X1 g9882__9945(.A (n_465), .B (id_insn_5), .C (ex_insn_5), .D
       (n_211), .Y (n_571));
  AOI22X1 g9883__2883(.A (n_465), .B (id_insn_7), .C (ex_insn_7), .D
       (n_211), .Y (n_570));
  AOI22X1 g9884__2346(.A (n_465), .B (id_insn_10), .C (ex_insn_10), .D
       (n_211), .Y (n_569));
  AOI22X1 g9885__1666(.A (n_465), .B (id_insn_11), .C (ex_insn_11), .D
       (n_211), .Y (n_568));
  AOI22X1 g9886__7410(.A (n_465), .B (id_insn_12), .C (ex_insn_12), .D
       (n_211), .Y (n_567));
  AOI22X1 g9887__6417(.A (n_465), .B (id_insn_13), .C (ex_insn_13), .D
       (n_211), .Y (n_566));
  AOI22X1 g9888__5477(.A (n_465), .B (id_insn_14), .C (ex_insn_14), .D
       (n_211), .Y (n_565));
  AOI22X1 g9889__2398(.A (n_465), .B (id_insn_8), .C (ex_insn_8), .D
       (n_211), .Y (n_564));
  AOI22X1 g9890__5107(.A (n_465), .B (id_insn_15), .C (ex_insn_15), .D
       (n_211), .Y (n_563));
  AOI22X1 g9891__6260(.A (n_465), .B (id_insn_9), .C (ex_insn_9), .D
       (n_211), .Y (n_562));
  AOI22X1 g9892__4319(.A (n_465), .B (id_insn_16), .C (ex_insn_16), .D
       (n_211), .Y (n_561));
  AOI22X1 g9893__8428(.A (n_465), .B (id_insn_17), .C (ex_insn_17), .D
       (n_211), .Y (n_560));
  AOI22X1 g9894__5526(.A (n_465), .B (id_insn_18), .C (ex_insn_18), .D
       (n_211), .Y (n_559));
  AOI22X1 g9895__6783(.A (n_465), .B (id_insn_19), .C (ex_insn_19), .D
       (n_211), .Y (n_558));
  AOI22X1 g9896__3680(.A (n_465), .B (id_insn_20), .C (ex_insn_20), .D
       (n_211), .Y (n_557));
  AOI22X1 g9897__1617(.A (n_465), .B (id_insn_25), .C (ex_insn_25), .D
       (n_211), .Y (n_556));
  AOI22X1 g9898__2802(.A (n_465), .B (id_insn_26), .C (ex_insn_26), .D
       (n_211), .Y (n_555));
  AOI22X1 g9899__1705(.A (n_465), .B (id_insn_27), .C (ex_insn_27), .D
       (n_211), .Y (n_554));
  AOI22X1 g9900__5122(.A (n_465), .B (id_insn_28), .C (ex_insn_28), .D
       (n_211), .Y (n_553));
  AOI22X1 g9901__8246(.A (n_465), .B (id_insn_29), .C (ex_insn_29), .D
       (n_211), .Y (n_552));
  AOI22X1 g9902__7098(.A (n_465), .B (id_insn_30), .C (ex_insn_30), .D
       (n_211), .Y (n_551));
  AOI22X1 g9903__6131(.A (n_465), .B (id_insn_31), .C (ex_insn_31), .D
       (n_211), .Y (n_550));
  AOI22X1 g9904__1881(.A (n_465), .B (id_insn_21), .C (ex_insn_21), .D
       (n_211), .Y (n_549));
  AOI22X1 g9905__5115(.A (n_465), .B (id_insn_23), .C (ex_insn_23), .D
       (n_211), .Y (n_548));
  AOI22X1 g9906__7482(.A (n_465), .B (id_insn_24), .C (ex_insn_24), .D
       (n_211), .Y (n_547));
  AOI21X1 g9907__4733(.A (id_insn_30), .B (n_407), .C (n_475), .Y
       (n_546));
  AOI22X1 g9908__6161(.A (n_465), .B (id_branch_op_0), .C
       (ex_branch_op_0), .D (n_211), .Y (n_545));
  OR2X1 g9909__9315(.A (n_487), .B (n_256), .Y (n_582));
  INVX1 g9977(.A (n_14), .Y (n_544));
  INVX1 g9978(.A (n_65), .Y (n_543));
  INVX1 g9979(.A (n_64), .Y (n_542));
  INVX1 g9980(.A (n_28), .Y (n_541));
  INVX1 g9981(.A (n_47), .Y (n_540));
  INVX1 g9982(.A (n_54), .Y (n_539));
  INVX1 g9983(.A (n_59), .Y (n_538));
  INVX1 g9984(.A (n_11), .Y (n_537));
  INVX1 g9985(.A (n_48), .Y (n_536));
  INVX1 g9986(.A (n_56), .Y (n_535));
  INVX1 g9987(.A (n_6), .Y (n_534));
  INVX1 g9988(.A (n_29), .Y (n_533));
  INVX1 g9989(.A (n_37), .Y (n_532));
  INVX1 g9990(.A (n_21), .Y (n_531));
  INVX1 g9991(.A (n_49), .Y (n_530));
  INVX1 g9992(.A (n_9), .Y (n_529));
  INVX1 g9993(.A (n_24), .Y (n_528));
  INVX1 g9994(.A (n_0), .Y (n_527));
  INVX1 g9995(.A (n_50), .Y (n_526));
  INVX1 g9996(.A (n_66), .Y (n_525));
  INVX1 g9997(.A (n_32), .Y (n_524));
  INVX1 g9998(.A (n_10), .Y (n_523));
  INVX1 g9999(.A (n_42), .Y (n_522));
  INVX1 g10000(.A (n_25), .Y (n_521));
  INVX1 g10001(.A (n_8), .Y (n_520));
  INVX1 g10002(.A (n_19), .Y (n_519));
  INVX1 g10003(.A (n_41), .Y (n_518));
  INVX1 g10004(.A (n_4), .Y (n_517));
  INVX1 g10007(.A (n_511), .Y (n_213));
  NAND3X1 g10008__9945(.A (if_insn_31), .B (n_257), .C (n_260), .Y
       (n_510));
  AOI22X1 g10009__2883(.A (n_351), .B (if_insn_31), .C (id_insn_31), .D
       (n_353), .Y (n_509));
  AOI22X1 g10010__2346(.A (n_351), .B (if_insn_30), .C (id_insn_30), .D
       (n_353), .Y (n_508));
  AOI22X1 g10011__1666(.A (n_351), .B (if_insn_28), .C (id_insn_28), .D
       (n_353), .Y (n_507));
  AOI22X1 g10012__7410(.A (n_351), .B (if_insn_27), .C (id_insn_27), .D
       (n_353), .Y (n_506));
  AOI22X1 g10013__6417(.A (n_351), .B (if_insn_26), .C (id_insn_26), .D
       (n_353), .Y (n_505));
  AOI22X1 g10014__5477(.A (n_351), .B (if_insn_25), .C (id_insn_25), .D
       (n_353), .Y (n_504));
  AOI22X1 g10015__2398(.A (n_351), .B (if_insn_24), .C (id_insn_24), .D
       (n_353), .Y (n_503));
  AOI22X1 g10016__5107(.A (n_351), .B (if_insn_23), .C (id_insn_23), .D
       (n_353), .Y (n_502));
  AOI22X1 g10017__6260(.A (n_351), .B (if_insn_22), .C (id_insn_22), .D
       (n_353), .Y (n_501));
  AOI22X1 g10018__4319(.A (n_351), .B (if_insn_21), .C (id_insn_21), .D
       (n_353), .Y (n_500));
  AOI22X1 g10019__8428(.A (n_351), .B (if_insn_20), .C (id_insn_20), .D
       (n_353), .Y (n_499));
  AOI22X1 g10020__5526(.A (n_351), .B (if_insn_19), .C (id_insn_19), .D
       (n_353), .Y (n_498));
  AOI22X1 g10021__6783(.A (n_351), .B (if_insn_18), .C (id_insn_18), .D
       (n_353), .Y (n_497));
  AOI22X1 g10022__3680(.A (n_351), .B (if_insn_17), .C (id_insn_17), .D
       (n_353), .Y (n_496));
  AOI22X1 g10023__1617(.A (n_351), .B (if_insn_16), .C (id_insn_16), .D
       (n_353), .Y (n_495));
  AOI22X1 g10024__2802(.A (n_351), .B (if_insn_15), .C (id_insn_15), .D
       (n_353), .Y (n_494));
  AOI22X1 g10025__1705(.A (n_351), .B (if_insn_14), .C (id_insn_14), .D
       (n_353), .Y (n_493));
  AOI22X1 g10026__5122(.A (n_351), .B (if_insn_13), .C (id_insn_13), .D
       (n_353), .Y (n_492));
  AOI22X1 g10027__8246(.A (n_351), .B (if_insn_12), .C (id_insn_12), .D
       (n_353), .Y (n_491));
  AOI22X1 g10028__7098(.A (n_351), .B (if_insn_11), .C (id_insn_11), .D
       (n_353), .Y (n_490));
  AOI21X1 g10029__6131(.A (id_insn_26), .B (n_242), .C (n_212), .Y
       (n_489));
  OAI21X1 g10030__1881(.A (n_862), .B (n_860), .C (n_206), .Y (n_488));
  OR2X1 g10031__5115(.A (n_466), .B (n_356), .Y (n_487));
  OR2X1 g10032__7482(.A (n_368), .B (if_insn_31), .Y (n_486));
  MUX2X1 g10033__4733(.A (n_200), .B (spr_write), .S (n_254), .Y
       (n_485));
  NAND3X1 g10034__6161(.A (if_insn_26), .B (if_insn_27), .C (n_355), .Y
       (n_484));
  AOI22X1 g10035__9315(.A (n_351), .B (if_insn_10), .C (id_insn_10), .D
       (n_353), .Y (n_483));
  MUX2X1 g10036__9945(.A (n_346), .B (n_849), .S (id_insn_29), .Y
       (n_482));
  OAI21X1 g10037__2883(.A (n_235), .B (n_352), .C (n_466), .Y (n_481));
  AOI21X1 g10038__2346(.A (n_218), .B (n_246), .C (n_188), .Y (n_480));
  MUX2X1 g10039__1666(.A (n_357), .B (spr_read), .S (n_254), .Y
       (n_479));
  OR2X1 g10040__7410(.A (n_417), .B (if_insn_29), .Y (n_478));
  AOI22X1 g10041__6417(.A (n_351), .B (if_insn_9), .C (id_insn_9), .D
       (n_353), .Y (n_477));
  AOI22X1 g10042__5477(.A (n_351), .B (if_insn_8), .C (id_insn_8), .D
       (n_353), .Y (n_476));
  MUX2X1 g10043__2398(.A (n_248), .B (n_194), .S (id_insn_26), .Y
       (n_475));
  AOI22X1 g10044__5107(.A (n_351), .B (if_insn_0), .C (id_insn_0), .D
       (n_353), .Y (n_474));
  AOI22X1 g10045__6260(.A (n_351), .B (if_insn_1), .C (id_insn_1), .D
       (n_353), .Y (n_473));
  AOI22X1 g10046__4319(.A (n_351), .B (if_insn_2), .C (id_insn_2), .D
       (n_353), .Y (n_472));
  AOI22X1 g10047__8428(.A (n_351), .B (if_insn_3), .C (id_insn_3), .D
       (n_353), .Y (n_471));
  AOI22X1 g10048__5526(.A (n_351), .B (if_insn_4), .C (id_insn_4), .D
       (n_353), .Y (n_470));
  AOI22X1 g10049__6783(.A (n_351), .B (if_insn_5), .C (id_insn_5), .D
       (n_353), .Y (n_469));
  AOI22X1 g10050__3680(.A (n_351), .B (if_insn_6), .C (id_insn_6), .D
       (n_353), .Y (n_468));
  AOI22X1 g10051__1617(.A (n_351), .B (if_insn_7), .C (id_insn_7), .D
       (n_353), .Y (n_467));
  NAND3X1 g10054__2802(.A (n_223), .B (n_334), .C (n_465), .Y (n_516));
  OAI21X1 g10055__1705(.A (n_862), .B (n_861), .C (n_180), .Y (n_515));
  OR2X1 g10056__5122(.A (n_464), .B (n_225), .Y (n_514));
  AND2X1 g10072__8246(.A (n_372), .B (n_836), .Y (n_513));
  AND2X1 g10073__7098(.A (n_851), .B (n_465), .Y (n_512));
  AND2X1 g10074__6131(.A (n_226), .B (n_465), .Y (n_511));
  INVX1 g10075(.A (n_465), .Y (n_464));
  NOR2X1 g10076__1881(.A (rst), .B (n_326), .Y (n_463));
  NAND2X1 g10077__5115(.A (n_216), .B (n_347), .Y (n_462));
  NAND2X1 g10078__7482(.A (n_216), .B (n_343), .Y (n_461));
  NAND2X1 g10079__4733(.A (n_216), .B (n_310), .Y (n_460));
  NAND2X1 g10080__6161(.A (id_branch_op_0), .B (n_353), .Y (n_459));
  NAND2X1 g10081__9315(.A (ex_insn_22), .B (n_211), .Y (n_458));
  NAND2X1 g10082__9945(.A (sig_syscall), .B (n_211), .Y (n_457));
  NOR2X1 g10083__2883(.A (rst), .B (n_331), .Y (n_456));
  NOR2X1 g10084__2346(.A (rst), .B (n_330), .Y (n_455));
  NOR2X1 g10085__1666(.A (rst), .B (n_329), .Y (n_454));
  NOR2X1 g10086__7410(.A (rst), .B (n_325), .Y (n_453));
  NOR2X1 g10087__6417(.A (rst), .B (n_333), .Y (n_452));
  NOR2X1 g10088__5477(.A (rst), .B (n_344), .Y (n_451));
  NOR2X1 g10089__2398(.A (rst), .B (n_311), .Y (n_450));
  NOR2X1 g10090__5107(.A (rst), .B (n_327), .Y (n_449));
  NOR2X1 g10091__6260(.A (rst), .B (n_348), .Y (n_448));
  NOR2X1 g10092__4319(.A (rst), .B (n_328), .Y (n_447));
  NOR2X1 g10093__8428(.A (rst), .B (n_323), .Y (n_446));
  NOR2X1 g10094__5526(.A (rst), .B (n_317), .Y (n_445));
  NOR2X1 g10095__6783(.A (rst), .B (n_301), .Y (n_444));
  NOR2X1 g10096__3680(.A (rst), .B (n_321), .Y (n_443));
  NOR2X1 g10097__1617(.A (rst), .B (n_304), .Y (n_442));
  NOR2X1 g10098__2802(.A (rst), .B (n_314), .Y (n_441));
  NOR2X1 g10099__1705(.A (rst), .B (n_335), .Y (n_440));
  NOR2X1 g10100__5122(.A (rst), .B (n_324), .Y (n_439));
  NAND2X1 g10101__8246(.A (n_216), .B (n_315), .Y (n_438));
  NOR2X1 g10102__7098(.A (rst), .B (n_299), .Y (n_437));
  NOR2X1 g10103__6131(.A (rst), .B (n_298), .Y (n_436));
  NOR2X1 g10104__1881(.A (rst), .B (n_297), .Y (n_435));
  NOR2X1 g10105__5115(.A (rst), .B (n_296), .Y (n_434));
  NOR2X1 g10106__7482(.A (rst), .B (n_295), .Y (n_433));
  NOR2X1 g10107__4733(.A (rst), .B (n_294), .Y (n_432));
  NAND2X1 g10108__6161(.A (id_insn_30), .B (n_337), .Y (n_431));
  NOR2X1 g10109__9315(.A (rst), .B (n_293), .Y (n_430));
  NOR2X1 g10110__9945(.A (rst), .B (n_292), .Y (n_429));
  NOR2X1 g10111__2883(.A (rst), .B (n_291), .Y (n_428));
  NOR2X1 g10112__2346(.A (rst), .B (n_290), .Y (n_427));
  NOR2X1 g10113__1666(.A (rst), .B (n_289), .Y (n_426));
  NOR2X1 g10114__7410(.A (rst), .B (n_318), .Y (n_425));
  NOR2X1 g10115__6417(.A (rst), .B (n_316), .Y (n_424));
  NOR2X1 g10116__5477(.A (rst), .B (n_320), .Y (n_423));
  NOR2X1 g10117__2398(.A (rst), .B (n_312), .Y (n_422));
  NOR2X1 g10118__5107(.A (rst), .B (n_286), .Y (n_421));
  NOR2X1 g10119__6260(.A (rst), .B (n_285), .Y (n_420));
  NOR2X1 g10120__4319(.A (rst), .B (n_284), .Y (n_419));
  NOR2X1 g10121__8428(.A (rst), .B (n_283), .Y (n_418));
  OR2X1 g10122__5526(.A (n_356), .B (n_258), .Y (n_417));
  NOR2X1 g10123__6783(.A (rst), .B (n_282), .Y (n_416));
  OR2X1 g10124__3680(.A (n_350), .B (n_221), .Y (n_466));
  AND2X1 g10125__1617(.A (n_351), .B (n_215), .Y (n_465));
  INVX1 g10126(.A (n_44), .Y (n_415));
  INVX1 g10127(.A (n_63), .Y (n_414));
  INVX1 g10128(.A (n_67), .Y (n_413));
  INVX1 g10129(.A (n_43), .Y (n_412));
  INVX1 g10130(.A (n_27), .Y (n_411));
  INVX1 g10131(.A (n_57), .Y (n_410));
  MUX2X1 g10133__2802(.A (n_247), .B (n_259), .S (id_insn_26), .Y
       (n_407));
  NOR2X1 g10134__1705(.A (rst), .B (n_279), .Y (n_406));
  NOR2X1 g10135__5122(.A (rst), .B (n_281), .Y (n_405));
  NOR2X1 g10136__8246(.A (rst), .B (n_280), .Y (n_404));
  NOR2X1 g10137__7098(.A (rst), .B (n_277), .Y (n_403));
  NOR2X1 g10138__6131(.A (rst), .B (n_276), .Y (n_402));
  NOR2X1 g10139__1881(.A (rst), .B (n_278), .Y (n_401));
  NOR2X1 g10140__5115(.A (rst), .B (n_275), .Y (n_400));
  NOR2X1 g10141__7482(.A (rst), .B (n_332), .Y (n_399));
  NOR2X1 g10142__4733(.A (rst), .B (n_287), .Y (n_398));
  NOR2X1 g10143__6161(.A (rst), .B (n_274), .Y (n_397));
  NOR2X1 g10144__9315(.A (rst), .B (n_300), .Y (n_396));
  NOR2X1 g10145__9945(.A (rst), .B (n_273), .Y (n_395));
  NOR2X1 g10146__2883(.A (rst), .B (n_271), .Y (n_394));
  NOR2X1 g10147__2346(.A (rst), .B (n_307), .Y (n_393));
  NOR2X1 g10148__1666(.A (rst), .B (n_272), .Y (n_392));
  NOR2X1 g10149__7410(.A (rst), .B (n_288), .Y (n_391));
  NOR2X1 g10150__6417(.A (rst), .B (n_319), .Y (n_390));
  NOR2X1 g10151__5477(.A (rst), .B (n_270), .Y (n_389));
  NOR2X1 g10152__2398(.A (rst), .B (n_269), .Y (n_388));
  NOR2X1 g10153__5107(.A (rst), .B (n_268), .Y (n_387));
  NOR2X1 g10154__6260(.A (rst), .B (n_313), .Y (n_386));
  NOR2X1 g10155__4319(.A (rst), .B (n_309), .Y (n_385));
  NOR2X1 g10156__8428(.A (rst), .B (n_306), .Y (n_384));
  NOR2X1 g10157__5526(.A (rst), .B (n_266), .Y (n_383));
  NOR2X1 g10158__6783(.A (rst), .B (n_322), .Y (n_382));
  NOR2X1 g10159__3680(.A (rst), .B (n_303), .Y (n_381));
  NOR2X1 g10160__1617(.A (rst), .B (n_261), .Y (n_380));
  NOR2X1 g10161__2802(.A (rst), .B (n_265), .Y (n_379));
  NOR2X1 g10162__1705(.A (rst), .B (n_267), .Y (n_378));
  NOR2X1 g10163__5122(.A (rst), .B (n_264), .Y (n_377));
  NOR2X1 g10164__8246(.A (rst), .B (n_263), .Y (n_376));
  NOR2X1 g10165__7098(.A (rst), .B (n_308), .Y (n_375));
  NOR2X1 g10166__6131(.A (rst), .B (n_262), .Y (n_374));
  NOR2X1 g10167__1881(.A (rst), .B (n_302), .Y (n_373));
  OAI21X1 g10168__5115(.A (n_859), .B (n_848), .C (n_336), .Y (n_372));
  AOI21X1 g10169__7482(.A (n_232), .B (n_247), .C (n_845), .Y (n_371));
  NOR2X1 g10170__4733(.A (rst), .B (n_305), .Y (n_370));
  AOI22X1 g10171__6161(.A (n_243), .B (n_257), .C (if_insn_30), .D
       (if_insn_31), .Y (n_369));
  OAI21X1 g10172__9315(.A (n_258), .B (n_257), .C (if_insn_30), .Y
       (n_368));
  OAI21X1 g10173__9945(.A (if_insn_29), .B (n_245), .C (if_insn_28), .Y
       (n_367));
  OR2X1 g10174__2883(.A (n_190), .B (n_218), .Y (n_366));
  AOI22X1 g10175__2346(.A (id_simm_11), .B (n_237), .C (ex_simm_11), .D
       (n_253), .Y (n_365));
  AOI22X1 g10176__1666(.A (id_simm_12), .B (n_237), .C (ex_simm_12), .D
       (n_253), .Y (n_364));
  AOI22X1 g10177__7410(.A (id_simm_13), .B (n_237), .C (ex_simm_13), .D
       (n_253), .Y (n_363));
  AOI22X1 g10178__6417(.A (id_simm_14), .B (n_237), .C (ex_simm_14), .D
       (n_253), .Y (n_362));
  AOI22X1 g10179__5477(.A (id_simm_15), .B (n_237), .C (ex_simm_15), .D
       (n_253), .Y (n_361));
  AOI22X1 g10180__2398(.A (id_simm_31), .B (n_237), .C (ex_simm_31), .D
       (n_253), .Y (n_360));
  MUX2X1 g10181__5107(.A (n_850), .B (n_247), .S (n_235), .Y (n_359));
  AOI21X1 g10182__6260(.A (n_228), .B (n_242), .C (n_209), .Y (n_409));
  OAI21X1 g10183__4319(.A (n_848), .B (n_241), .C (n_843), .Y (n_408));
  INVX1 g10184(.A (n_356), .Y (n_355));
  INVX1 g10185(.A (n_353), .Y (n_352));
  INVX1 g10186(.A (n_351), .Y (n_350));
  INVX1 g10188(.A (n_211), .Y (n_349));
  MUX2X1 g10191__8428(.A (wb_insn_14), .B (ex_insn_14), .S (wb_freeze),
       .Y (n_348));
  MUX2X1 g10192__5526(.A (wb_insn_22), .B (ex_insn_22), .S (wb_freeze),
       .Y (n_347));
  OR2X1 g10193__6783(.A (n_248), .B (id_insn_26), .Y (n_346));
  NAND2X1 g10194__3680(.A (n_232), .B (n_259), .Y (n_345));
  MUX2X1 g10195__1617(.A (wb_insn_8), .B (ex_insn_8), .S (wb_freeze),
       .Y (n_344));
  MUX2X1 g10196__2802(.A (wb_insn_28), .B (ex_insn_28), .S (wb_freeze),
       .Y (n_343));
  NAND2X1 g10197__1705(.A (n_245), .B (n_243), .Y (n_342));
  NAND2X1 g10198__5122(.A (rfwb_op_0), .B (n_255), .Y (n_341));
  NAND2X1 g10199__8246(.A (rfwb_op_1), .B (n_255), .Y (n_340));
  NAND2X1 g10200__7098(.A (rfwb_op_2), .B (n_255), .Y (n_339));
  NOR2X1 g10201__6131(.A (n_240), .B (n_838), .Y (n_338));
  NOR3X1 g10202__1881(.A (id_insn_28), .B (n_846), .C (n_848), .Y
       (n_337));
  OR2X1 g10203__5115(.A (n_251), .B (n_232), .Y (n_336));
  MUX2X1 g10204__7482(.A (wb_rfaddrw2), .B (rf_addrw_2), .S
       (wb_freeze), .Y (n_335));
  NOR3X1 g10205__4733(.A (id_insn_23), .B (n_863), .C (n_839), .Y
       (n_334));
  MUX2X1 g10206__6161(.A (wb_insn_7), .B (ex_insn_7), .S (wb_freeze),
       .Y (n_333));
  MUX2X1 g10207__9315(.A (wb_insn_1), .B (ex_insn_1), .S (wb_freeze),
       .Y (n_332));
  MUX2X1 g10208__9945(.A (wb_insn_2), .B (ex_insn_2), .S (wb_freeze),
       .Y (n_331));
  MUX2X1 g10209__2883(.A (wb_insn_3), .B (ex_insn_3), .S (wb_freeze),
       .Y (n_330));
  MUX2X1 g10210__2346(.A (wb_insn_5), .B (ex_insn_5), .S (wb_freeze),
       .Y (n_329));
  MUX2X1 g10211__1666(.A (wb_insn_9), .B (ex_insn_9), .S (wb_freeze),
       .Y (n_328));
  MUX2X1 g10212__7410(.A (wb_insn_11), .B (ex_insn_11), .S (wb_freeze),
       .Y (n_327));
  MUX2X1 g10213__6417(.A (wb_insn_13), .B (ex_insn_13), .S (wb_freeze),
       .Y (n_326));
  MUX2X1 g10214__5477(.A (wb_insn_6), .B (ex_insn_6), .S (wb_freeze),
       .Y (n_325));
  MUX2X1 g10215__2398(.A (wb_insn_17), .B (ex_insn_17), .S (wb_freeze),
       .Y (n_324));
  MUX2X1 g10216__5107(.A (wb_insn_20), .B (ex_insn_20), .S (wb_freeze),
       .Y (n_323));
  MUX2X1 g10217__6260(.A (wb_insn_21), .B (ex_insn_21), .S (wb_freeze),
       .Y (n_322));
  MUX2X1 g10218__4319(.A (wb_insn_19), .B (ex_insn_19), .S (wb_freeze),
       .Y (n_321));
  MUX2X1 g10219__8428(.A (wb_insn_25), .B (ex_insn_25), .S (wb_freeze),
       .Y (n_320));
  MUX2X1 g10220__5526(.A (wb_insn_27), .B (ex_insn_27), .S (wb_freeze),
       .Y (n_319));
  MUX2X1 g10221__6783(.A (wb_insn_29), .B (ex_insn_29), .S (wb_freeze),
       .Y (n_318));
  MUX2X1 g10222__3680(.A (wb_insn_18), .B (ex_insn_18), .S (wb_freeze),
       .Y (n_317));
  MUX2X1 g10223__1617(.A (wb_rfaddrw1), .B (rf_addrw_1), .S
       (wb_freeze), .Y (n_316));
  MUX2X1 g10224__2802(.A (wb_insn_16), .B (ex_insn_16), .S (wb_freeze),
       .Y (n_315));
  MUX2X1 g10225__1705(.A (wb_insn_24), .B (ex_insn_24), .S (wb_freeze),
       .Y (n_314));
  MUX2X1 g10226__5122(.A (wb_insn_31), .B (ex_insn_31), .S (wb_freeze),
       .Y (n_313));
  MUX2X1 g10227__8246(.A (wb_insn_15), .B (ex_insn_15), .S (wb_freeze),
       .Y (n_312));
  MUX2X1 g10228__7098(.A (wb_insn_10), .B (ex_insn_10), .S (wb_freeze),
       .Y (n_311));
  MUX2X1 g10229__6131(.A (wb_insn_26), .B (ex_insn_26), .S (wb_freeze),
       .Y (n_310));
  MUX2X1 g10230__1881(.A (wb_rfaddrw4), .B (rf_addrw_4), .S
       (wb_freeze), .Y (n_309));
  MUX2X1 g10231__5115(.A (wb_insn_12), .B (ex_insn_12), .S (wb_freeze),
       .Y (n_308));
  AND2X1 g10232__7482(.A (n_242), .B (id_insn_27), .Y (n_358));
  NOR3X1 g10233__4733(.A (n_240), .B (n_848), .C (n_861), .Y (n_357));
  OR2X1 g10234__6161(.A (n_244), .B (if_insn_28), .Y (n_356));
  AND2X1 g10235__9315(.A (n_239), .B (n_252), .Y (n_354));
  AND2X1 g10236__9945(.A (n_239), .B (id_freeze), .Y (n_353));
  AND2X1 g10237__2883(.A (n_239), .B (n_217), .Y (n_351));
  AND2X1 g10238__2346(.A (n_239), .B (ex_freeze), .Y (n_211));
  MUX2X1 g10239__1666(.A (wb_insn_4), .B (ex_insn_4), .S (wb_freeze),
       .Y (n_307));
  MUX2X1 g10240__7410(.A (wb_insn_23), .B (ex_insn_23), .S (wb_freeze),
       .Y (n_306));
  MUX2X1 g10241__6417(.A (wb_rfaddrw0), .B (rf_addrw_0), .S
       (wb_freeze), .Y (n_305));
  MUX2X1 g10242__5477(.A (wb_insn_30), .B (ex_insn_30), .S (wb_freeze),
       .Y (n_304));
  MUX2X1 g10243__2398(.A (wb_rfaddrw3), .B (rf_addrw_3), .S
       (wb_freeze), .Y (n_303));
  MUX2X1 g10244__5107(.A (wb_insn_0), .B (ex_insn_0), .S (wb_freeze),
       .Y (n_302));
  MUX2X1 g10245__6260(.A (id_branch_addrtarget_17), .B
       (ex_branch_addrtarget_17), .S (n_215), .Y (n_301));
  MUX2X1 g10246__4319(.A (id_branch_addrtarget_16), .B
       (ex_branch_addrtarget_16), .S (n_215), .Y (n_300));
  MUX2X1 g10247__8428(.A (id_insn_0), .B (ex_simm_0), .S (n_215), .Y
       (n_299));
  MUX2X1 g10248__5526(.A (id_insn_1), .B (ex_simm_1), .S (n_215), .Y
       (n_298));
  MUX2X1 g10249__6783(.A (id_insn_2), .B (ex_simm_2), .S (n_215), .Y
       (n_297));
  MUX2X1 g10250__3680(.A (id_insn_3), .B (ex_simm_3), .S (n_215), .Y
       (n_296));
  MUX2X1 g10251__1617(.A (id_insn_4), .B (ex_simm_4), .S (n_215), .Y
       (n_295));
  MUX2X1 g10252__2802(.A (id_insn_5), .B (ex_simm_5), .S (n_215), .Y
       (n_294));
  MUX2X1 g10253__1705(.A (id_insn_6), .B (ex_simm_6), .S (n_215), .Y
       (n_293));
  MUX2X1 g10254__5122(.A (id_insn_7), .B (ex_simm_7), .S (n_215), .Y
       (n_292));
  MUX2X1 g10255__8246(.A (id_insn_8), .B (ex_simm_8), .S (n_215), .Y
       (n_291));
  MUX2X1 g10256__7098(.A (id_insn_9), .B (ex_simm_9), .S (n_215), .Y
       (n_290));
  MUX2X1 g10257__6131(.A (id_insn_10), .B (ex_simm_10), .S (n_215), .Y
       (n_289));
  MUX2X1 g10258__1881(.A (id_branch_addrtarget_22), .B
       (ex_branch_addrtarget_22), .S (n_215), .Y (n_288));
  MUX2X1 g10259__5115(.A (id_branch_addrtarget_15), .B
       (ex_branch_addrtarget_15), .S (n_215), .Y (n_287));
  MUX2X1 g10260__7482(.A (id_branch_addrtarget_2), .B
       (ex_branch_addrtarget_2), .S (n_215), .Y (n_286));
  MUX2X1 g10261__4733(.A (id_branch_addrtarget_3), .B
       (ex_branch_addrtarget_3), .S (n_215), .Y (n_285));
  MUX2X1 g10262__6161(.A (id_branch_addrtarget_4), .B
       (ex_branch_addrtarget_4), .S (n_215), .Y (n_284));
  MUX2X1 g10263__9315(.A (id_branch_addrtarget_5), .B
       (ex_branch_addrtarget_5), .S (n_215), .Y (n_283));
  MUX2X1 g10264__9945(.A (id_branch_addrtarget_6), .B
       (ex_branch_addrtarget_6), .S (n_215), .Y (n_282));
  MUX2X1 g10265__2883(.A (id_branch_addrtarget_7), .B
       (ex_branch_addrtarget_7), .S (n_215), .Y (n_281));
  MUX2X1 g10266__2346(.A (id_branch_addrtarget_8), .B
       (ex_branch_addrtarget_8), .S (n_215), .Y (n_280));
  MUX2X1 g10267__1666(.A (id_branch_addrtarget_9), .B
       (ex_branch_addrtarget_9), .S (n_215), .Y (n_279));
  MUX2X1 g10268__7410(.A (id_branch_addrtarget_12), .B
       (ex_branch_addrtarget_12), .S (n_215), .Y (n_278));
  MUX2X1 g10269__6417(.A (id_branch_addrtarget_10), .B
       (ex_branch_addrtarget_10), .S (n_215), .Y (n_277));
  MUX2X1 g10270__5477(.A (id_branch_addrtarget_11), .B
       (ex_branch_addrtarget_11), .S (n_215), .Y (n_276));
  MUX2X1 g10271__2398(.A (id_branch_addrtarget_13), .B
       (ex_branch_addrtarget_13), .S (n_215), .Y (n_275));
  MUX2X1 g10272__5107(.A (id_branch_addrtarget_14), .B
       (ex_branch_addrtarget_14), .S (n_215), .Y (n_274));
  MUX2X1 g10273__6260(.A (id_branch_addrtarget_18), .B
       (ex_branch_addrtarget_18), .S (n_215), .Y (n_273));
  MUX2X1 g10274__4319(.A (id_branch_addrtarget_20), .B
       (ex_branch_addrtarget_20), .S (n_215), .Y (n_272));
  MUX2X1 g10275__8428(.A (id_branch_addrtarget_21), .B
       (ex_branch_addrtarget_21), .S (n_215), .Y (n_271));
  MUX2X1 g10276__5526(.A (id_branch_addrtarget_23), .B
       (ex_branch_addrtarget_23), .S (n_215), .Y (n_270));
  MUX2X1 g10277__6783(.A (id_branch_addrtarget_24), .B
       (ex_branch_addrtarget_24), .S (n_215), .Y (n_269));
  MUX2X1 g10278__3680(.A (id_branch_addrtarget_25), .B
       (ex_branch_addrtarget_25), .S (n_215), .Y (n_268));
  MUX2X1 g10279__1617(.A (id_branch_addrtarget_26), .B
       (ex_branch_addrtarget_26), .S (n_215), .Y (n_267));
  MUX2X1 g10280__2802(.A (id_branch_addrtarget_27), .B
       (ex_branch_addrtarget_27), .S (n_215), .Y (n_266));
  MUX2X1 g10281__1705(.A (id_branch_addrtarget_28), .B
       (ex_branch_addrtarget_28), .S (n_215), .Y (n_265));
  MUX2X1 g10282__5122(.A (id_branch_addrtarget_29), .B
       (ex_branch_addrtarget_29), .S (n_215), .Y (n_264));
  MUX2X1 g10283__8246(.A (id_branch_addrtarget_30), .B
       (ex_branch_addrtarget_30), .S (n_215), .Y (n_263));
  MUX2X1 g10284__7098(.A (id_branch_addrtarget_31), .B
       (ex_branch_addrtarget_31), .S (n_215), .Y (n_262));
  MUX2X1 g10285__6131(.A (id_branch_addrtarget_19), .B
       (ex_branch_addrtarget_19), .S (n_215), .Y (n_261));
  MUX2X1 g10286__1881(.A (if_insn_28), .B (n_218), .S (if_insn_30), .Y
       (n_260));
  INVX1 g10287(.A (n_257), .Y (n_256));
  INVX1 g10288(.A (n_255), .Y (n_254));
  OR2X1 g10289__5115(.A (n_217), .B (ex_freeze), .Y (n_252));
  OR2X1 g10290__7482(.A (n_847), .B (id_insn_28), .Y (n_251));
  NAND2X1 g10291__4733(.A (id_freeze), .B (sel_imm), .Y (n_250));
  AND2X1 g10292__6161(.A (n_233), .B (id_insn_27), .Y (n_259));
  AND2X1 g10293__9315(.A (n_224), .B (if_insn_27), .Y (n_258));
  AND2X1 g10294__9945(.A (n_219), .B (if_insn_26), .Y (n_257));
  AND2X1 g10295__2883(.A (n_227), .B (ex_freeze), .Y (n_255));
  AND2X1 g10296__2346(.A (n_216), .B (ex_freeze), .Y (n_253));
  INVX1 g10297(.A (n_245), .Y (n_246));
  INVX1 g10298(.A (n_243), .Y (n_244));
  INVX1 g10299(.A (n_242), .Y (n_241));
  INVX1 g10301(.A (n_240), .Y (n_210));
  INVX1 g10302(.A (n_237), .Y (n_238));
  NOR2X1 g10303__1666(.A (n_847), .B (n_840), .Y (n_249));
  OR2X1 g10304__7410(.A (n_234), .B (n_233), .Y (n_248));
  AND2X1 g10305__6417(.A (n_233), .B (n_234), .Y (n_247));
  AND2X1 g10306__5477(.A (n_219), .B (n_224), .Y (n_245));
  AND2X1 g10307__2398(.A (n_222), .B (n_220), .Y (n_243));
  AND2X1 g10308__5107(.A (n_230), .B (n_231), .Y (n_242));
  OR2X1 g10309__6260(.A (if_flushpipe), .B (id_freeze), .Y (n_240));
  AND2X1 g10310__4319(.A (n_227), .B (n_216), .Y (n_239));
  AND2X1 g10311__8428(.A (n_216), .B (n_215), .Y (n_237));
  INVX1 g10312(.A (id_insn_0), .Y (n_236));
  INVX1 g10313(.A (id_insn_29), .Y (n_235));
  INVX1 g10314(.A (id_insn_27), .Y (n_234));
  INVX1 g10315(.A (id_insn_28), .Y (n_233));
  INVX1 g10316(.A (id_insn_30), .Y (n_232));
  INVX1 g10317(.A (n_859), .Y (n_231));
  INVX1 g10318(.A (n_846), .Y (n_230));
  INVX1 g10319(.A (comp_op_1), .Y (n_229));
  INVX1 g10320(.A (n_863), .Y (n_228));
  INVX1 g10321(.A (if_flushpipe), .Y (n_227));
  INVX1 g10322(.A (n_851), .Y (n_226));
  INVX1 g10323(.A (id_insn_22), .Y (n_225));
  INVX1 g10324(.A (if_insn_26), .Y (n_224));
  INVX1 g10325(.A (id_insn_25), .Y (n_223));
  INVX1 g10326(.A (if_insn_31), .Y (n_222));
  INVX1 g10327(.A (if_insn_29), .Y (n_221));
  INVX1 g10328(.A (if_insn_30), .Y (n_220));
  INVX1 g10329(.A (if_insn_27), .Y (n_219));
  INVX1 g10330(.A (if_insn_28), .Y (n_218));
  INVX1 g10331(.A (id_freeze), .Y (n_217));
  INVX1 g10332(.A (rst), .Y (n_216));
  INVX1 g10333(.A (ex_freeze), .Y (n_215));
  INVX1 drc_bufs10339(.A (n_208), .Y (n_214));
  INVX1 drc_bufs10347(.A (n_206), .Y (n_212));
  BUFX2 drc_bufs10349(.A (n_678), .Y (n_205));
  BUFX2 drc_bufs10350(.A (n_651), .Y (n_204));
  BUFX2 drc_bufs10351(.A (n_619), .Y (n_203));
  BUFX2 drc_bufs10352(.A (n_629), .Y (n_202));
  BUFX2 drc_bufs10353(.A (n_480), .Y (n_201));
  BUFX2 drc_bufs10354(.A (n_338), .Y (n_200));
  BUFX2 drc_bufs10355(.A (n_628), .Y (n_199));
  BUFX2 drc_bufs10356(.A (n_458), .Y (n_198));
  BUFX2 drc_bufs10357(.A (n_546), .Y (n_197));
  BUFX2 drc_bufs10358(.A (n_674), .Y (n_196));
  BUFX2 drc_bufs10359(.A (n_484), .Y (n_195));
  BUFX2 drc_bufs10360(.A (n_345), .Y (n_194));
  BUFX2 drc_bufs10361(.A (n_341), .Y (n_193));
  BUFX2 drc_bufs10362(.A (n_250), .Y (n_192));
  BUFX2 drc_bufs10363(.A (n_647), .Y (n_191));
  BUFX2 drc_bufs10364(.A (n_342), .Y (n_190));
  BUFX2 drc_bufs10365(.A (n_371), .Y (n_189));
  BUFX2 drc_bufs10366(.A (n_369), .Y (n_188));
  BUFX2 drc_bufs10367(.A (n_618), .Y (n_187));
  BUFX2 drc_bufs10368(.A (n_666), .Y (n_186));
  BUFX2 drc_bufs10369(.A (n_665), .Y (n_185));
  BUFX2 drc_bufs10370(.A (n_657), .Y (n_184));
  BUFX2 drc_bufs10371(.A (n_555), .Y (n_183));
  BUFX2 drc_bufs10372(.A (n_553), .Y (n_182));
  BUFX2 drc_bufs10373(.A (n_656), .Y (n_181));
  BUFX2 drc_bufs10374(.A (n_431), .Y (n_180));
  BUFX2 drc_bufs10375(.A (n_679), .Y (n_179));
  BUFX2 drc_bufs10376(.A (n_510), .Y (n_178));
  BUFX2 drc_bufs10377(.A (n_507), .Y (n_177));
  BUFX2 drc_bufs10378(.A (n_505), .Y (n_176));
  BUFX2 drc_bufs10379(.A (n_501), .Y (n_175));
  BUFX2 drc_bufs10380(.A (n_339), .Y (n_174));
  BUFX2 drc_bufs10381(.A (n_634), .Y (n_173));
  BUFX2 drc_bufs10382(.A (n_495), .Y (n_172));
  BUFX2 drc_bufs10383(.A (n_340), .Y (n_171));
  BUFX2 drc_bufs10384(.A (n_632), .Y (n_170));
  BUFX2 drc_bufs10385(.A (n_631), .Y (n_169));
  BUFX2 drc_bufs10386(.A (n_561), .Y (n_168));
  BUFX2 drc_bufs10387(.A (n_459), .Y (n_167));
  BUFX2 drc_bufs10388(.A (n_457), .Y (n_166));
  BUFX2 drc_bufs10389(.A (n_399), .Y (n_165));
  BUFX2 drc_bufs10390(.A (n_381), .Y (n_164));
  BUFX2 drc_bufs10391(.A (n_683), .Y (n_163));
  BUFX2 drc_bufs10392(.A (n_447), .Y (n_162));
  BUFX2 drc_bufs10393(.A (n_403), .Y (n_161));
  BUFX2 drc_bufs10394(.A (n_446), .Y (n_160));
  BUFX2 drc_bufs10395(.A (n_624), .Y (n_159));
  BUFX2 drc_bufs10396(.A (n_445), .Y (n_158));
  BUFX2 drc_bufs10397(.A (n_416), .Y (n_157));
  BUFX2 drc_bufs10398(.A (n_444), .Y (n_156));
  BUFX2 drc_bufs10399(.A (n_443), .Y (n_155));
  BUFX2 drc_bufs10400(.A (n_442), .Y (n_154));
  BUFX2 drc_bufs10401(.A (n_420), .Y (n_153));
  BUFX2 drc_bufs10402(.A (n_421), .Y (n_152));
  BUFX2 drc_bufs10403(.A (n_422), .Y (n_151));
  BUFX2 drc_bufs10404(.A (n_623), .Y (n_150));
  BUFX2 drc_bufs10405(.A (n_424), .Y (n_149));
  BUFX2 drc_bufs10406(.A (n_441), .Y (n_148));
  BUFX2 drc_bufs10407(.A (n_440), .Y (n_147));
  BUFX2 drc_bufs10408(.A (n_622), .Y (n_146));
  BUFX2 drc_bufs10409(.A (n_439), .Y (n_145));
  BUFX2 drc_bufs10410(.A (n_438), .Y (n_144));
  BUFX2 drc_bufs10411(.A (n_437), .Y (n_143));
  BUFX2 drc_bufs10412(.A (n_436), .Y (n_142));
  BUFX2 drc_bufs10413(.A (n_621), .Y (n_141));
  BUFX2 drc_bufs10414(.A (n_435), .Y (n_140));
  BUFX2 drc_bufs10415(.A (n_434), .Y (n_139));
  BUFX2 drc_bufs10416(.A (n_433), .Y (n_138));
  BUFX2 drc_bufs10417(.A (n_432), .Y (n_137));
  BUFX2 drc_bufs10418(.A (n_673), .Y (n_136));
  BUFX2 drc_bufs10419(.A (n_430), .Y (n_135));
  BUFX2 drc_bufs10420(.A (n_429), .Y (n_134));
  BUFX2 drc_bufs10421(.A (n_428), .Y (n_133));
  BUFX2 drc_bufs10422(.A (n_427), .Y (n_132));
  BUFX2 drc_bufs10423(.A (n_426), .Y (n_131));
  BUFX2 drc_bufs10424(.A (n_425), .Y (n_130));
  BUFX2 drc_bufs10425(.A (n_383), .Y (n_129));
  BUFX2 drc_bufs10426(.A (n_617), .Y (n_128));
  BUFX2 drc_bufs10427(.A (n_423), .Y (n_127));
  BUFX2 drc_bufs10428(.A (n_650), .Y (n_126));
  BUFX2 drc_bufs10429(.A (n_448), .Y (n_125));
  BUFX2 drc_bufs10430(.A (n_419), .Y (n_124));
  BUFX2 drc_bufs10431(.A (n_450), .Y (n_123));
  BUFX2 drc_bufs10432(.A (n_418), .Y (n_122));
  BUFX2 drc_bufs10433(.A (n_452), .Y (n_121));
  BUFX2 drc_bufs10434(.A (n_616), .Y (n_120));
  BUFX2 drc_bufs10435(.A (n_391), .Y (n_119));
  BUFX2 drc_bufs10436(.A (n_387), .Y (n_118));
  BUFX2 drc_bufs10437(.A (n_456), .Y (n_117));
  BUFX2 drc_bufs10438(.A (n_615), .Y (n_116));
  BUFX2 drc_bufs10439(.A (n_406), .Y (n_115));
  BUFX2 drc_bufs10440(.A (n_405), .Y (n_114));
  BUFX2 drc_bufs10441(.A (n_404), .Y (n_113));
  BUFX2 drc_bufs10442(.A (n_402), .Y (n_112));
  BUFX2 drc_bufs10443(.A (n_401), .Y (n_111));
  BUFX2 drc_bufs10444(.A (n_400), .Y (n_110));
  BUFX2 drc_bufs10445(.A (n_398), .Y (n_109));
  BUFX2 drc_bufs10446(.A (n_397), .Y (n_108));
  BUFX2 drc_bufs10447(.A (n_396), .Y (n_107));
  BUFX2 drc_bufs10448(.A (n_672), .Y (n_106));
  BUFX2 drc_bufs10449(.A (n_394), .Y (n_105));
  BUFX2 drc_bufs10450(.A (n_392), .Y (n_104));
  BUFX2 drc_bufs10451(.A (n_684), .Y (n_103));
  BUFX2 drc_bufs10452(.A (n_390), .Y (n_102));
  BUFX2 drc_bufs10453(.A (n_389), .Y (n_101));
  BUFX2 drc_bufs10454(.A (n_388), .Y (n_100));
  BUFX2 drc_bufs10455(.A (n_386), .Y (n_99));
  BUFX2 drc_bufs10456(.A (n_385), .Y (n_98));
  BUFX2 drc_bufs10457(.A (n_384), .Y (n_97));
  BUFX2 drc_bufs10458(.A (n_382), .Y (n_96));
  BUFX2 drc_bufs10459(.A (n_380), .Y (n_95));
  BUFX2 drc_bufs10460(.A (n_378), .Y (n_94));
  BUFX2 drc_bufs10461(.A (n_377), .Y (n_93));
  BUFX2 drc_bufs10462(.A (n_376), .Y (n_92));
  BUFX2 drc_bufs10463(.A (n_680), .Y (n_91));
  BUFX2 drc_bufs10464(.A (n_373), .Y (n_90));
  BUFX2 drc_bufs10465(.A (n_374), .Y (n_89));
  BUFX2 drc_bufs10466(.A (n_370), .Y (n_88));
  BUFX2 drc_bufs10467(.A (n_375), .Y (n_87));
  BUFX2 drc_bufs10468(.A (n_676), .Y (n_86));
  BUFX2 drc_bufs10469(.A (n_393), .Y (n_85));
  BUFX2 drc_bufs10470(.A (n_379), .Y (n_84));
  BUFX2 drc_bufs10471(.A (n_463), .Y (n_83));
  BUFX2 drc_bufs10472(.A (n_462), .Y (n_82));
  BUFX2 drc_bufs10473(.A (n_461), .Y (n_81));
  BUFX2 drc_bufs10474(.A (n_460), .Y (n_80));
  BUFX2 drc_bufs10475(.A (n_395), .Y (n_79));
  BUFX2 drc_bufs10476(.A (n_675), .Y (n_78));
  BUFX2 drc_bufs10477(.A (n_627), .Y (n_77));
  BUFX2 drc_bufs10478(.A (n_626), .Y (n_76));
  BUFX2 drc_bufs10479(.A (n_455), .Y (n_75));
  BUFX2 drc_bufs10480(.A (n_454), .Y (n_74));
  BUFX2 drc_bufs10481(.A (n_453), .Y (n_73));
  BUFX2 drc_bufs10482(.A (n_625), .Y (n_72));
  BUFX2 drc_bufs10483(.A (n_451), .Y (n_71));
  BUFX2 drc_bufs10484(.A (n_449), .Y (n_70));
  BUFX2 drc_bufs10485(.A (n_548), .Y (n_69));
  BUFX2 drc_bufs10486(.A (n_547), .Y (n_68));
  BUFX2 drc_bufs10487(.A (n_363), .Y (n_67));
  BUFX2 drc_bufs10488(.A (n_476), .Y (n_66));
  BUFX2 drc_bufs10489(.A (n_508), .Y (n_65));
  BUFX2 drc_bufs10490(.A (n_506), .Y (n_64));
  BUFX2 drc_bufs10491(.A (n_364), .Y (n_63));
  BUFX2 drc_bufs10492(.A (n_575), .Y (n_62));
  BUFX2 drc_bufs10493(.A (n_573), .Y (n_61));
  BUFX2 drc_bufs10494(.A (n_572), .Y (n_60));
  BUFX2 drc_bufs10495(.A (n_500), .Y (n_59));
  BUFX2 drc_bufs10496(.A (n_559), .Y (n_58));
  BUFX2 drc_bufs10497(.A (n_360), .Y (n_57));
  BUFX2 drc_bufs10498(.A (n_497), .Y (n_56));
  BUFX2 drc_bufs10499(.A (n_564), .Y (n_55));
  BUFX2 drc_bufs10500(.A (n_502), .Y (n_54));
  BUFX2 drc_bufs10501(.A (n_565), .Y (n_53));
  BUFX2 drc_bufs10502(.A (n_566), .Y (n_52));
  BUFX2 drc_bufs10503(.A (n_567), .Y (n_51));
  BUFX2 drc_bufs10504(.A (n_477), .Y (n_50));
  BUFX2 drc_bufs10505(.A (n_491), .Y (n_49));
  BUFX2 drc_bufs10506(.A (n_498), .Y (n_48));
  BUFX2 drc_bufs10507(.A (n_503), .Y (n_47));
  BUFX2 drc_bufs10508(.A (n_577), .Y (n_46));
  BUFX2 drc_bufs10509(.A (n_633), .Y (n_45));
  BUFX2 drc_bufs10510(.A (n_365), .Y (n_44));
  BUFX2 drc_bufs10511(.A (n_362), .Y (n_43));
  BUFX2 drc_bufs10512(.A (n_472), .Y (n_42));
  BUFX2 drc_bufs10513(.A (n_468), .Y (n_41));
  BUFX2 drc_bufs10514(.A (n_659), .Y (n_40));
  BUFX2 drc_bufs10515(.A (n_562), .Y (n_39));
  BUFX2 drc_bufs10516(.A (n_560), .Y (n_38));
  BUFX2 drc_bufs10517(.A (n_493), .Y (n_37));
  BUFX2 drc_bufs10518(.A (n_554), .Y (n_36));
  BUFX2 drc_bufs10519(.A (n_552), .Y (n_35));
  BUFX2 drc_bufs10520(.A (n_545), .Y (n_34));
  BUFX2 drc_bufs10521(.A (n_569), .Y (n_33));
  BUFX2 drc_bufs10522(.A (n_474), .Y (n_32));
  BUFX2 drc_bufs10523(.A (n_568), .Y (n_31));
  BUFX2 drc_bufs10524(.A (n_579), .Y (n_30));
  BUFX2 drc_bufs10525(.A (n_494), .Y (n_29));
  BUFX2 drc_bufs10526(.A (n_504), .Y (n_28));
  BUFX2 drc_bufs10527(.A (n_361), .Y (n_27));
  BUFX2 drc_bufs10528(.A (n_563), .Y (n_26));
  BUFX2 drc_bufs10529(.A (n_471), .Y (n_25));
  BUFX2 drc_bufs10530(.A (n_489), .Y (n_24));
  BUFX2 drc_bufs10531(.A (n_660), .Y (n_23));
  BUFX2 drc_bufs10532(.A (n_576), .Y (n_22));
  BUFX2 drc_bufs10533(.A (n_492), .Y (n_21));
  BUFX2 drc_bufs10534(.A (n_570), .Y (n_20));
  BUFX2 drc_bufs10535(.A (n_469), .Y (n_19));
  BUFX2 drc_bufs10536(.A (n_578), .Y (n_18));
  BUFX2 drc_bufs10537(.A (n_556), .Y (n_17));
  BUFX2 drc_bufs10538(.A (n_648), .Y (n_16));
  BUFX2 drc_bufs10539(.A (n_549), .Y (n_15));
  BUFX2 drc_bufs10540(.A (n_509), .Y (n_14));
  BUFX2 drc_bufs10541(.A (n_551), .Y (n_13));
  BUFX2 drc_bufs10542(.A (n_658), .Y (n_12));
  BUFX2 drc_bufs10543(.A (n_499), .Y (n_11));
  BUFX2 drc_bufs10544(.A (n_473), .Y (n_10));
  BUFX2 drc_bufs10545(.A (n_490), .Y (n_9));
  BUFX2 drc_bufs10546(.A (n_470), .Y (n_8));
  BUFX2 drc_bufs10547(.A (n_557), .Y (n_7));
  BUFX2 drc_bufs10548(.A (n_496), .Y (n_6));
  BUFX2 drc_bufs10549(.A (n_550), .Y (n_5));
  BUFX2 drc_bufs10550(.A (n_467), .Y (n_4));
  BUFX2 drc_bufs10551(.A (n_571), .Y (n_3));
  BUFX2 drc_bufs10552(.A (n_558), .Y (n_2));
  BUFX2 drc_bufs10553(.A (n_574), .Y (n_1));
  BUFX2 drc_bufs10554(.A (n_483), .Y (n_0));
  BUFX2 drc_bufs10555(.A (n_643), .Y (n_207));
  BUFX2 drc_bufs10556(.A (n_516), .Y (n_208));
  BUFX2 drc_bufs10557(.A (n_409), .Y (n_206));
  BUFX2 drc_bufs10558(.A (n_249), .Y (n_209));
  XNOR2X1 add_321_65_g702__5526(.A (add_321_65_n_558), .B
       (add_321_65_n_621), .Y (id_branch_addrtarget_31));
  FAX1 add_321_65_g703__6783(.A (id_pc_30), .B (id_insn_25), .C
       (add_321_65_n_560), .YC (add_321_65_n_558), .YS
       (id_branch_addrtarget_30));
  FAX1 add_321_65_g704__3680(.A (id_pc_29), .B (id_insn_25), .C
       (add_321_65_n_563), .YC (add_321_65_n_560), .YS
       (id_branch_addrtarget_29));
  FAX1 add_321_65_g705__1617(.A (id_pc_28), .B (id_insn_25), .C
       (add_321_65_n_565), .YC (add_321_65_n_563), .YS
       (id_branch_addrtarget_28));
  FAX1 add_321_65_g706__2802(.A (id_pc_27), .B (id_insn_25), .C
       (add_321_65_n_567), .YC (add_321_65_n_565), .YS
       (id_branch_addrtarget_27));
  FAX1 add_321_65_g707__1705(.A (id_pc_26), .B (id_insn_24), .C
       (add_321_65_n_569), .YC (add_321_65_n_567), .YS
       (id_branch_addrtarget_26));
  FAX1 add_321_65_g708__5122(.A (id_pc_25), .B (id_insn_23), .C
       (add_321_65_n_571), .YC (add_321_65_n_569), .YS
       (id_branch_addrtarget_25));
  FAX1 add_321_65_g709__8246(.A (id_pc_24), .B (id_insn_22), .C
       (add_321_65_n_573), .YC (add_321_65_n_571), .YS
       (id_branch_addrtarget_24));
  FAX1 add_321_65_g710__7098(.A (id_pc_23), .B (id_insn_21), .C
       (add_321_65_n_575), .YC (add_321_65_n_573), .YS
       (id_branch_addrtarget_23));
  FAX1 add_321_65_g711__6131(.A (id_pc_22), .B (id_insn_20), .C
       (add_321_65_n_577), .YC (add_321_65_n_575), .YS
       (id_branch_addrtarget_22));
  FAX1 add_321_65_g712__1881(.A (id_pc_21), .B (id_insn_19), .C
       (add_321_65_n_579), .YC (add_321_65_n_577), .YS
       (id_branch_addrtarget_21));
  FAX1 add_321_65_g713__5115(.A (id_pc_20), .B (id_insn_18), .C
       (add_321_65_n_581), .YC (add_321_65_n_579), .YS
       (id_branch_addrtarget_20));
  FAX1 add_321_65_g714__7482(.A (id_pc_19), .B (id_insn_17), .C
       (add_321_65_n_583), .YC (add_321_65_n_581), .YS
       (id_branch_addrtarget_19));
  FAX1 add_321_65_g715__4733(.A (id_pc_18), .B (id_insn_16), .C
       (add_321_65_n_585), .YC (add_321_65_n_583), .YS
       (id_branch_addrtarget_18));
  FAX1 add_321_65_g716__6161(.A (id_pc_17), .B (id_insn_15), .C
       (add_321_65_n_587), .YC (add_321_65_n_585), .YS
       (id_branch_addrtarget_17));
  FAX1 add_321_65_g717__9315(.A (id_pc_16), .B (id_insn_14), .C
       (add_321_65_n_589), .YC (add_321_65_n_587), .YS
       (id_branch_addrtarget_16));
  FAX1 add_321_65_g718__9945(.A (id_pc_15), .B (id_insn_13), .C
       (add_321_65_n_591), .YC (add_321_65_n_589), .YS
       (id_branch_addrtarget_15));
  FAX1 add_321_65_g719__2883(.A (id_pc_14), .B (id_insn_12), .C
       (add_321_65_n_593), .YC (add_321_65_n_591), .YS
       (id_branch_addrtarget_14));
  FAX1 add_321_65_g720__2346(.A (id_pc_13), .B (id_insn_11), .C
       (add_321_65_n_595), .YC (add_321_65_n_593), .YS
       (id_branch_addrtarget_13));
  FAX1 add_321_65_g721__1666(.A (id_pc_12), .B (id_insn_10), .C
       (add_321_65_n_597), .YC (add_321_65_n_595), .YS
       (id_branch_addrtarget_12));
  FAX1 add_321_65_g722__7410(.A (id_pc_11), .B (id_insn_9), .C
       (add_321_65_n_599), .YC (add_321_65_n_597), .YS
       (id_branch_addrtarget_11));
  FAX1 add_321_65_g723__6417(.A (id_pc_10), .B (id_insn_8), .C
       (add_321_65_n_601), .YC (add_321_65_n_599), .YS
       (id_branch_addrtarget_10));
  FAX1 add_321_65_g724__5477(.A (id_pc_9), .B (id_insn_7), .C
       (add_321_65_n_603), .YC (add_321_65_n_601), .YS
       (id_branch_addrtarget_9));
  FAX1 add_321_65_g725__2398(.A (id_pc_8), .B (id_insn_6), .C
       (add_321_65_n_605), .YC (add_321_65_n_603), .YS
       (id_branch_addrtarget_8));
  FAX1 add_321_65_g726__5107(.A (id_pc_7), .B (id_insn_5), .C
       (add_321_65_n_607), .YC (add_321_65_n_605), .YS
       (id_branch_addrtarget_7));
  FAX1 add_321_65_g727__6260(.A (id_pc_6), .B (id_insn_4), .C
       (add_321_65_n_609), .YC (add_321_65_n_607), .YS
       (id_branch_addrtarget_6));
  FAX1 add_321_65_g728__4319(.A (id_pc_5), .B (id_insn_3), .C
       (add_321_65_n_611), .YC (add_321_65_n_609), .YS
       (id_branch_addrtarget_5));
  FAX1 add_321_65_g729__8428(.A (id_pc_4), .B (id_insn_2), .C
       (add_321_65_n_613), .YC (add_321_65_n_611), .YS
       (id_branch_addrtarget_4));
  FAX1 add_321_65_g730__5526(.A (id_pc_3), .B (id_insn_1), .C
       (add_321_65_n_615), .YC (add_321_65_n_613), .YS
       (id_branch_addrtarget_3));
  HAX1 add_321_65_g731__6783(.A (id_pc_2), .B (id_insn_0), .YC
       (add_321_65_n_615), .YS (id_branch_addrtarget_2));
  XNOR2X1 add_321_65_g2__3680(.A (id_insn_25), .B (id_pc_31), .Y
       (add_321_65_n_621));
endmodule

