# -*- coding: utf-8 -*-
"""Copy of fuzzing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10KL-zfgF5K7_3-aGjLV5-21MuvpXeycA

##Initialize

##BITFLLIP 1/1
"""

def b11(input_bin):
  bin_list=list(input_bin)

  for gh in range(len(bin_list)):
    bin_list[gh]='0' if bin_list[gh] == '1' else '1'
    mutated_binary = ''.join(bin_list)
    file1 = open('mutated_seeds.txt', 'a')
    file1.writelines(mutated_binary + '\n')
    file1.close()
    bin_list=list(input_bin)
  return ()

import random
def dec_bin(binary):
    num = int(binary, 2)
    return num

"""##BITFLLIP 2/1"""

def b21(input_bin):
  l=list(input_bin)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set b21  \n")
  file1.close()

  for x in range (0, len(l)-1):
    for y in range(2):
     #print(l[x+y])
      l[x+y]='0' if l[x+y]=='1'   else '1'
      #print(l[x+y])

    mutated_seq= ''.join(l)
    file1=open('fuzz_mutated_seeds.txt', 'a')
    file1.writelines(mutated_seq + '\n')
    file1.close()

    l=list(input_bin)
  return ()

"""##BITFLIP4/1

"""

def b41(input_bin):
  l=list(input_bin)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set 41  \n")
  file1.close()

  for x in range (0, len(l)-3):
    for y in range(4):
     #print(l[x+y])
      l[x+y]='0' if l[x+y]=='1'   else '1'
      #print(l[x+y])

    mutated_seq= ''.join(l)
    #print(mutated_seq)
    file1=open('fuzz_mutated_seeds.txt', 'a')
    file1.writelines(mutated_seq + '\n')
    file1.close()

    l=list(input_bin)
  return ()

"""##BITFLIP 8/8"""

def b88(input_bin):
  l=list(input_bin)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set b88 \n")
  file1.close()

  for x in range (0, len(l)-7):
    for y in range(8):
     #print(l[x+y])
      l[x+y]='0' if l[x+y]=='1'   else '1'
      #print(l[x+y])

    mutated_seq= ''.join(l)
    #print(mutated_seq)
    file1=open('fuzz_mutated_seeds.txt', 'a')
    file1.writelines(mutated_seq + '\n')
    file1.close()

    l=list(input_bin)
  return ()

"""##BITFLIP 16"""

def b16(input_bin):
  l=list(input_bin)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set B16  \n")
  file1.close()

  for x in range (0, len(l)-15):
    for y in range(16):
     #print(l[x+y])
      l[x+y]='0' if l[x+y]=='1'   else '1'
      #print(l[x+y])

    mutated_seq= ''.join(l)
    #print(mutated_seq)
    file1=open('fuzz_mutated_seeds.txt', 'a')
    file1.writelines(mutated_seq + '\n')
    file1.close()

    l=list(input_bin)
  return ()

"""## BITFLIP 32"""

def b32(input_bin):
  l=list(input_bin)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set B32  \n")
  file1.close()

  for x in range (0, len(l)-31):
    for y in range(32):
     #print(l[x+y])
      l[x+y]='0' if l[x+y]=='1'   else '1'
      #print(l[x+y])

    mutated_seq= ''.join(l)
    #print(mutated_seq)
    file1=open('fuzz_mutated_seeds.txt', 'a')
    file1.writelines(mutated_seq + '\n')
    file1.close()

    l=list(input_bin)
  return ()

"""## ARITH 8"""

def arith8(input_bin):
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set a8  \n")
  file1.close()


  for x in range (0, len(input_bin)-7):
    bin_to_dec=dec_bin(input_bin[x:   x+8])  #coverting bin to dec
    #print("binary to decimal:",bin_to_dec)
    random_number = random.randint(0, 36) # rand number generat
    #random_number=30
    #print("random_number:", random_number)

    random_number_addbin= bin(random_number+ bin_to_dec) #addition of 2 numbers and converetd to binary
    #print("Random Number in Binary",random_number_addbin)

    kj=len(random_number_addbin[2:])

    #print(kj)



    if (kj <= 8):
      final_addsub=random_number_addbin[2:].zfill(8) # filling with zeros to match length string data
      #print(final_addsub)

    else:
      final_addsub=random_number_addbin[3:].zfill(8) # filling with zeros to match length string data
      #print(final_addsub)


    li=list(input_bin) #List data
    uinp=list(input_bin)

    for y,char in enumerate(final_addsub):
      li[x+y]=char

    mutated_seq=''.join(li)

    #mutated_seq=elim +
    #print(mutated_seq)
    file1=open('fuzz_mutated_seeds.txt', 'a')
    file1.writelines(mutated_seq + '\n')
    file1.close()

    input_bin=''.join(uinp)
  return ()

#arith8('111111111')


def arith16(input_bin):
    """Applies arithmetic mutation by adding a random number (0-36) to 16-bit segments of the binary input."""
    file1 = open('fuzz_mutated_seeds.txt', 'a')
    file1.close()

    for x in range(0, len(input_bin) - 15):  # Ensure 16-bit segments exist
        bin_to_dec = dec_bin(input_bin[x: x+16])  # Convert binary to decimal
        random_number = random.randint(0, 36)  # Generate a random number
        
        random_number_addbin = bin(random_number + bin_to_dec)  # Addition result in binary

        kj = len(random_number_addbin[2:])  # Ignore "0b" prefix

        # Adjust final binary representation to 16 bits
        if kj <= 16:
            final_addsub = random_number_addbin[2:].zfill(16)
        else:
            final_addsub = random_number_addbin[3:].zfill(16)

        li = list(input_bin)  # Convert input to list for mutability
        uinp = list(input_bin)  # Preserve original input

        for y, char in enumerate(final_addsub):
            li[x + y] = char

        mutated_seq = ''.join(li)

        # Write mutated sequence to file
        with open('fuzz_mutated_seeds.txt', 'a') as file1:
            file1.writelines(mutated_seq + '\n')

        input_bin = ''.join(uinp)  # Restore original input for next iteration

    return ()

def arith32(input_bin):
    """Applies arithmetic mutation by adding a random number (0-36) to 32-bit segments of the binary input."""
    file1 = open('fuzz_mutated_seeds.txt', 'a')
    file1.close()

    for x in range(0, len(input_bin) - 31):  # Ensure 32-bit segments exist
        bin_to_dec = dec_bin(input_bin[x: x+32])  # Convert binary to decimal
        random_number = random.randint(0, 36)  # Generate a random number
        
        random_number_addbin = bin(random_number + bin_to_dec)  # Addition result in binary

        kj = len(random_number_addbin[2:])  # Ignore "0b" prefix

        # Adjust final binary representation to 32 bits
        if kj <= 32:
            final_addsub = random_number_addbin[2:].zfill(32)
        else:
            final_addsub = random_number_addbin[3:].zfill(32)  # Trim MSB if needed

        li = list(input_bin)  # Convert input to list for mutability
        uinp = list(input_bin)  # Preserve original input

        for y, char in enumerate(final_addsub):
            li[x + y] = char

        mutated_seq = ''.join(li)

        # Write mutated sequence to file
        with open('fuzz_mutated_seeds.txt', 'a') as file1:
            file1.writelines(mutated_seq + '\n')

        input_bin = ''.join(uinp)  # Restore original input for next iteration

    return ()
"""##NON DETERMINISTIC"""

def ndb1( input_bit):
  l=list(input_bit)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set ndb1  \n")
  file1.close()

  index=  random.randint(0, len(l) -1)
  #print(index)
  l[index]='0' if l[index] == '1' else '1'
  mutated_binary = ''.join(l)
  #print(mutated_binary)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  file1.writelines(mutated_binary + '\n')
  file1.close()
  bin_list=list(input_bit)

  return  ()

"""## I8"""

import random

interest_value8=[str(random.randint(0, 1)) for _ in range(8)]


def i8(input_bit):
  l=list(input_bit)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set I8  \n")
  file1.close()
  #print(l)
  index=random.randint(0, len(l) -8)
  #print(index)
  for x in range(0,8):
    l[index+x]=interest_value8[x]
  mutated_binary = ''.join(l)
  #print(mutated_binary)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  file1.writelines(mutated_binary + '\n')
  file1.close()

  return ()

"""## I16"""

import random

interest_value16=[str(random.randint(0, 1)) for _ in range(16)]


def i16(input_bit):
  l=list(input_bit)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set I16 \n")
  file1.close()
  #print(l)
  index=random.randint(0, len(l) -16)
  #print(index)
  for x in range(0,16):
    l[index+x]=interest_value16[x]
  mutated_binary = ''.join(l)
  #print(mutated_binary)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  file1.writelines(mutated_binary + '\n')
  file1.close()

  return ("done")

"""##i32"""

import random

interest_value32=[str(random.randint(0, 1)) for _ in range(32)]


def i32(input_bit):
  l=list(input_bit)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  #file1.writelines("Next Set I32  \n")
  file1.close()
  #print(l)
  index=random.randint(0, len(l) -32)
  #print(index)
  for x in range(0,32):
    l[index+x]=interest_value32[x]
  mutated_binary = ''.join(l)
  #print(mutated_binary)
  file1 = open('fuzz_mutated_seeds.txt', 'a')
  file1.writelines(mutated_binary + '\n')
  file1.close()

  return print("done")




def fuzz_mutation(input_file):
  count = 0
  print("----------------------------------------------------Mutation Deploying---------------------------------------------------------")
  with open(input_file, 'r') as file1:
    for line in file1:
      line = line.strip()  # Remove leading and trailing whitespace
      if line:
        bit_length=len(line)
        print("seed length:", bit_length)
        if (bit_length>1  and bit_length < 4  ) :
          print("b11,b21,ndb1")
          possible_mutattions=[b11,b21,ndb1]
        elif (bit_length >=4 and bit_length <8):
          print("b11,b21,ndb1,b41")
          possible_mutattions=[b11,b21,ndb1,b41]
        elif (bit_length >=8 and bit_length <16):
          print("b11,b21,b41,b88,i8,ndb1,arith8")
          possible_mutattions=[b11,b21,b41,b88,i8,ndb1,arith8]
        elif (bit_length >=16 and bit_length <32):
          print("b11,b21,b41,ndb1,b88,i8,i16,arith8")
          possible_mutattions=[b11,b21,b41,ndb1,b88,i8,i16,arith8]
        elif (bit_length >=32 ):
          print("all")
          #possible_mutattions=[b11,b21,b41,b88,b16,b32,arith8,ndb1,i8,i16,i32]
          possible_mutattions=[b16,b32,arith8,arith16,arith32,ndb1,i8,i16,i32]
        else:
          print("Should be atleast greater than 1")
          possible_mutattions=[]
        for func in possible_mutattions:
          func(line)
        count += 1

  print("Total Number of Initial Seeeds:", count)
  #print(possible_mutattions)