
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: Mar 22 2025 11:39:47 EDT (Mar 22 2025 15:39:47 UTC)

// Verification Directory fv/GPIO 

module GPIO(clk, i_arst, i_DATA_31, i_DATA_30, i_DATA_29, i_DATA_28,
     i_DATA_27, i_DATA_26, i_DATA_25, i_DATA_24, i_DATA_23, i_DATA_22,
     i_DATA_21, i_DATA_20, i_DATA_19, i_DATA_18, i_DATA_17, i_DATA_16,
     i_DATA_15, i_DATA_14, i_DATA_13, i_DATA_12, i_DATA_11, i_DATA_10,
     i_DATA_9, i_DATA_8, i_DATA_7, i_DATA_6, i_DATA_5, i_DATA_4,
     i_DATA_3, i_DATA_2, i_DATA_1, i_DATA_0, i_ALT, i_ALT_IN,
     i_DDIR_WE, i_DIN_RE, i_DOUT_WE, io_IO_in_31, io_IO_in_30,
     io_IO_in_29, io_IO_in_28, io_IO_in_27, io_IO_in_26, io_IO_in_25,
     io_IO_in_24, io_IO_in_23, io_IO_in_22, io_IO_in_21, io_IO_in_20,
     io_IO_in_19, io_IO_in_18, io_IO_in_17, io_IO_in_16, io_IO_in_15,
     io_IO_in_14, io_IO_in_13, io_IO_in_12, io_IO_in_11, io_IO_in_10,
     io_IO_in_9, io_IO_in_8, io_IO_in_7, io_IO_in_6, io_IO_in_5,
     io_IO_in_4, io_IO_in_3, io_IO_in_2, io_IO_in_1, io_IO_in_0,
     o_DIN_31, o_DIN_30, o_DIN_29, o_DIN_28, o_DIN_27, o_DIN_26,
     o_DIN_25, o_DIN_24, o_DIN_23, o_DIN_22, o_DIN_21, o_DIN_20,
     o_DIN_19, o_DIN_18, o_DIN_17, o_DIN_16, o_DIN_15, o_DIN_14,
     o_DIN_13, o_DIN_12, o_DIN_11, o_DIN_10, o_DIN_9, o_DIN_8, o_DIN_7,
     o_DIN_6, o_DIN_5, o_DIN_4, o_DIN_3, o_DIN_2, o_DIN_1, o_DIN_0,
     io_IO_out_31, io_IO_out_30, io_IO_out_29, io_IO_out_28,
     io_IO_out_27, io_IO_out_26, io_IO_out_25, io_IO_out_24,
     io_IO_out_23, io_IO_out_22, io_IO_out_21, io_IO_out_20,
     io_IO_out_19, io_IO_out_18, io_IO_out_17, io_IO_out_16,
     io_IO_out_15, io_IO_out_14, io_IO_out_13, io_IO_out_12,
     io_IO_out_11, io_IO_out_10, io_IO_out_9, io_IO_out_8, io_IO_out_7,
     io_IO_out_6, io_IO_out_5, io_IO_out_4, io_IO_out_3, io_IO_out_2,
     io_IO_out_1, io_IO_out_0, BAM_output);
  input clk, i_arst, i_DATA_31, i_DATA_30, i_DATA_29, i_DATA_28,
       i_DATA_27, i_DATA_26, i_DATA_25, i_DATA_24, i_DATA_23,
       i_DATA_22, i_DATA_21, i_DATA_20, i_DATA_19, i_DATA_18,
       i_DATA_17, i_DATA_16, i_DATA_15, i_DATA_14, i_DATA_13,
       i_DATA_12, i_DATA_11, i_DATA_10, i_DATA_9, i_DATA_8, i_DATA_7,
       i_DATA_6, i_DATA_5, i_DATA_4, i_DATA_3, i_DATA_2, i_DATA_1,
       i_DATA_0, i_ALT, i_ALT_IN, i_DDIR_WE, i_DIN_RE, i_DOUT_WE,
       io_IO_in_31, io_IO_in_30, io_IO_in_29, io_IO_in_28, io_IO_in_27,
       io_IO_in_26, io_IO_in_25, io_IO_in_24, io_IO_in_23, io_IO_in_22,
       io_IO_in_21, io_IO_in_20, io_IO_in_19, io_IO_in_18, io_IO_in_17,
       io_IO_in_16, io_IO_in_15, io_IO_in_14, io_IO_in_13, io_IO_in_12,
       io_IO_in_11, io_IO_in_10, io_IO_in_9, io_IO_in_8, io_IO_in_7,
       io_IO_in_6, io_IO_in_5, io_IO_in_4, io_IO_in_3, io_IO_in_2,
       io_IO_in_1, io_IO_in_0;
  output o_DIN_31, o_DIN_30, o_DIN_29, o_DIN_28, o_DIN_27, o_DIN_26,
       o_DIN_25, o_DIN_24, o_DIN_23, o_DIN_22, o_DIN_21, o_DIN_20,
       o_DIN_19, o_DIN_18, o_DIN_17, o_DIN_16, o_DIN_15, o_DIN_14,
       o_DIN_13, o_DIN_12, o_DIN_11, o_DIN_10, o_DIN_9, o_DIN_8,
       o_DIN_7, o_DIN_6, o_DIN_5, o_DIN_4, o_DIN_3, o_DIN_2, o_DIN_1,
       o_DIN_0, io_IO_out_31, io_IO_out_30, io_IO_out_29, io_IO_out_28,
       io_IO_out_27, io_IO_out_26, io_IO_out_25, io_IO_out_24,
       io_IO_out_23, io_IO_out_22, io_IO_out_21, io_IO_out_20,
       io_IO_out_19, io_IO_out_18, io_IO_out_17, io_IO_out_16,
       io_IO_out_15, io_IO_out_14, io_IO_out_13, io_IO_out_12,
       io_IO_out_11, io_IO_out_10, io_IO_out_9, io_IO_out_8,
       io_IO_out_7, io_IO_out_6, io_IO_out_5, io_IO_out_4, io_IO_out_3,
       io_IO_out_2, io_IO_out_1, io_IO_out_0, BAM_output;
  wire DDIR0, DDIR2, DDIR3, DDIR4, DDIR5, DDIR6, DDIR7, DDIR9;
  wire DDIR10, DDIR13, DDIR17, DDIR18, DDIR20, DDIR21, DDIR24, DDIR25;
  wire DDIR27, DDIR28, DDIR29, DDIR30, DOUT2, DOUT5, DOUT8, DOUT9;
  wire DOUT12, DOUT14, DOUT15, DOUT16, DOUT17, DOUT19, DOUT20, DOUT21;
  wire DOUT22, DOUT24, DOUT25, DOUT27, DOUT29, DOUT30, n_2, n_5;
  wire n_14, n_17, n_20, n_21, n_24, n_25, n_27, n_29;
  wire n_34, n_35, n_38, n_39, n_43, n_45, n_50, n_54;
  wire n_55, n_57, n_58, n_59, n_61, n_68, n_69, n_72;
  wire n_73, n_74, n_75, n_78, n_81, n_82, n_86, n_87;
  wire n_88, n_93, n_95, n_96, n_100, n_103, n_104, n_105;
  wire n_107, n_108, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_121, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_139, n_140, n_146, n_147, n_149, n_150, n_152;
  wire n_153, n_157, n_161, n_166, n_168, n_170, n_171, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_181, n_184, n_186;
  wire n_187, n_188, n_194, n_197, n_202, n_203, n_206, n_207;
  wire n_209, n_214, n_215, n_216, n_217, n_218, n_221, n_228;
  wire n_233, n_236, n_237, n_242, n_244, n_245, n_258, n_259;
  wire n_263, n_265, n_266, n_268, n_270, n_273, n_275, n_277;
  wire n_279, n_280, n_281, n_284, n_288, n_291, n_292, n_295;
  wire n_300, n_301, n_306, n_307, n_309, n_310, n_311, n_312;
  wire n_313, n_318, n_319, n_322, n_323, n_324, n_325, n_326;
  wire n_327, n_328, n_330, n_332, n_333, n_338, n_339, n_341;
  wire n_343, n_344, n_345, n_348, n_349, n_352, n_353, n_355;
  wire n_358, n_364, n_365, n_369, n_376, n_378, n_379, n_380;
  wire n_381, n_383, n_384, n_385, n_388, n_393, n_394, n_395;
  wire n_396, n_397, n_398, n_399, n_402, n_403, n_404, n_405;
  wire n_406, n_407, n_410, n_411, n_412, n_413, n_416, n_417;
  wire n_420, n_421, n_422, n_424, n_427, n_428, n_429, n_430;
  wire n_431, n_433, n_437, n_442, n_444, n_445, n_446, n_447;
  wire n_451, n_452, n_456, n_457, n_462, n_468, n_472, n_473;
  wire n_475, n_483, n_487, n_488, n_490, n_492, n_493, n_494;
  wire n_496, n_502, n_503, n_504, n_511, n_513, n_517, n_519;
  wire n_520, n_522, n_525, n_529, n_531, n_534, n_535, n_536;
  wire n_537, n_543, n_544, n_545, n_546, n_548, n_552, n_554;
  wire n_556, n_558, n_560, n_564, n_566, n_568, n_571, n_574;
  wire n_575, n_578, n_579, n_581, n_583, n_584, n_587, n_589;
  wire n_590, n_594, n_595, n_596, n_598, n_599, n_600, n_603;
  wire n_605, n_611, n_615, n_647, n_649, n_651, n_654, n_657;
  wire n_660, n_661, n_662, n_663, n_664, n_665, n_666, n_668;
  wire n_673, n_674, n_675, n_677, n_680, n_686, n_692, n_697;
  wire n_698, n_699, n_700, n_704, n_745, n_748, n_750, n_752;
  wire n_753, n_754, n_756, n_760, n_763, n_766, n_768, n_769;
  wire n_771, n_773, n_774, n_775;
  target targeti(.clk (clk), .i_arst (i_arst), .i_DATA_31 (i_DATA_31),
       .i_DATA_30 (i_DATA_30), .i_DATA_29 (i_DATA_29), .i_DATA_28
       (i_DATA_28), .i_DATA_27 (i_DATA_27), .i_DATA_26 (i_DATA_26),
       .i_DATA_25 (i_DATA_25), .i_DATA_23 (i_DATA_23), .i_DATA_22
       (i_DATA_22), .i_DATA_21 (i_DATA_21), .i_DATA_20 (i_DATA_20),
       .i_DATA_19 (i_DATA_19), .i_DATA_18 (i_DATA_18), .i_DATA_17
       (i_DATA_17), .i_DATA_16 (i_DATA_16), .i_DATA_15 (i_DATA_15),
       .i_DATA_14 (i_DATA_14), .i_DATA_13 (i_DATA_13), .i_DATA_12
       (i_DATA_12), .i_DATA_11 (i_DATA_11), .i_DATA_10 (i_DATA_10),
       .i_DATA_9 (i_DATA_9), .i_DATA_8 (i_DATA_8), .i_DATA_7
       (i_DATA_7), .i_DATA_6 (i_DATA_6), .i_DATA_5 (i_DATA_5),
       .i_DATA_4 (i_DATA_4), .i_DATA_3 (i_DATA_3), .i_DATA_2
       (i_DATA_2), .i_DATA_1 (i_DATA_1), .i_DATA_0 (i_DATA_0),
       .i_ALT_IN (i_ALT_IN), .i_DDIR_WE (i_DDIR_WE), .i_DIN_RE
       (i_DIN_RE), .i_DOUT_WE (i_DOUT_WE), .io_IO_in_31 (io_IO_in_31),
       .io_IO_in_30 (io_IO_in_30), .io_IO_in_26 (io_IO_in_26),
       .io_IO_in_25 (io_IO_in_25), .io_IO_in_24 (io_IO_in_24),
       .io_IO_in_23 (io_IO_in_23), .io_IO_in_22 (io_IO_in_22),
       .io_IO_in_21 (io_IO_in_21), .io_IO_in_20 (io_IO_in_20),
       .io_IO_in_18 (io_IO_in_18), .io_IO_in_15 (io_IO_in_15),
       .io_IO_in_13 (io_IO_in_13), .io_IO_in_12 (io_IO_in_12),
       .io_IO_in_10 (io_IO_in_10), .io_IO_in_9 (io_IO_in_9),
       .io_IO_in_7 (io_IO_in_7), .io_IO_in_6 (io_IO_in_6), .io_IO_in_5
       (io_IO_in_5), .io_IO_in_4 (io_IO_in_4), .io_IO_in_2
       (io_IO_in_2), .io_IO_in_0 (io_IO_in_0), .g7047_Y (n_68),
       .g6836__4319_Y (n_674), .g6527_Y (n_611), .g6865__2883_Y
       (n_279), .g6926__1617_Y (n_55), .g6917__5107_Y (n_647),
       .g6871__6417_Y (n_277), .\DDIR_reg[28]_Q  (DDIR28), .g6548_Y
       (n_534), .g7038_Y (n_86), .g6839__5526_Y (n_673),
       .drc_bufs6906_Y (n_75), .\DDIR_reg[18]_Q  (DDIR18),
       .g6764__5122_Y (n_700), .g6838__8428_Y (n_288), .g6934__5115_Y
       (n_39), .\o_DIN_reg[23]_Q  (o_DIN_23), .drc_bufs6729_Y (n_295),
       .g6829__6417_Y (n_291), .g6383_Y (n_2), .g6963_Y (n_338),
       .g6767__7098_Y (n_699), .g6997_Y (n_236), .g6924__6783_Y (n_59),
       .g6775__4733_Y (n_181), .drc_bufs6708_Y (n_309), .g6445_Y
       (n_422), .g6449_Y (n_430), .g6593__9315_Y (n_447), .g6368_Y
       (n_546), .\DDIR_reg[30]_Q  (DDIR30), .g6414_Y (n_358), .g7007_Y
       (n_216), .g6863__9945_Y (n_665), .g6602__5107_Y (n_429),
       .g6634__5526_Y (n_365), .g6979_Y (n_306), .\DDIR_reg[27]_Q 
       (DDIR27), .\DOUT_reg[12]_Q  (DOUT12), .g6665__5107_Y (n_766),
       .drc_bufs6876_Y (n_95), .g6615__6131_Y (n_403), .g6966_Y
       (n_332), .g7025_Y (n_115), .g6887__2802_Y (n_657),
       .g6869__7410_Y (n_663), .g6516_Y (n_599), .g6627__6417_Y
       (n_379), .g7008_Y (n_214), .g6982_Y (n_300), .\DOUT_reg[20]_Q 
       (DOUT20), .g6904__9315_Y (n_266), .\DDIR_reg[6]_Q  (DDIR6),
       .g6465_Y (n_462), .g6719__2802_Y (n_748), .g6703__6417_Y
       (n_140), .\DOUT_reg[15]_Q  (DOUT15), .g6512_Y (n_590), .g6533_Y
       (n_502), .\o_DIN_reg[1]_Q  (o_DIN_1), .drc_bufs6807_Y (n_209),
       .g6351_Y (n_496), .g6713__5526_Y (n_750), .g6455_Y (n_442),
       .g6573_Y (n_522), .g6618__7482_Y (n_397), .g6683__7098_Y
       (n_760), .g6941__2346_Y (n_25), .\DOUT_reg[9]_Q  (DOUT9),
       .g6606__5526_Y (n_421), .g6500_Y (n_596), .g6676__1617_Y
       (n_149), .g6460_Y (n_452), .g7017_Y (n_131), .g6537_Y (n_594),
       .drc_bufs6828_Y (n_130), .g6540_Y (n_513), .g6993_Y (n_244),
       .g6652__9315_Y (n_157), .drc_bufs6867_Y (n_104), .g6685__6131_Y
       (n_146), .g6389_Y (n_14), .drc_bufs6879_Y (n_93), .g6480_Y
       (n_520), .g6354_Y (n_529), .g6376_Y (n_503), .g6580__3680_Y
       (n_473), .g6650__6161_Y (n_771), .\DOUT_reg[27]_Q  (DOUT27),
       .\DOUT_reg[14]_Q  (DOUT14), .g6833__5107_Y (n_675), .g6446_Y
       (n_424), .g6898__5115_Y (n_268), .\DOUT_reg[8]_Q  (DOUT8),
       .\DDIR_reg[2]_Q  (DDIR2), .drc_bufs6897_Y (n_81), .g6892__8246_Y
       (n_270), .drc_bufs6660_Y (n_341), .g6485_Y (n_556), .g6958_Y
       (n_348), .g6872__5477_Y (n_662), .g6611__1705_Y (n_411),
       .g6626__7410_Y (n_381), .g6594__9945_Y (n_445), .g6701__7410_Y
       (n_754), .g6695__9945_Y (n_756), .\DDIR_reg[25]_Q  (DDIR25),
       .g6428_Y (n_388), .g6624__2346_Y (n_385), .g6392_Y (n_20),
       .g7020_Y (n_125), .g6547_Y (n_598), .g6406_Y (n_50), .g6976_Y
       (n_312), .g6826__1666_Y (n_292), .g6644__1881_Y (n_773),
       .\o_DIN_reg[21]_Q  (o_DIN_21), .g6704__5477_Y (n_753),
       .g6610__2802_Y (n_413), .g6517_Y (n_603), .g6911__7410_Y
       (n_649), .g6487_Y (n_558), .\o_DIN_reg[9]_Q  (o_DIN_9), .g6970_Y
       (n_324), .drc_bufs6855_Y (n_112), .g7024_Y (n_117), .g6519_Y
       (n_564), .g6608__3680_Y (n_417), .g6495_Y (n_568), .g6986_Y
       (n_258), .g6468_Y (n_468), .g6674__3680_Y (n_763),
       .drc_bufs6657_Y (n_343), .g6437_Y (n_406), .drc_bufs6861_Y
       (n_108), .g6673__6783_Y (n_150), .\DDIR_reg[0]_Q  (DDIR0),
       .drc_bufs6789_Y (n_221), .g6936__4733_Y (n_35), .drc_bufs6639_Y
       (n_355), .g6752__4319_Y (n_704), .g6773__7482_Y (n_697),
       .\o_DIN_reg[29]_Q  (o_DIN_29), .drc_bufs6771_Y (n_233), .g6973_Y
       (n_318), .g6850__8246_Y (n_284), .g6754__8428_Y (n_188),
       .g6425_Y (n_376), .g6357_Y (n_537), .g6969_Y (n_326),
       .g6790__2398_Y (n_176), .g6859__4733_Y (n_281), .g6588__1881_Y
       (n_457), .o_DIN_31 (o_DIN_31), .o_DIN_30 (o_DIN_30), .o_DIN_28
       (o_DIN_28), .o_DIN_27 (o_DIN_27), .o_DIN_26 (o_DIN_26),
       .o_DIN_25 (o_DIN_25), .o_DIN_24 (o_DIN_24), .o_DIN_22
       (o_DIN_22), .o_DIN_20 (o_DIN_20), .o_DIN_19 (o_DIN_19),
       .o_DIN_16 (o_DIN_16), .o_DIN_15 (o_DIN_15), .o_DIN_14
       (o_DIN_14), .o_DIN_13 (o_DIN_13), .o_DIN_12 (o_DIN_12),
       .o_DIN_11 (o_DIN_11), .o_DIN_8 (o_DIN_8), .o_DIN_7 (o_DIN_7),
       .o_DIN_6 (o_DIN_6), .o_DIN_5 (o_DIN_5), .o_DIN_4 (o_DIN_4),
       .o_DIN_2 (o_DIN_2), .o_DIN_0 (o_DIN_0), .io_IO_out_31
       (io_IO_out_31), .io_IO_out_30 (io_IO_out_30), .io_IO_out_27
       (io_IO_out_27), .io_IO_out_26 (io_IO_out_26), .io_IO_out_25
       (io_IO_out_25), .io_IO_out_23 (io_IO_out_23), .io_IO_out_22
       (io_IO_out_22), .io_IO_out_21 (io_IO_out_21), .io_IO_out_19
       (io_IO_out_19), .io_IO_out_18 (io_IO_out_18), .io_IO_out_16
       (io_IO_out_16), .io_IO_out_15 (io_IO_out_15), .io_IO_out_14
       (io_IO_out_14), .io_IO_out_12 (io_IO_out_12), .io_IO_out_11
       (io_IO_out_11), .io_IO_out_10 (io_IO_out_10), .io_IO_out_8
       (io_IO_out_8), .io_IO_out_7 (io_IO_out_7), .io_IO_out_6
       (io_IO_out_6), .io_IO_out_5 (io_IO_out_5), .io_IO_out_1
       (io_IO_out_1), .io_IO_out_0 (io_IO_out_0), .drc_bufs6855_A
       (n_668), .g6593__9315_B (n_446), .g6703__6417_B (n_595),
       .\DOUT_reg[27]_D  (n_369), .g6517_A (DDIR5), .g6924__6783_A
       (n_263), .\o_DIN_reg[18]_D  (n_27), .g6960_A (n_345),
       .drc_bufs6708_A (n_752), .g6624__2346_A (n_184), .g6640__8246_B
       (n_554), .drc_bufs6789_A (n_692), .g15__2883_A (n_511),
       .g6907__2883_B (n_581), .g6904__9315_C (n_74), .g6673__6783_B
       (n_574), .g6808__8246_B (n_589), .g6997_A (n_237),
       .g6850__8246_B (n_548), .\DDIR_reg[2]_D  (n_483),
       .drc_bufs6861_A (n_666), .drc_bufs6867_A (n_664), .g6593__9315_A
       (n_152), .drc_bufs6825_A (n_680), .\DDIR_reg[28]_D  (n_431),
       .g6790__2398_B (n_566), .g7019_A (n_128), .g6540_A (DOUT24),
       .\o_DIN_reg[10]_D  (n_43), .g22__5107_EN (DDIR20), .g26__5526_A
       (n_535), .\DDIR_reg[27]_D  (n_433), .g6973_A (n_319),
       .g19__6417_EN (DDIR17), .g6615__6131_A (n_175), .g6627__6417_B
       (n_378), .g7047_A (n_69), .g6775__4733_C (n_228), .g7012_A
       (n_207), .drc_bufs6906_A (n_651), .g31__1705_EN (DDIR29),
       .g6862__9315_B (n_578), .drc_bufs6771_A (n_698), .g6361_A
       (DOUT29), .g6366_A (DOUT17), .\o_DIN_reg[17]_D  (n_29),
       .g15__2883_EN (DDIR13), .g6754__8428_C (n_242), .drc_bufs6876_A
       (n_661), .g6611__1705_A (n_171), .\o_DIN_reg[29]_D  (n_5),
       .g7038_A (n_87), .g6580__3680_A (n_139), .g6624__2346_B (n_384),
       .g6966_A (n_333), .g6676__1617_B (n_575), .g6573_A (DOUT22),
       .g6614__7098_A (n_174), .g6619__4733_B (n_394), .g6610__2802_B
       (n_412), .drc_bufs6660_A (n_768), .g6754__8428_B (n_517),
       .g6982_A (n_301), .g6898__5115_B (n_615), .g6986_A (n_259),
       .g6618__7482_B (n_396), .g6898__5115_C (n_78), .g6829__6417_B
       (n_493), .g7024_A (n_118), .g6627__6417_A (n_187), .g6963_A
       (n_339), .g6970_A (n_325), .g6368_A (DOUT30), .\DDIR_reg[30]_D 
       (n_427), .g6892__8246_C (n_82), .g7025_A (n_116), .g30__2802_A
       (n_543), .g6814__5115_B (n_600), .g6634__5526_A (n_194),
       .g6626__7410_A (n_186), .g6826__1666_C (n_129), .drc_bufs6828_A
       (n_677), .\DDIR_reg[25]_D  (n_437), .g6673__6783_C (n_330),
       .drc_bufs6807_A (n_686), .g6826__1666_B (n_584), .g6865__2883_C
       (n_103), .g6373_A (DOUT2), .g6551_A (DOUT16), .g6357_A (DOUT25),
       .drc_bufs6729_A (n_745), .g7008_A (n_215), .g6626__7410_B
       (n_380), .g7045_A (n_73), .g11__4733_EN (DDIR9), .g6516_A
       (DDIR7), .g6608__3680_B (n_416), .g6__7098_A (n_494),
       .g6790__2398_C (n_218), .g7020_A (n_126), .g6924__6783_B (n_58),
       .g6594__9945_B (n_444), .g22__5107_A (n_525), .g6__7098_EN
       (DDIR4), .\o_DIN_reg[9]_D  (n_45), .g6617__5115_A (n_177),
       .g7007_A (n_217), .g7033_A (n_100), .g6883__6783_B (n_531),
       .g6862__9315_C (n_105), .g6354_A (DOUT21), .g5__8246_A (n_492),
       .g6495_A (DDIR21), .g6976_A (n_313), .g6652__9315_B (n_560),
       .\o_DIN_reg[1]_D  (n_61), .g6548_A (DOUT19), .\DDIR_reg[0]_D 
       (n_487), .\o_DIN_reg[21]_D  (n_21), .g6606__5526_A (n_166),
       .g5__8246_EN (DDIR3), .g6969_A (n_327), .g6977_A (n_311),
       .g6351_A (DOUT5), .g6838__8428_C (n_121), .g6676__1617_C
       (n_328), .g6892__8246_B (n_579), .g6588__1881_A (n_147),
       .\o_DIN_reg[3]_D  (n_57), .g6512_A (DDIR10), .g6594__9945_A
       (n_153), .g6685__6131_B (n_583), .g6602__5107_B (n_428),
       .g6936__4733_A (n_275), .\DOUT_reg[8]_D  (n_407), .g6619__4733_A
       (n_179), .g6580__3680_B (n_472), .g6859__4733_C (n_107),
       .\DDIR_reg[18]_D  (n_451), .g6958_A (n_349), .g7014_A (n_203),
       .\DOUT_reg[20]_D  (n_383), .g6993_A (n_245), .g6926__1617_B
       (n_54), .g6871__6417_B (n_605), .\o_DIN_reg[23]_D  (n_17),
       .g1__1617_A (n_488), .g26__5526_EN (DDIR24), .g6971_A (n_323),
       .g6904__9315_B (n_536), .g6618__7482_A (n_178), .g6936__4733_B
       (n_34), .g6883__6783_C (n_88), .g6979_A (n_307), .g7026_A
       (n_114), .\DDIR_reg[6]_D  (n_475), .g6838__8428_B (n_519),
       .\DOUT_reg[15]_D  (n_393), .g6588__1881_B (n_456));
  INVX1 g6480(.A (DDIR30), .Y (n_520));
  INVX1 g6537(.A (o_DIN_3), .Y (n_594));
  INVX1 g6485(.A (DDIR27), .Y (n_556));
  INVX1 g6487(.A (o_DIN_22), .Y (n_558));
  INVX1 g6495(.A (DDIR21), .Y (n_568));
  INVX1 g6494(.A (o_DIN_20), .Y (n_571));
  INVX1 g6498(.A (o_DIN_18), .Y (n_587));
  INVX1 g6500(.A (o_DIN_17), .Y (n_596));
  INVX1 g6512(.A (DDIR10), .Y (n_590));
  INVX1 g6516(.A (DDIR7), .Y (n_599));
  INVX1 g6517(.A (DDIR5), .Y (n_603));
  INVX1 g6519(.A (o_DIN_10), .Y (n_564));
  INVX1 g6527(.A (DDIR0), .Y (n_611));
  INVX1 g6533(.A (DOUT27), .Y (n_502));
  INVX1 g6354(.A (DOUT21), .Y (n_529));
  INVX1 g6540(.A (DOUT24), .Y (n_513));
  INVX1 g6573(.A (DOUT22), .Y (n_522));
  INVX1 g6547(.A (o_DIN_0), .Y (n_598));
  INVX1 g6548(.A (DOUT19), .Y (n_534));
  INVX1 g6357(.A (DOUT25), .Y (n_537));
  INVX1 g6361(.A (DOUT29), .Y (n_544));
  INVX1 g6366(.A (DOUT17), .Y (n_552));
  INVX1 g6368(.A (DOUT30), .Y (n_546));
  INVX1 g6551(.A (DOUT16), .Y (n_545));
  INVX1 g6373(.A (DOUT2), .Y (n_490));
  INVX1 g6376(.A (DOUT8), .Y (n_503));
  INVX1 g6377(.A (DOUT9), .Y (n_504));
  INVX1 g6351(.A (DOUT5), .Y (n_496));
  INVX1 g6414(.A (i_arst), .Y (n_358));
  INVX1 g6446(.A (i_arst), .Y (n_424));
  INVX1 g6383(.A (i_arst), .Y (n_2));
  INVX1 g6449(.A (i_arst), .Y (n_430));
  INVX1 g6416(.A (i_arst), .Y (n_364));
  INVX1 g6455(.A (i_arst), .Y (n_442));
  INVX1 g6401(.A (i_arst), .Y (n_38));
  INVX1 g6460(.A (i_arst), .Y (n_452));
  INVX1 g6425(.A (i_arst), .Y (n_376));
  INVX1 g6392(.A (i_arst), .Y (n_20));
  INVX1 g6465(.A (i_arst), .Y (n_462));
  INVX1 g6468(.A (i_arst), .Y (n_468));
  INVX1 g6428(.A (i_arst), .Y (n_388));
  INVX1 g6394(.A (i_arst), .Y (n_24));
  INVX1 g6406(.A (i_arst), .Y (n_50));
  INVX1 g6433(.A (i_arst), .Y (n_398));
  INVX1 g6435(.A (i_arst), .Y (n_402));
  INVX1 g6436(.A (i_arst), .Y (n_404));
  INVX1 g6437(.A (i_arst), .Y (n_406));
  INVX1 g6389(.A (i_arst), .Y (n_14));
  INVX1 g6439(.A (i_arst), .Y (n_410));
  INVX1 g6444(.A (i_arst), .Y (n_420));
  INVX1 g6445(.A (i_arst), .Y (n_422));
  DFFPOSX1 \DDIR_reg[0] (.CLK (clk), .D (n_487), .Q (DDIR0));
  DFFPOSX1 \DDIR_reg[2] (.CLK (clk), .D (n_483), .Q (DDIR2));
  DFFPOSX1 \DDIR_reg[6] (.CLK (clk), .D (n_475), .Q (DDIR6));
  DFFPOSX1 \DDIR_reg[18] (.CLK (clk), .D (n_451), .Q (DDIR18));
  DFFPOSX1 \DDIR_reg[25] (.CLK (clk), .D (n_437), .Q (DDIR25));
  DFFPOSX1 \DDIR_reg[27] (.CLK (clk), .D (n_433), .Q (DDIR27));
  DFFPOSX1 \DDIR_reg[28] (.CLK (clk), .D (n_431), .Q (DDIR28));
  DFFPOSX1 \DDIR_reg[30] (.CLK (clk), .D (n_427), .Q (DDIR30));
  DFFPOSX1 \DOUT_reg[8] (.CLK (clk), .D (n_407), .Q (DOUT8));
  DFFPOSX1 \DOUT_reg[9] (.CLK (clk), .D (n_405), .Q (DOUT9));
  DFFPOSX1 \DOUT_reg[12] (.CLK (clk), .D (n_399), .Q (DOUT12));
  DFFPOSX1 \DOUT_reg[14] (.CLK (clk), .D (n_395), .Q (DOUT14));
  DFFPOSX1 \DOUT_reg[15] (.CLK (clk), .D (n_393), .Q (DOUT15));
  DFFPOSX1 \DOUT_reg[20] (.CLK (clk), .D (n_383), .Q (DOUT20));
  DFFPOSX1 \DOUT_reg[27] (.CLK (clk), .D (n_369), .Q (DOUT27));
  TBUFX2 g1__1617(.A (n_488), .EN (i_ALT), .Y (BAM_output));
  TBUFX2 g4__5122(.A (n_490), .EN (DDIR2), .Y (io_IO_out_2));
  TBUFX2 g5__8246(.A (n_492), .EN (DDIR3), .Y (io_IO_out_3));
  TBUFX2 g6__7098(.A (n_494), .EN (DDIR4), .Y (io_IO_out_4));
  TBUFX2 g11__4733(.A (n_504), .EN (DDIR9), .Y (io_IO_out_9));
  TBUFX2 g15__2883(.A (n_511), .EN (DDIR13), .Y (io_IO_out_13));
  TBUFX2 g19__6417(.A (n_552), .EN (DDIR17), .Y (io_IO_out_17));
  TBUFX2 g22__5107(.A (n_525), .EN (DDIR20), .Y (io_IO_out_20));
  TBUFX2 g26__5526(.A (n_535), .EN (DDIR24), .Y (io_IO_out_24));
  TBUFX2 g30__2802(.A (n_543), .EN (DDIR28), .Y (io_IO_out_28));
  TBUFX2 g31__1705(.A (n_544), .EN (DDIR29), .Y (io_IO_out_29));
  AND2X1 g6580__3680(.A (n_139), .B (n_472), .Y (n_473));
  AND2X1 g6588__1881(.A (n_147), .B (n_456), .Y (n_457));
  AND2X1 g6593__9315(.A (n_152), .B (n_446), .Y (n_447));
  AND2X1 g6594__9945(.A (n_153), .B (n_444), .Y (n_445));
  AND2X1 g6602__5107(.A (n_161), .B (n_428), .Y (n_429));
  AND2X1 g6606__5526(.A (n_166), .B (n_420), .Y (n_421));
  AND2X1 g6608__3680(.A (n_168), .B (n_416), .Y (n_417));
  AND2X1 g6610__2802(.A (n_170), .B (n_412), .Y (n_413));
  AND2X1 g6611__1705(.A (n_171), .B (n_410), .Y (n_411));
  AND2X1 g6614__7098(.A (n_174), .B (n_404), .Y (n_405));
  AND2X1 g6615__6131(.A (n_175), .B (n_402), .Y (n_403));
  AND2X1 g6617__5115(.A (n_177), .B (n_398), .Y (n_399));
  AND2X1 g6618__7482(.A (n_178), .B (n_396), .Y (n_397));
  AND2X1 g6619__4733(.A (n_179), .B (n_394), .Y (n_395));
  AND2X1 g6624__2346(.A (n_184), .B (n_384), .Y (n_385));
  AND2X1 g6626__7410(.A (n_186), .B (n_380), .Y (n_381));
  AND2X1 g6627__6417(.A (n_187), .B (n_378), .Y (n_379));
  AND2X1 g6634__5526(.A (n_194), .B (n_364), .Y (n_365));
  NAND2X1 g6638__5122(.A (i_DATA_30), .B (i_DDIR_WE), .Y (n_775));
  BUFX2 drc_bufs6639(.A (n_775), .Y (n_355));
  OAI21X1 g6640__8246(.A (i_DDIR_WE), .B (n_554), .C (n_352), .Y
       (n_161));
  NAND2X1 g6641__7098(.A (i_DATA_29), .B (i_DDIR_WE), .Y (n_774));
  BUFX2 drc_bufs6642(.A (n_774), .Y (n_353));
  NAND2X1 g6644__1881(.A (i_DATA_28), .B (i_DDIR_WE), .Y (n_773));
  NAND2X1 g6650__6161(.A (i_DATA_26), .B (i_DDIR_WE), .Y (n_771));
  OAI21X1 g6652__9315(.A (i_DDIR_WE), .B (n_560), .C (n_344), .Y
       (n_157));
  NAND2X1 g6656__2346(.A (i_DATA_24), .B (i_DDIR_WE), .Y (n_769));
  BUFX2 drc_bufs6657(.A (n_769), .Y (n_343));
  BUFX2 drc_bufs6660(.A (n_768), .Y (n_341));
  NAND2X1 g6665__5107(.A (i_DATA_21), .B (i_DDIR_WE), .Y (n_766));
  OAI21X1 g6673__6783(.A (i_DDIR_WE), .B (n_574), .C (n_330), .Y
       (n_150));
  NAND2X1 g6674__3680(.A (i_DATA_18), .B (i_DDIR_WE), .Y (n_763));
  OAI21X1 g6676__1617(.A (i_DDIR_WE), .B (n_575), .C (n_328), .Y
       (n_149));
  NAND2X1 g6683__7098(.A (i_DATA_15), .B (i_DDIR_WE), .Y (n_760));
  OAI21X1 g6685__6131(.A (i_DDIR_WE), .B (n_583), .C (n_322), .Y
       (n_146));
  NAND2X1 g6695__9945(.A (i_DATA_11), .B (i_DDIR_WE), .Y (n_756));
  NAND2X1 g6701__7410(.A (i_DATA_9), .B (i_DDIR_WE), .Y (n_754));
  OAI21X1 g6703__6417(.A (i_DDIR_WE), .B (n_595), .C (n_310), .Y
       (n_140));
  NAND2X1 g6704__5477(.A (i_DATA_8), .B (i_DDIR_WE), .Y (n_753));
  BUFX2 drc_bufs6708(.A (n_752), .Y (n_309));
  NAND2X1 g6713__5526(.A (i_DATA_5), .B (i_DDIR_WE), .Y (n_750));
  NAND2X1 g6719__2802(.A (i_DATA_3), .B (i_DDIR_WE), .Y (n_748));
  BUFX2 drc_bufs6729(.A (n_745), .Y (n_295));
  NAND2X1 g6752__4319(.A (i_DATA_24), .B (i_DOUT_WE), .Y (n_704));
  OAI21X1 g6754__8428(.A (i_DOUT_WE), .B (n_517), .C (n_242), .Y
       (n_188));
  NAND2X1 g6764__5122(.A (i_DATA_20), .B (i_DOUT_WE), .Y (n_700));
  NAND2X1 g6767__7098(.A (i_DATA_19), .B (i_DOUT_WE), .Y (n_699));
  BUFX2 drc_bufs6771(.A (n_698), .Y (n_233));
  NAND2X1 g6773__7482(.A (i_DATA_17), .B (i_DOUT_WE), .Y (n_697));
  OAI21X1 g6775__4733(.A (i_DOUT_WE), .B (n_545), .C (n_228), .Y
       (n_181));
  BUFX2 drc_bufs6789(.A (n_692), .Y (n_221));
  OAI21X1 g6790__2398(.A (i_DOUT_WE), .B (n_566), .C (n_218), .Y
       (n_176));
  BUFX2 drc_bufs6807(.A (n_686), .Y (n_209));
  OAI21X1 g6808__8246(.A (i_DOUT_WE), .B (n_589), .C (n_206), .Y
       (n_170));
  OAI21X1 g6814__5115(.A (i_DOUT_WE), .B (n_600), .C (n_202), .Y
       (n_168));
  BUFX2 drc_bufs6825(.A (n_680), .Y (n_197));
  OAI21X1 g6826__1666(.A (i_DIN_RE), .B (n_584), .C (n_129), .Y
       (n_292));
  BUFX2 drc_bufs6828(.A (n_677), .Y (n_130));
  OAI21X1 g6829__6417(.A (i_DIN_RE), .B (n_493), .C (n_127), .Y
       (n_291));
  NAND2X1 g6833__5107(.A (i_DIN_RE), .B (io_IO_in_29), .Y (n_675));
  NAND2X1 g6836__4319(.A (i_DIN_RE), .B (io_IO_in_28), .Y (n_674));
  OAI21X1 g6838__8428(.A (i_DIN_RE), .B (n_519), .C (n_121), .Y
       (n_288));
  NAND2X1 g6839__5526(.A (i_DIN_RE), .B (io_IO_in_27), .Y (n_673));
  OAI21X1 g6850__8246(.A (i_DIN_RE), .B (n_548), .C (n_113), .Y
       (n_284));
  BUFX2 drc_bufs6855(.A (n_668), .Y (n_112));
  OAI21X1 g6859__4733(.A (i_DIN_RE), .B (n_571), .C (n_107), .Y
       (n_281));
  BUFX2 drc_bufs6861(.A (n_666), .Y (n_108));
  OAI21X1 g6862__9315(.A (i_DIN_RE), .B (n_578), .C (n_105), .Y
       (n_280));
  NAND2X1 g6863__9945(.A (i_DIN_RE), .B (io_IO_in_19), .Y (n_665));
  OAI21X1 g6865__2883(.A (i_DIN_RE), .B (n_587), .C (n_103), .Y
       (n_279));
  BUFX2 drc_bufs6867(.A (n_664), .Y (n_104));
  NAND2X1 g6869__7410(.A (i_DIN_RE), .B (io_IO_in_17), .Y (n_663));
  OAI21X1 g6871__6417(.A (i_DIN_RE), .B (n_605), .C (n_96), .Y (n_277));
  NAND2X1 g6872__5477(.A (i_DIN_RE), .B (io_IO_in_16), .Y (n_662));
  BUFX2 drc_bufs6876(.A (n_661), .Y (n_95));
  NAND2X1 g6878__4319(.A (i_DIN_RE), .B (io_IO_in_14), .Y (n_660));
  BUFX2 drc_bufs6879(.A (n_660), .Y (n_93));
  OAI21X1 g6883__6783(.A (i_DIN_RE), .B (n_531), .C (n_88), .Y (n_273));
  NAND2X1 g6887__2802(.A (i_DIN_RE), .B (io_IO_in_11), .Y (n_657));
  OAI21X1 g6892__8246(.A (i_DIN_RE), .B (n_579), .C (n_82), .Y (n_270));
  NAND2X1 g6896__1881(.A (i_DIN_RE), .B (io_IO_in_8), .Y (n_654));
  BUFX2 drc_bufs6897(.A (n_654), .Y (n_81));
  OAI21X1 g6898__5115(.A (i_DIN_RE), .B (n_615), .C (n_78), .Y (n_268));
  OAI21X1 g6904__9315(.A (i_DIN_RE), .B (n_536), .C (n_74), .Y (n_266));
  BUFX2 drc_bufs6906(.A (n_651), .Y (n_75));
  OAI21X1 g6907__2883(.A (i_DIN_RE), .B (n_581), .C (n_72), .Y (n_265));
  NAND2X1 g6911__7410(.A (i_DIN_RE), .B (io_IO_in_3), .Y (n_649));
  NAND2X1 g6917__5107(.A (i_DIN_RE), .B (io_IO_in_1), .Y (n_647));
  AND2X1 g6924__6783(.A (n_263), .B (n_58), .Y (n_59));
  AND2X1 g6926__1617(.A (n_265), .B (n_54), .Y (n_55));
  AND2X1 g6934__5115(.A (n_273), .B (n_38), .Y (n_39));
  AND2X1 g6936__4733(.A (n_275), .B (n_34), .Y (n_35));
  AND2X1 g6941__2346(.A (n_280), .B (n_24), .Y (n_25));
  DFFPOSX1 \o_DIN_reg[1] (.CLK (clk), .D (n_61), .Q (o_DIN_1));
  DFFPOSX1 \o_DIN_reg[3] (.CLK (clk), .D (n_57), .Q (o_DIN_3));
  DFFPOSX1 \o_DIN_reg[9] (.CLK (clk), .D (n_45), .Q (o_DIN_9));
  DFFPOSX1 \o_DIN_reg[10] (.CLK (clk), .D (n_43), .Q (o_DIN_10));
  DFFPOSX1 \o_DIN_reg[17] (.CLK (clk), .D (n_29), .Q (o_DIN_17));
  DFFPOSX1 \o_DIN_reg[18] (.CLK (clk), .D (n_27), .Q (o_DIN_18));
  DFFPOSX1 \o_DIN_reg[21] (.CLK (clk), .D (n_21), .Q (o_DIN_21));
  DFFPOSX1 \o_DIN_reg[23] (.CLK (clk), .D (n_17), .Q (o_DIN_23));
  DFFPOSX1 \o_DIN_reg[29] (.CLK (clk), .D (n_5), .Q (o_DIN_29));
  BUFX2 g6956(.A (n_353), .Y (n_352));
  BUFX2 g6958(.A (n_349), .Y (n_348));
  BUFX2 g6960(.A (n_345), .Y (n_344));
  BUFX2 g6963(.A (n_339), .Y (n_338));
  BUFX2 g6966(.A (n_333), .Y (n_332));
  BUFX2 g6969(.A (n_327), .Y (n_326));
  BUFX2 g6970(.A (n_325), .Y (n_324));
  BUFX2 g6971(.A (n_323), .Y (n_322));
  BUFX2 g6973(.A (n_319), .Y (n_318));
  BUFX2 g6976(.A (n_313), .Y (n_312));
  BUFX2 g6977(.A (n_311), .Y (n_310));
  BUFX2 g6979(.A (n_307), .Y (n_306));
  BUFX2 g6982(.A (n_301), .Y (n_300));
  BUFX2 g6986(.A (n_259), .Y (n_258));
  BUFX2 g6993(.A (n_245), .Y (n_244));
  BUFX2 g6997(.A (n_237), .Y (n_236));
  BUFX2 g7007(.A (n_217), .Y (n_216));
  BUFX2 g7008(.A (n_215), .Y (n_214));
  BUFX2 g7012(.A (n_207), .Y (n_206));
  BUFX2 g7014(.A (n_203), .Y (n_202));
  BUFX2 g7017(.A (n_197), .Y (n_131));
  BUFX2 g7019(.A (n_128), .Y (n_127));
  BUFX2 g7020(.A (n_126), .Y (n_125));
  BUFX2 g7024(.A (n_118), .Y (n_117));
  BUFX2 g7025(.A (n_116), .Y (n_115));
  BUFX2 g7026(.A (n_114), .Y (n_113));
  BUFX2 g7033(.A (n_100), .Y (n_96));
  BUFX2 g7038(.A (n_87), .Y (n_86));
  BUFX2 g7045(.A (n_73), .Y (n_72));
  BUFX2 g7047(.A (n_69), .Y (n_68));
endmodule

