
// Generated by Cadence Genus(TM) Synthesis Solution 22.15-s086_1
// Generated on: Mar 22 2025 11:39:33 EDT (Mar 22 2025 15:39:33 UTC)

// Verification Directory  

module target(clk, i_arst, i_DATA_31, i_DATA_30, i_DATA_29, i_DATA_28,
     i_DATA_27, i_DATA_26, i_DATA_25, i_DATA_23, i_DATA_22, i_DATA_21,
     i_DATA_20, i_DATA_19, i_DATA_18, i_DATA_17, i_DATA_16, i_DATA_15,
     i_DATA_14, i_DATA_13, i_DATA_12, i_DATA_11, i_DATA_10, i_DATA_9,
     i_DATA_8, i_DATA_7, i_DATA_6, i_DATA_5, i_DATA_4, i_DATA_3,
     i_DATA_2, i_DATA_1, i_DATA_0, i_ALT_IN, i_DDIR_WE, i_DIN_RE,
     i_DOUT_WE, io_IO_in_31, io_IO_in_30, io_IO_in_26, io_IO_in_25,
     io_IO_in_24, io_IO_in_23, io_IO_in_22, io_IO_in_21, io_IO_in_20,
     io_IO_in_18, io_IO_in_15, io_IO_in_13, io_IO_in_12, io_IO_in_10,
     io_IO_in_9, io_IO_in_7, io_IO_in_6, io_IO_in_5, io_IO_in_4,
     io_IO_in_2, io_IO_in_0, g7047_Y, g6836__4319_Y, g6527_Y,
     g6865__2883_Y, g6926__1617_Y, g6917__5107_Y, g6871__6417_Y,
     DDIR_reg_28__Q , g6548_Y, g7038_Y, g6839__5526_Y, drc_bufs6906_Y,
     DDIR_reg_18__Q , g6764__5122_Y, g6838__8428_Y, g6934__5115_Y,
     o_DIN_reg_23__Q , drc_bufs6729_Y, g6829__6417_Y, g6383_Y,
     g6963_Y, g6767__7098_Y, g6997_Y, g6924__6783_Y, g6775__4733_Y,
     drc_bufs6708_Y, g6445_Y, g6449_Y, g6593__9315_Y, g6368_Y,
     DDIR_reg_30__Q , g6414_Y, g7007_Y, g6863__9945_Y, g6602__5107_Y,
     g6634__5526_Y, g6979_Y, DDIR_reg_27__Q , DOUT_reg_12__Q ,
     g6665__5107_Y, drc_bufs6876_Y, g6615__6131_Y, g6966_Y, g7025_Y,
     g6887__2802_Y, g6869__7410_Y, g6516_Y, g6627__6417_Y, g7008_Y,
     g6982_Y, DOUT_reg_20__Q , g6904__9315_Y, DDIR_reg_6__Q ,
     g6465_Y, g6719__2802_Y, g6703__6417_Y, DOUT_reg_15__Q , g6512_Y,
     g6533_Y, o_DIN_reg_1__Q , drc_bufs6807_Y, g6351_Y, g6713__5526_Y,
     g6455_Y, g6573_Y, g6618__7482_Y, g6683__7098_Y, g6941__2346_Y,
     DOUT_reg_9__Q , g6606__5526_Y, g6500_Y, g6676__1617_Y, g6460_Y,
     g7017_Y, g6537_Y, drc_bufs6828_Y, g6540_Y, g6993_Y, g6652__9315_Y,
     drc_bufs6867_Y, g6685__6131_Y, g6389_Y, drc_bufs6879_Y, g6480_Y,
     g6354_Y, g6376_Y, g6580__3680_Y, g6650__6161_Y, DOUT_reg_27__Q ,
     DOUT_reg_14__Q , g6833__5107_Y, g6446_Y, g6898__5115_Y,
     DOUT_reg_8__Q , DDIR_reg_2__Q , drc_bufs6897_Y, g6892__8246_Y,
     drc_bufs6660_Y, g6485_Y, g6958_Y, g6872__5477_Y, g6611__1705_Y,
     g6626__7410_Y, g6594__9945_Y, g6701__7410_Y, g6695__9945_Y,
     DDIR_reg_25__Q , g6428_Y, g6624__2346_Y, g6392_Y, g7020_Y,
     g6547_Y, g6406_Y, g6976_Y, g6826__1666_Y, g6644__1881_Y,
     o_DIN_reg_21__Q , g6704__5477_Y, g6610__2802_Y, g6517_Y,
     g6911__7410_Y, g6487_Y, o_DIN_reg_9__Q , g6970_Y, drc_bufs6855_Y,
     g7024_Y, g6519_Y, g6608__3680_Y, g6495_Y, g6986_Y, g6468_Y,
     g6674__3680_Y, drc_bufs6657_Y, g6437_Y, drc_bufs6861_Y,
     g6673__6783_Y, DDIR_reg_0__Q , drc_bufs6789_Y, g6936__4733_Y,
     drc_bufs6639_Y, g6752__4319_Y, g6773__7482_Y, o_DIN_reg_29__Q ,
     drc_bufs6771_Y, g6973_Y, g6850__8246_Y, g6754__8428_Y, g6425_Y,
     g6357_Y, g6969_Y, g6790__2398_Y, g6859__4733_Y, g6588__1881_Y,
     o_DIN_31, o_DIN_30, o_DIN_28, o_DIN_27, o_DIN_26, o_DIN_25,
     o_DIN_24, o_DIN_22, o_DIN_20, o_DIN_19, o_DIN_16, o_DIN_15,
     o_DIN_14, o_DIN_13, o_DIN_12, o_DIN_11, o_DIN_8, o_DIN_7, o_DIN_6,
     o_DIN_5, o_DIN_4, o_DIN_2, o_DIN_0, io_IO_out_31, io_IO_out_30,
     io_IO_out_27, io_IO_out_26, io_IO_out_25, io_IO_out_23,
     io_IO_out_22, io_IO_out_21, io_IO_out_19, io_IO_out_18,
     io_IO_out_16, io_IO_out_15, io_IO_out_14, io_IO_out_12,
     io_IO_out_11, io_IO_out_10, io_IO_out_8, io_IO_out_7, io_IO_out_6,
     io_IO_out_5, io_IO_out_1, io_IO_out_0, drc_bufs6855_A,
     g6593__9315_B, g6703__6417_B, DOUT_reg_27__D , g6517_A,
     g6924__6783_A, o_DIN_reg_18__D , g6960_A, drc_bufs6708_A,
     g6624__2346_A, g6640__8246_B, drc_bufs6789_A, g15__2883_A,
     g6907__2883_B, g6904__9315_C, g6673__6783_B, g6808__8246_B,
     g6997_A, g6850__8246_B, DDIR_reg_2__D , drc_bufs6861_A,
     drc_bufs6867_A, g6593__9315_A, drc_bufs6825_A, DDIR_reg_28__D ,
     g6790__2398_B, g7019_A, g6540_A, o_DIN_reg_10__D , g22__5107_EN,
     g26__5526_A, DDIR_reg_27__D , g6973_A, g19__6417_EN,
     g6615__6131_A, g6627__6417_B, g7047_A, g6775__4733_C, g7012_A,
     drc_bufs6906_A, g31__1705_EN, g6862__9315_B, drc_bufs6771_A,
     g6361_A, g6366_A, o_DIN_reg_17__D , g15__2883_EN, g6754__8428_C,
     drc_bufs6876_A, g6611__1705_A, o_DIN_reg_29__D , g7038_A,
     g6580__3680_A, g6624__2346_B, g6966_A, g6676__1617_B, g6573_A,
     g6614__7098_A, g6619__4733_B, g6610__2802_B, drc_bufs6660_A,
     g6754__8428_B, g6982_A, g6898__5115_B, g6986_A, g6618__7482_B,
     g6898__5115_C, g6829__6417_B, g7024_A, g6627__6417_A, g6963_A,
     g6970_A, g6368_A, DDIR_reg_30__D , g6892__8246_C, g7025_A,
     g30__2802_A, g6814__5115_B, g6634__5526_A, g6626__7410_A,
     g6826__1666_C, drc_bufs6828_A, DDIR_reg_25__D , g6673__6783_C,
     drc_bufs6807_A, g6826__1666_B, g6865__2883_C, g6373_A, g6551_A,
     g6357_A, drc_bufs6729_A, g7008_A, g6626__7410_B, g7045_A,
     g11__4733_EN, g6516_A, g6608__3680_B, g6__7098_A, g6790__2398_C,
     g7020_A, g6924__6783_B, g6594__9945_B, g22__5107_A, g6__7098_EN,
     o_DIN_reg_9__D , g6617__5115_A, g7007_A, g7033_A, g6883__6783_B,
     g6862__9315_C, g6354_A, g5__8246_A, g6495_A, g6976_A,
     g6652__9315_B, o_DIN_reg_1__D , g6548_A, DDIR_reg_0__D ,
     o_DIN_reg_21__D , g6606__5526_A, g5__8246_EN, g6969_A, g6977_A,
     g6351_A, g6838__8428_C, g6676__1617_C, g6892__8246_B,
     g6588__1881_A, o_DIN_reg_3__D , g6512_A, g6594__9945_A,
     g6685__6131_B, g6602__5107_B, g6936__4733_A, DOUT_reg_8__D ,
     g6619__4733_A, g6580__3680_B, g6859__4733_C, DDIR_reg_18__D ,
     g6958_A, g7014_A, DOUT_reg_20__D , g6993_A, g6926__1617_B,
     g6871__6417_B, o_DIN_reg_23__D , g1__1617_A, g26__5526_EN,
     g6971_A, g6904__9315_B, g6618__7482_A, g6936__4733_B,
     g6883__6783_C, g6979_A, g7026_A, DDIR_reg_6__D , g6838__8428_B,
     DOUT_reg_15__D , g6588__1881_B);
  input clk, i_arst, i_DATA_31, i_DATA_30, i_DATA_29, i_DATA_28,
       i_DATA_27, i_DATA_26, i_DATA_25, i_DATA_23, i_DATA_22,
       i_DATA_21, i_DATA_20, i_DATA_19, i_DATA_18, i_DATA_17,
       i_DATA_16, i_DATA_15, i_DATA_14, i_DATA_13, i_DATA_12,
       i_DATA_11, i_DATA_10, i_DATA_9, i_DATA_8, i_DATA_7, i_DATA_6,
       i_DATA_5, i_DATA_4, i_DATA_3, i_DATA_2, i_DATA_1, i_DATA_0,
       i_ALT_IN, i_DDIR_WE, i_DIN_RE, i_DOUT_WE, io_IO_in_31,
       io_IO_in_30, io_IO_in_26, io_IO_in_25, io_IO_in_24, io_IO_in_23,
       io_IO_in_22, io_IO_in_21, io_IO_in_20, io_IO_in_18, io_IO_in_15,
       io_IO_in_13, io_IO_in_12, io_IO_in_10, io_IO_in_9, io_IO_in_7,
       io_IO_in_6, io_IO_in_5, io_IO_in_4, io_IO_in_2, io_IO_in_0,
       g7047_Y, g6836__4319_Y, g6527_Y, g6865__2883_Y, g6926__1617_Y,
       g6917__5107_Y, g6871__6417_Y, DDIR_reg_28__Q , g6548_Y,
       g7038_Y, g6839__5526_Y, drc_bufs6906_Y, DDIR_reg_18__Q ,
       g6764__5122_Y, g6838__8428_Y, g6934__5115_Y, o_DIN_reg_23__Q ,
       drc_bufs6729_Y, g6829__6417_Y, g6383_Y, g6963_Y, g6767__7098_Y,
       g6997_Y, g6924__6783_Y, g6775__4733_Y, drc_bufs6708_Y, g6445_Y,
       g6449_Y, g6593__9315_Y, g6368_Y, DDIR_reg_30__Q , g6414_Y,
       g7007_Y, g6863__9945_Y, g6602__5107_Y, g6634__5526_Y, g6979_Y,
       DDIR_reg_27__Q , DOUT_reg_12__Q , g6665__5107_Y,
       drc_bufs6876_Y, g6615__6131_Y, g6966_Y, g7025_Y, g6887__2802_Y,
       g6869__7410_Y, g6516_Y, g6627__6417_Y, g7008_Y, g6982_Y,
       DOUT_reg_20__Q , g6904__9315_Y, DDIR_reg_6__Q , g6465_Y,
       g6719__2802_Y, g6703__6417_Y, DOUT_reg_15__Q , g6512_Y,
       g6533_Y, o_DIN_reg_1__Q , drc_bufs6807_Y, g6351_Y,
       g6713__5526_Y, g6455_Y, g6573_Y, g6618__7482_Y, g6683__7098_Y,
       g6941__2346_Y, DOUT_reg_9__Q , g6606__5526_Y, g6500_Y,
       g6676__1617_Y, g6460_Y, g7017_Y, g6537_Y, drc_bufs6828_Y,
       g6540_Y, g6993_Y, g6652__9315_Y, drc_bufs6867_Y, g6685__6131_Y,
       g6389_Y, drc_bufs6879_Y, g6480_Y, g6354_Y, g6376_Y,
       g6580__3680_Y, g6650__6161_Y, DOUT_reg_27__Q , DOUT_reg_14__Q
       , g6833__5107_Y, g6446_Y, g6898__5115_Y, DOUT_reg_8__Q ,
       DDIR_reg_2__Q , drc_bufs6897_Y, g6892__8246_Y, drc_bufs6660_Y,
       g6485_Y, g6958_Y, g6872__5477_Y, g6611__1705_Y, g6626__7410_Y,
       g6594__9945_Y, g6701__7410_Y, g6695__9945_Y, DDIR_reg_25__Q ,
       g6428_Y, g6624__2346_Y, g6392_Y, g7020_Y, g6547_Y, g6406_Y,
       g6976_Y, g6826__1666_Y, g6644__1881_Y, o_DIN_reg_21__Q ,
       g6704__5477_Y, g6610__2802_Y, g6517_Y, g6911__7410_Y, g6487_Y,
       o_DIN_reg_9__Q , g6970_Y, drc_bufs6855_Y, g7024_Y, g6519_Y,
       g6608__3680_Y, g6495_Y, g6986_Y, g6468_Y, g6674__3680_Y,
       drc_bufs6657_Y, g6437_Y, drc_bufs6861_Y, g6673__6783_Y,
       DDIR_reg_0__Q , drc_bufs6789_Y, g6936__4733_Y, drc_bufs6639_Y,
       g6752__4319_Y, g6773__7482_Y, o_DIN_reg_29__Q , drc_bufs6771_Y,
       g6973_Y, g6850__8246_Y, g6754__8428_Y, g6425_Y, g6357_Y,
       g6969_Y, g6790__2398_Y, g6859__4733_Y, g6588__1881_Y;
  output o_DIN_31, o_DIN_30, o_DIN_28, o_DIN_27, o_DIN_26, o_DIN_25,
       o_DIN_24, o_DIN_22, o_DIN_20, o_DIN_19, o_DIN_16, o_DIN_15,
       o_DIN_14, o_DIN_13, o_DIN_12, o_DIN_11, o_DIN_8, o_DIN_7,
       o_DIN_6, o_DIN_5, o_DIN_4, o_DIN_2, o_DIN_0, io_IO_out_31,
       io_IO_out_30, io_IO_out_27, io_IO_out_26, io_IO_out_25,
       io_IO_out_23, io_IO_out_22, io_IO_out_21, io_IO_out_19,
       io_IO_out_18, io_IO_out_16, io_IO_out_15, io_IO_out_14,
       io_IO_out_12, io_IO_out_11, io_IO_out_10, io_IO_out_8,
       io_IO_out_7, io_IO_out_6, io_IO_out_5, io_IO_out_1, io_IO_out_0,
       drc_bufs6855_A, g6593__9315_B, g6703__6417_B, DOUT_reg_27__D ,
       g6517_A, g6924__6783_A, o_DIN_reg_18__D , g6960_A,
       drc_bufs6708_A, g6624__2346_A, g6640__8246_B, drc_bufs6789_A,
       g15__2883_A, g6907__2883_B, g6904__9315_C, g6673__6783_B,
       g6808__8246_B, g6997_A, g6850__8246_B, DDIR_reg_2__D ,
       drc_bufs6861_A, drc_bufs6867_A, g6593__9315_A, drc_bufs6825_A,
       DDIR_reg_28__D , g6790__2398_B, g7019_A, g6540_A,
       o_DIN_reg_10__D , g22__5107_EN, g26__5526_A, DDIR_reg_27__D ,
       g6973_A, g19__6417_EN, g6615__6131_A, g6627__6417_B, g7047_A,
       g6775__4733_C, g7012_A, drc_bufs6906_A, g31__1705_EN,
       g6862__9315_B, drc_bufs6771_A, g6361_A, g6366_A,
       o_DIN_reg_17__D , g15__2883_EN, g6754__8428_C, drc_bufs6876_A,
       g6611__1705_A, o_DIN_reg_29__D , g7038_A, g6580__3680_A,
       g6624__2346_B, g6966_A, g6676__1617_B, g6573_A, g6614__7098_A,
       g6619__4733_B, g6610__2802_B, drc_bufs6660_A, g6754__8428_B,
       g6982_A, g6898__5115_B, g6986_A, g6618__7482_B, g6898__5115_C,
       g6829__6417_B, g7024_A, g6627__6417_A, g6963_A, g6970_A,
       g6368_A, DDIR_reg_30__D , g6892__8246_C, g7025_A, g30__2802_A,
       g6814__5115_B, g6634__5526_A, g6626__7410_A, g6826__1666_C,
       drc_bufs6828_A, DDIR_reg_25__D , g6673__6783_C, drc_bufs6807_A,
       g6826__1666_B, g6865__2883_C, g6373_A, g6551_A, g6357_A,
       drc_bufs6729_A, g7008_A, g6626__7410_B, g7045_A, g11__4733_EN,
       g6516_A, g6608__3680_B, g6__7098_A, g6790__2398_C, g7020_A,
       g6924__6783_B, g6594__9945_B, g22__5107_A, g6__7098_EN,
       o_DIN_reg_9__D , g6617__5115_A, g7007_A, g7033_A,
       g6883__6783_B, g6862__9315_C, g6354_A, g5__8246_A, g6495_A,
       g6976_A, g6652__9315_B, o_DIN_reg_1__D , g6548_A,
       DDIR_reg_0__D , o_DIN_reg_21__D , g6606__5526_A, g5__8246_EN,
       g6969_A, g6977_A, g6351_A, g6838__8428_C, g6676__1617_C,
       g6892__8246_B, g6588__1881_A, o_DIN_reg_3__D , g6512_A,
       g6594__9945_A, g6685__6131_B, g6602__5107_B, g6936__4733_A,
       DOUT_reg_8__D , g6619__4733_A, g6580__3680_B, g6859__4733_C,
       DDIR_reg_18__D , g6958_A, g7014_A, DOUT_reg_20__D , g6993_A,
       g6926__1617_B, g6871__6417_B, o_DIN_reg_23__D , g1__1617_A,
       g26__5526_EN, g6971_A, g6904__9315_B, g6618__7482_A,
       g6936__4733_B, g6883__6783_C, g6979_A, g7026_A, DDIR_reg_6__D ,
       g6838__8428_B, DOUT_reg_15__D , g6588__1881_B;
  wire DDIR1, DDIR8, DDIR11, DDIR12, DDIR14, DDIR15, DDIR16, DDIR19;
  wire DDIR22, DDIR23, DDIR26, DDIR31, DOUT0, DOUT1, DOUT3, DOUT4;
  wire DOUT6, DOUT7, DOUT10, DOUT11, DOUT13, DOUT18, DOUT23, DOUT26;
  wire DOUT28, DOUT31, n_0, n_418, n_419, n_423, n_425, n_426;
  wire n_432, n_434, n_435, n_436, n_438, n_439, n_440, n_441;
  wire n_443, n_448, n_449, n_450, n_453, n_454, n_455, n_458;
  wire n_459, n_460, n_461, n_463, n_464, n_465, n_466, n_467;
  wire n_469, n_470, n_471, n_474, n_476, n_477, n_478, n_479;
  wire n_480, n_481, n_482, n_484, n_485, n_486, n_489, n_491;
  wire n_495, n_497, n_498, n_499, n_500, n_501, n_505, n_506;
  wire n_507, n_508, n_509, n_510, n_512, n_514, n_515, n_516;
  wire n_518, n_521, n_523, n_524, n_526, n_527, n_528, n_530;
  wire n_532, n_533, n_538, n_539, n_540, n_541, n_542, n_547;
  wire n_549, n_550, n_551, n_553, n_555, n_557, n_559, n_561;
  wire n_562, n_563, n_565, n_567, n_569, n_570, n_572, n_573;
  wire n_576, n_577, n_580, n_582, n_585, n_586, n_588, n_591;
  wire n_592, n_593, n_597, n_601, n_602, n_604, n_606, n_607;
  wire n_608, n_609, n_610, n_612, n_613, n_614, n_616, n_646;
  wire n_648, n_650, n_652, n_653, n_655, n_656, n_658, n_659;
  wire n_667, n_669, n_670, n_671, n_672, n_676, n_681, n_682;
  wire n_683, n_684, n_685, n_687, n_688, n_689, n_690, n_691;
  wire n_693, n_694, n_695, n_696, n_701, n_702, n_703, n_705;
  wire n_706, n_707, n_708, n_709, n_710, n_711, n_746, n_747;
  wire n_749, n_751, n_755, n_757, n_758, n_759, n_761, n_762;
  wire n_764, n_765, n_767, n_770, n_772, n_776, n_841, n_842;
  wire n_843, n_844, n_845, n_846, n_847, n_848, n_849, n_850;
  wire n_851, n_852, n_853, n_854, n_855, n_856, n_857, n_858;
  wire n_859, n_860, n_861, n_862, n_863, n_864, n_865, n_866;
  wire n_867, n_868, n_869, n_870, n_871, n_872, n_873, n_874;
  wire n_875, n_876, n_877, n_878, n_879, n_880, n_881, n_882;
  wire n_883, n_884, n_885, n_886, n_887, n_888, n_889, n_890;
  wire n_891, n_892, n_893, n_894, n_895, n_896, n_897, n_898;
  wire n_899, n_900, n_901, n_902, n_903, n_904, n_905, n_906;
  wire n_907, n_908, n_909, n_910, n_911, n_912, n_913, n_914;
  wire n_915, n_916, n_917, n_918, n_919, n_920, n_921, n_922;
  wire n_923, n_924, n_925, n_926, n_927, n_928, n_929, n_930;
  wire n_931, n_932, n_933, n_934, n_935, n_936, n_937, n_938;
  wire n_939, n_940, n_941, n_942, n_943, n_944, n_945, n_946;
  wire n_947, n_948, n_949, n_950, n_951, n_952, n_953, n_954;
  wire n_955, n_956, n_957, n_958, n_959, n_960, n_961, n_962;
  wire n_963, n_964, n_965, n_966, n_967, n_968, n_969, n_970;
  wire n_971, n_972, n_973, n_974, n_975, n_976, n_977, n_978;
  wire n_979, n_980, n_981, n_982, n_983, n_984, n_985, n_986;
  wire n_987, n_988, n_989, n_990, n_991, n_992, n_993, n_994;
  wire n_995, n_996, n_997, n_998, n_999, n_1000, n_1001, n_1002;
  wire n_1003, n_1004, n_1005, n_1006, n_1007, n_1008, n_1009, n_1010;
  wire n_1011, n_1012, n_1013, n_1014, n_1015, n_1016, n_1017, n_1018;
  wire n_1019, n_1020, n_1021, n_1022, n_1023, n_1024, n_1025, n_1026;
  wire n_1027, n_1028, n_1029, n_1030, n_1031, n_1032, n_1033, n_1034;
  wire n_1035, n_1036, n_1037, n_1038, n_1039, n_1040, n_1041, n_1042;
  wire n_1043, n_1044, n_1045, n_1046, n_1047, n_1048, n_1049, n_1050;
  wire n_1051, n_1052, n_1053, n_1054, n_1055, n_1056, n_1057, n_1058;
  wire n_1059, n_1060, n_1061, n_1062, n_1063;
  NAND2X1 g6854__1881(.A (i_DIN_RE), .B (io_IO_in_22), .Y
       (drc_bufs6855_A));
  INVX1 g6457(.A (i_arst), .Y (g6593__9315_B));
  DFFPOSX1 o_DIN_reg_15_ (.CLK (clk), .D (n_841), .Q (o_DIN_15));
  BUFX2 g7004(.A (n_842), .Y (n_843));
  INVX1 g6497(.A (DDIR19), .Y (n_572));
  INVX1 g6471(.A (i_arst), .Y (n_474));
  INVX1 g6463(.A (i_arst), .Y (n_458));
  INVX1 g6514(.A (DDIR8), .Y (g6703__6417_B));
  AND2X1 g6632__4319(.A (n_844), .B (n_845), .Y (DOUT_reg_27__D ));
  DFFPOSX1 DDIR_reg_5_ (.CLK (clk), .D (n_477), .Q (g6517_A));
  INVX1 g6539(.A (g6368_A), .Y (n_491));
  OAI21X1 g6913__6417(.A (i_DIN_RE), .B (n_524), .C (g7047_Y), .Y
       (g6924__6783_A));
  BUFX2 drc_bufs6837(.A (g6836__4319_Y), .Y (n_846));
  OAI21X1 g6727__6131(.A (i_DDIR_WE), .B (g6527_Y), .C (n_847), .Y
       (n_848));
  INVX1 g6371(.A (DOUT26), .Y (n_538));
  NAND2X1 g6821__9945(.A (i_DATA_1), .B (i_DOUT_WE), .Y (n_681));
  INVX1 g6411(.A (i_arst), .Y (n_849));
  AND2X1 g6940__2883(.A (g6865__2883_Y), .B (n_850), .Y
       (o_DIN_reg_18__D ));
  TBUFX2 g14__9945(.A (n_508), .EN (DDIR12), .Y (io_IO_out_12));
  DFFPOSX1 o_DIN_reg_4_ (.CLK (clk), .D (g6926__1617_Y), .Q (o_DIN_4));
  NAND2X1 g6689__7482(.A (i_DATA_13), .B (i_DDIR_WE), .Y (n_758));
  BUFX2 drc_bufs6918(.A (g6917__5107_Y), .Y (n_851));
  BUFX2 drc_bufs6654(.A (n_770), .Y (g6960_A));
  BUFX2 g7003(.A (n_852), .Y (n_853));
  AND2X1 g6938__9315(.A (g6871__6417_Y), .B (n_854), .Y (n_855));
  NAND2X1 g6707__5107(.A (i_DATA_7), .B (i_DDIR_WE), .Y
       (drc_bufs6708_A));
  NAND2X1 g6779__9945(.A (i_DATA_15), .B (i_DOUT_WE), .Y (n_695));
  INVX1 g6482(.A (DDIR_reg_28__Q ), .Y (n_555));
  INVX1 g6459(.A (i_arst), .Y (n_448));
  OAI21X1 g6766__8246(.A (i_DOUT_WE), .B (g6548_Y), .C (n_856), .Y
       (g6624__2346_A));
  BUFX2 g6990(.A (n_857), .Y (n_858));
  INVX1 g6481(.A (g31__1705_EN), .Y (g6640__8246_B));
  NAND2X1 g6788__5477(.A (i_DATA_12), .B (i_DOUT_WE), .Y
       (drc_bufs6789_A));
  OAI21X1 g6886__1617(.A (i_DIN_RE), .B (n_551), .C (g7038_Y), .Y
       (n_859));
  BUFX2 drc_bufs6840(.A (g6839__5526_Y), .Y (n_860));
  INVX1 g6350(.A (DOUT13), .Y (g15__2883_A));
  INVX1 g6535(.A (o_DIN_4), .Y (g6907__2883_B));
  INVX1 g6386(.A (i_arst), .Y (n_861));
  INVX1 g6393(.A (i_arst), .Y (n_862));
  BUFX2 g7044(.A (drc_bufs6906_Y), .Y (g6904__9315_C));
  BUFX2 g6998(.A (n_863), .Y (n_856));
  INVX1 g6499(.A (DDIR_reg_18__Q ), .Y (g6673__6783_B));
  NAND2X1 g6908__2346(.A (i_DIN_RE), .B (io_IO_in_4), .Y (n_650));
  INVX1 g6562(.A (g6351_A), .Y (g6808__8246_B));
  TBUFX2 g9__5115(.A (n_499), .EN (g6516_A), .Y (io_IO_out_7));
  OAI21X1 g6694__9315(.A (i_DDIR_WE), .B (n_588), .C (n_864), .Y
       (n_865));
  NAND2X1 g6716__3680(.A (i_DATA_4), .B (i_DDIR_WE), .Y (n_749));
  OAI21X1 g6721__1705(.A (i_DDIR_WE), .B (n_608), .C (n_866), .Y
       (n_867));
  INVX1 g6385(.A (i_arst), .Y (n_868));
  DFFPOSX1 o_DIN_reg_8_ (.CLK (clk), .D (n_869), .Q (o_DIN_8));
  BUFX2 g6972(.A (n_870), .Y (n_871));
  INVX1 g6447(.A (i_arst), .Y (n_426));
  BUFX2 drc_bufs6765(.A (g6764__5122_Y), .Y (g6997_A));
  AND2X1 g6949__4319(.A (g6838__8428_Y), .B (n_861), .Y (n_872));
  INVX1 g6417(.A (i_arst), .Y (n_873));
  DFFPOSX1 o_DIN_reg_12_ (.CLK (clk), .D (g6934__5115_Y), .Q
       (o_DIN_12));
  INVX1 g6484(.A (o_DIN_reg_23__Q ), .Y (g6850__8246_B));
  AND2X1 g6575__6260(.A (n_867), .B (n_482), .Y (DDIR_reg_2__D ));
  BUFX2 g6985(.A (drc_bufs6729_Y), .Y (n_847));
  INVX1 g6474(.A (i_arst), .Y (n_480));
  NAND2X1 g6860__6161(.A (i_DIN_RE), .B (io_IO_in_20), .Y
       (drc_bufs6861_A));
  INVX1 g6419(.A (i_arst), .Y (n_874));
  AND2X1 g6952__6783(.A (g6829__6417_Y), .B (g6383_Y), .Y (n_875));
  INVX1 g6452(.A (i_arst), .Y (n_436));
  INVX1 g6464(.A (i_arst), .Y (n_460));
  INVX1 g6549(.A (DOUT18), .Y (n_539));
  OAI21X1 g6661__6417(.A (i_DDIR_WE), .B (n_567), .C (g6963_Y), .Y
       (n_876));
  NAND2X1 g6809__7098(.A (i_DATA_5), .B (i_DOUT_WE), .Y (n_685));
  BUFX2 drc_bufs6813(.A (n_684), .Y (n_877));
  BUFX2 drc_bufs6768(.A (g6767__7098_Y), .Y (n_863));
  OAI21X1 g6763__1705(.A (i_DOUT_WE), .B (n_528), .C (g6997_Y), .Y
       (n_878));
  BUFX2 drc_bufs6843(.A (n_672), .Y (n_879));
  DFFPOSX1 o_DIN_reg_2_ (.CLK (clk), .D (g6924__6783_Y), .Q (o_DIN_2));
  AND2X1 g6621__9315(.A (g6775__4733_Y), .B (n_880), .Y (n_881));
  NAND2X1 g6866__2346(.A (i_DIN_RE), .B (io_IO_in_18), .Y
       (drc_bufs6867_A));
  INVX1 g6536(.A (DOUT26), .Y (n_506));
  INVX1 g6391(.A (i_arst), .Y (n_882));
  DFFPOSX1 DOUT_reg_31_ (.CLK (clk), .D (n_883), .Q (DOUT31));
  OAI21X1 g6667__6260(.A (i_DDIR_WE), .B (n_570), .C (n_884), .Y
       (g6593__9315_A));
  BUFX2 drc_bufs6780(.A (n_695), .Y (n_885));
  OAI21X1 g6134__1617(.A (i_DDIR_WE), .B (n_549), .C (n_886), .Y
       (n_887));
  BUFX2 g6978(.A (drc_bufs6708_Y), .Y (n_888));
  BUFX2 drc_bufs6762(.A (n_701), .Y (n_889));
  NAND2X1 g6824__2346(.A (i_DATA_0), .B (i_DOUT_WE), .Y
       (drc_bufs6825_A));
  AND2X1 g6605__8428(.A (n_890), .B (g6445_Y), .Y (n_423));
  TBUFX2 g13__9315(.A (n_507), .EN (DDIR11), .Y (io_IO_out_11));
  BUFX2 drc_bufs6891(.A (n_656), .Y (n_891));
  AND2X1 g6601__2398(.A (n_892), .B (g6449_Y), .Y (DDIR_reg_28__D ));
  INVX1 g6556(.A (DOUT11), .Y (g6790__2398_B));
  BUFX2 drc_bufs6831(.A (n_676), .Y (g7019_A));
  BUFX2 drc_bufs6750(.A (n_705), .Y (n_893));
  NAND2X1 g6725__7098(.A (i_DATA_1), .B (i_DDIR_WE), .Y (n_746));
  AND2X1 g6948__6260(.A (n_894), .B (n_895), .Y (n_896));
  DFFPOSX1 DDIR_reg_22_ (.CLK (clk), .D (n_443), .Q (DDIR22));
  DFFPOSX1 DOUT_reg_24_ (.CLK (clk), .D (n_897), .Q (g6540_A));
  AND2X1 g6932__6131(.A (n_898), .B (n_899), .Y (o_DIN_reg_10__D ));
  AND2X1 g6630__5107(.A (n_900), .B (n_901), .Y (n_902));
  DFFPOSX1 DDIR_reg_20_ (.CLK (clk), .D (g6593__9315_Y), .Q
       (g22__5107_EN));
  INVX1 g6356(.A (g6540_A), .Y (g26__5526_A));
  AND2X1 g6600__5477(.A (n_903), .B (n_432), .Y (DDIR_reg_27__D ));
  BUFX2 drc_bufs6693(.A (n_757), .Y (g6973_A));
  NAND2X1 g6668__4319(.A (i_DATA_20), .B (i_DDIR_WE), .Y (n_765));
  DFFPOSX1 o_DIN_reg_25_ (.CLK (clk), .D (n_904), .Q (o_DIN_25));
  BUFX2 drc_bufs6726(.A (n_746), .Y (n_905));
  TBUFX2 g32__5122(.A (g6368_Y), .EN (DDIR_reg_30__Q ), .Y
       (io_IO_out_30));
  NAND2X1 g6812__1881(.A (i_DATA_4), .B (i_DOUT_WE), .Y (n_684));
  AND2X1 g6584__5122(.A (n_865), .B (n_464), .Y (n_465));
  DFFPOSX1 DDIR_reg_17_ (.CLK (clk), .D (n_453), .Q (g19__6417_EN));
  AND2X1 g6636__3680(.A (n_906), .B (g6414_Y), .Y (n_883));
  OAI21X1 g6793__6260(.A (i_DOUT_WE), .B (n_569), .C (g7007_Y), .Y
       (g6615__6131_A));
  INVX1 g6378(.A (g6573_A), .Y (n_532));
  INVX1 g6422(.A (i_arst), .Y (g6627__6417_B));
  BUFX2 drc_bufs6864(.A (g6863__9945_Y), .Y (n_907));
  INVX1 g6430(.A (i_arst), .Y (n_0));
  BUFX2 drc_bufs6915(.A (n_648), .Y (g7047_A));
  TBUFX2 g18__7410(.A (n_518), .EN (DDIR16), .Y (io_IO_out_16));
  BUFX2 g7001(.A (n_908), .Y (g6775__4733_C));
  BUFX2 drc_bufs6810(.A (n_685), .Y (g7012_A));
  BUFX2 drc_bufs6741(.A (n_708), .Y (n_909));
  NAND2X1 g6905__9945(.A (i_DIN_RE), .B (io_IO_in_5), .Y
       (drc_bufs6906_A));
  INVX1 g6472(.A (i_arst), .Y (n_476));
  DFFPOSX1 DDIR_reg_29_ (.CLK (clk), .D (g6602__5107_Y), .Q
       (g31__1705_EN));
  INVX1 g6402(.A (i_arst), .Y (n_910));
  AND2X1 g6586__7098(.A (n_911), .B (n_460), .Y (n_461));
  INVX1 g6395(.A (i_arst), .Y (n_850));
  INVX1 g6363(.A (DOUT31), .Y (n_547));
  INVX1 g6496(.A (o_DIN_19), .Y (g6862__9315_B));
  DFFPOSX1 DDIR_reg_14_ (.CLK (clk), .D (n_459), .Q (DDIR14));
  AND2X1 g6596__2346(.A (n_912), .B (n_440), .Y (n_441));
  NAND2X1 g6770__1881(.A (i_DATA_18), .B (i_DOUT_WE), .Y
       (drc_bufs6771_A));
  DFFPOSX1 DOUT_reg_29_ (.CLK (clk), .D (g6634__5526_Y), .Q (g6361_A));
  OAI21X1 g6709__6260(.A (i_DDIR_WE), .B (n_601), .C (g6979_Y), .Y
       (n_913));
  INVX1 g6412(.A (i_arst), .Y (n_914));
  TBUFX2 g29__1617(.A (n_540), .EN (DDIR_reg_27__Q ), .Y
       (io_IO_out_27));
  OAI21X1 g6901__4733(.A (i_DIN_RE), .B (n_516), .C (n_915), .Y
       (n_916));
  OAI21X1 g6835__6260(.A (i_DIN_RE), .B (n_510), .C (n_917), .Y
       (n_918));
  BUFX2 drc_bufs6747(.A (n_706), .Y (n_919));
  DFFPOSX1 DOUT_reg_17_ (.CLK (clk), .D (n_920), .Q (g6366_A));
  INVX1 g6555(.A (DOUT_reg_12__Q ), .Y (n_561));
  NAND2X1 g6857__7482(.A (i_DIN_RE), .B (io_IO_in_21), .Y (n_667));
  BUFX2 drc_bufs6921(.A (n_646), .Y (n_921));
  INVX1 g6407(.A (i_arst), .Y (n_922));
  BUFX2 drc_bufs6666(.A (g6665__5107_Y), .Y (n_923));
  AND2X1 g6939__9945(.A (n_924), .B (n_925), .Y (o_DIN_reg_17__D ));
  BUFX2 g7034(.A (drc_bufs6876_Y), .Y (n_926));
  BUFX2 drc_bufs6699(.A (n_755), .Y (n_927));
  DFFPOSX1 DDIR_reg_13_ (.CLK (clk), .D (n_461), .Q (g15__2883_EN));
  BUFX2 drc_bufs6759(.A (n_702), .Y (n_928));
  NAND2X1 g6890__5122(.A (i_DIN_RE), .B (io_IO_in_10), .Y (n_656));
  BUFX2 g6994(.A (n_929), .Y (g6754__8428_C));
  OAI21X1 g6658__1666(.A (i_DDIR_WE), .B (n_565), .C (n_930), .Y
       (n_912));
  BUFX2 drc_bufs6690(.A (n_758), .Y (n_870));
  INVX1 g6507(.A (g15__2883_EN), .Y (n_616));
  DFFPOSX1 DOUT_reg_10_ (.CLK (clk), .D (g6615__6131_Y), .Q (DOUT10));
  DFFPOSX1 o_DIN_reg_6_ (.CLK (clk), .D (n_931), .Q (o_DIN_6));
  DFFPOSX1 o_DIN_reg_27_ (.CLK (clk), .D (n_872), .Q (o_DIN_27));
  INVX1 g6564(.A (DOUT4), .Y (n_592));
  OAI21X1 g6670__8428(.A (i_DDIR_WE), .B (n_572), .C (g6966_Y), .Y
       (n_932));
  TBUFX2 g33__8246(.A (n_547), .EN (DDIR31), .Y (io_IO_out_31));
  OAI21X1 g6733__4733(.A (i_DOUT_WE), .B (n_491), .C (n_933), .Y
       (n_934));
  OAI21X1 g6724__8246(.A (i_DDIR_WE), .B (n_609), .C (n_935), .Y
       (n_936));
  NAND2X1 g6875__5107(.A (i_DIN_RE), .B (io_IO_in_15), .Y
       (drc_bufs6876_A));
  OAI21X1 g6805__1705(.A (i_DOUT_WE), .B (n_585), .C (n_937), .Y
       (g6611__1705_A));
  AND2X1 g6951__5526(.A (n_938), .B (n_939), .Y (o_DIN_reg_29__D ));
  INVX1 g6541(.A (o_DIN_2), .Y (n_524));
  DFFPOSX1 DDIR_reg_1_ (.CLK (clk), .D (n_485), .Q (DDIR1));
  OAI21X1 g6847__1705(.A (i_DIN_RE), .B (n_542), .C (g7025_Y), .Y
       (n_940));
  BUFX2 drc_bufs6888(.A (g6887__2802_Y), .Y (g7038_A));
  INVX1 g6568(.A (g22__5107_EN), .Y (n_570));
  BUFX2 drc_bufs6870(.A (g6869__7410_Y), .Y (n_941));
  OAI21X1 g6706__2398(.A (i_DDIR_WE), .B (g6516_Y), .C (n_888), .Y
       (g6580__3680_A));
  TBUFX2 g12__6161(.A (n_505), .EN (g6512_A), .Y (io_IO_out_10));
  INVX1 g6426(.A (i_arst), .Y (g6624__2346_B));
  BUFX2 drc_bufs6672(.A (n_764), .Y (g6966_A));
  INVX1 g6502(.A (g19__6417_EN), .Y (g6676__1617_B));
  DFFPOSX1 DOUT_reg_22_ (.CLK (clk), .D (g6627__6417_Y), .Q (g6573_A));
  OAI21X1 g6796__8428(.A (i_DOUT_WE), .B (n_573), .C (g7008_Y), .Y
       (g6614__7098_A));
  NAND2X1 g6848__5122(.A (i_DIN_RE), .B (io_IO_in_24), .Y (n_670));
  BUFX2 g6980(.A (n_942), .Y (n_943));
  AND2X1 g6583__1705(.A (n_944), .B (n_466), .Y (n_467));
  DFFPOSX1 DOUT_reg_28_ (.CLK (clk), .D (n_945), .Q (DOUT28));
  OAI21X1 g6718__1617(.A (i_DDIR_WE), .B (n_606), .C (g6982_Y), .Y
       (n_946));
  INVX1 g6467(.A (i_arst), .Y (n_466));
  INVX1 g6382(.A (i_arst), .Y (g6619__4733_B));
  INVX1 g6440(.A (i_arst), .Y (g6610__2802_B));
  NAND2X1 g6659__7410(.A (i_DATA_23), .B (i_DDIR_WE), .Y
       (drc_bufs6660_A));
  INVX1 g6545(.A (DOUT_reg_20__Q ), .Y (n_528));
  INVX1 g6365(.A (DOUT10), .Y (n_505));
  BUFX2 g7002(.A (n_885), .Y (n_947));
  INVX1 g6542(.A (DOUT23), .Y (g6754__8428_B));
  AND2X1 g6927__2802(.A (g6904__9315_Y), .B (n_922), .Y (n_948));
  OAI21X1 g6649__4733(.A (i_DDIR_WE), .B (n_559), .C (n_949), .Y
       (n_950));
  INVX1 g6420(.A (i_arst), .Y (n_901));
  INVX1 g6572(.A (DDIR_reg_6__Q ), .Y (n_601));
  AND2X1 g6585__8246(.A (n_951), .B (g6465_Y), .Y (n_463));
  INVX1 g6522(.A (g5__8246_EN), .Y (n_606));
  INVX1 g6557(.A (DOUT10), .Y (n_569));
  BUFX2 drc_bufs6720(.A (g6719__2802_Y), .Y (g6982_A));
  AND2X1 g6581__1617(.A (g6703__6417_Y), .B (n_470), .Y (n_471));
  AND2X1 g6592__6161(.A (n_932), .B (n_448), .Y (n_449));
  BUFX2 drc_bufs6882(.A (n_659), .Y (n_952));
  INVX1 g6552(.A (DOUT_reg_15__Q ), .Y (n_550));
  OAI21X1 g6697__2883(.A (i_DDIR_WE), .B (g6512_Y), .C (n_953), .Y
       (n_944));
  INVX1 g6529(.A (DOUT31), .Y (n_614));
  INVX1 g6489(.A (g26__5526_EN), .Y (n_562));
  NAND2X1 g6803__2802(.A (i_DATA_7), .B (i_DOUT_WE), .Y (n_687));
  INVX1 g6483(.A (o_DIN_24), .Y (n_542));
  OAI21X1 g6916__2398(.A (i_DIN_RE), .B (n_597), .C (n_954), .Y
       (n_955));
  INVX1 g6565(.A (g6373_A), .Y (n_602));
  BUFX2 drc_bufs6903(.A (n_652), .Y (n_956));
  INVX1 g6509(.A (o_DIN_14), .Y (n_501));
  NAND2X1 g6884__3680(.A (i_DIN_RE), .B (io_IO_in_12), .Y (n_658));
  INVX1 g6528(.A (o_DIN_7), .Y (g6898__5115_B));
  DFFPOSX1 o_DIN_reg_16_ (.CLK (clk), .D (n_855), .Q (o_DIN_16));
  DFFPOSX1 o_DIN_reg_13_ (.CLK (clk), .D (n_957), .Q (o_DIN_13));
  NAND2X1 g6881__5526(.A (i_DIN_RE), .B (io_IO_in_13), .Y (n_659));
  INVX1 g6362(.A (DOUT18), .Y (n_521));
  BUFX2 drc_bufs6732(.A (n_711), .Y (g6986_A));
  OAI21X1 g6742__1666(.A (i_DOUT_WE), .B (g6533_Y), .C (n_858), .Y
       (n_844));
  INVX1 g6543(.A (o_DIN_reg_1__Q ), .Y (n_597));
  BUFX2 g7011(.A (drc_bufs6807_Y), .Y (n_937));
  BUFX2 drc_bufs(.A (n_776), .Y (n_958));
  TBUFX2 g7__6131(.A (g6351_Y), .EN (g6517_A), .Y (io_IO_out_5));
  INVX1 g6432(.A (i_arst), .Y (g6618__7482_B));
  BUFX2 g6995(.A (n_928), .Y (n_959));
  DFFPOSX1 o_DIN_reg_20_ (.CLK (clk), .D (n_960), .Q (o_DIN_20));
  AND2X1 g6635__6783(.A (n_934), .B (n_961), .Y (n_962));
  DFFPOSX1 o_DIN_reg_30_ (.CLK (clk), .D (n_875), .Q (o_DIN_30));
  DFFPOSX1 DDIR_reg_19_ (.CLK (clk), .D (n_449), .Q (DDIR19));
  BUFX2 drc_bufs6714(.A (g6713__5526_Y), .Y (n_942));
  AND2X1 g6595__2883(.A (n_876), .B (g6455_Y), .Y (n_443));
  NAND2X1 g6902__6161(.A (i_DIN_RE), .B (io_IO_in_6), .Y (n_652));
  BUFX2 g7028(.A (n_963), .Y (n_964));
  INVX1 g6415(.A (i_arst), .Y (n_961));
  BUFX2 g7042(.A (n_965), .Y (g6898__5115_C));
  INVX1 g6461(.A (i_arst), .Y (n_454));
  BUFX2 g7036(.A (n_952), .Y (n_966));
  INVX1 g6520(.A (o_DIN_30), .Y (g6829__6417_B));
  BUFX2 drc_bufs6846(.A (n_671), .Y (g7024_A));
  OAI21X1 g6757__6783(.A (i_DOUT_WE), .B (g6573_Y), .C (n_959), .Y
       (g6627__6417_A));
  NAND2X1 g6653__9945(.A (i_DATA_25), .B (i_DDIR_WE), .Y (n_770));
  NAND2X1 g6791__5107(.A (i_DATA_11), .B (i_DOUT_WE), .Y (n_691));
  NAND2X1 g6671__5526(.A (i_DATA_19), .B (i_DDIR_WE), .Y (n_764));
  DFFPOSX1 DOUT_reg_13_ (.CLK (clk), .D (g6618__7482_Y), .Q (DOUT13));
  INVX1 g6526(.A (DDIR1), .Y (n_609));
  BUFX2 drc_bufs6663(.A (n_767), .Y (g6963_A));
  BUFX2 drc_bufs6684(.A (g6683__7098_Y), .Y (g6970_A));
  OAI21X1 g6715__6783(.A (i_DDIR_WE), .B (n_604), .C (n_967), .Y
       (n_968));
  DFFPOSX1 DOUT_reg_30_ (.CLK (clk), .D (n_962), .Q (g6368_A));
  INVX1 g6569(.A (DDIR15), .Y (n_580));
  AND2X1 g6603__6260(.A (n_969), .B (n_426), .Y (DDIR_reg_30__D ));
  BUFX2 g6992(.A (n_893), .Y (n_970));
  DFFPOSX1 o_DIN_reg_19_ (.CLK (clk), .D (g6941__2346_Y), .Q
       (o_DIN_19));
  OAI21X1 g6748__2398(.A (i_DOUT_WE), .B (n_509), .C (n_970), .Y
       (n_900));
  INVX1 g6558(.A (DOUT_reg_9__Q ), .Y (n_573));
  AND2X1 g6631__6260(.A (n_971), .B (n_874), .Y (n_972));
  DFFPOSX1 DOUT_reg_1_ (.CLK (clk), .D (g6606__5526_Y), .Q (DOUT1));
  INVX1 g6421(.A (i_arst), .Y (n_973));
  OAI21X1 g6868__1666(.A (i_DIN_RE), .B (g6500_Y), .C (n_974), .Y
       (n_924));
  AND2X1 g6590__7482(.A (g6676__1617_Y), .B (g6460_Y), .Y (n_453));
  BUFX2 g7040(.A (n_975), .Y (g6892__8246_C));
  DFFPOSX1 o_DIN_reg_28_ (.CLK (clk), .D (n_976), .Q (o_DIN_28));
  BUFX2 drc_bufs6849(.A (n_670), .Y (g7025_A));
  OAI21X1 g6823__2883(.A (i_DOUT_WE), .B (n_610), .C (g7017_Y), .Y
       (n_890));
  INVX1 g6360(.A (DOUT28), .Y (g30__2802_A));
  INVX1 g6524(.A (DOUT3), .Y (g6814__5115_B));
  INVX1 g6504(.A (DDIR16), .Y (n_577));
  INVX1 g6429(.A (i_arst), .Y (n_880));
  BUFX2 g6981(.A (n_977), .Y (n_967));
  OAI21X1 g6910__1666(.A (i_DIN_RE), .B (g6537_Y), .C (n_978), .Y
       (n_979));
  INVX1 g6510(.A (DDIR11), .Y (n_588));
  NAND2X1 g6680__5122(.A (i_DATA_16), .B (i_DDIR_WE), .Y (n_761));
  OAI21X1 g6772__5115(.A (i_DOUT_WE), .B (n_541), .C (n_980), .Y
       (n_981));
  OAI21X1 g6736__9315(.A (i_DOUT_WE), .B (n_495), .C (n_982), .Y
       (g6634__5526_A));
  INVX1 g6381(.A (g6551_A), .Y (n_518));
  BUFX2 drc_bufs6783(.A (n_694), .Y (n_852));
  OAI21X1 g6760__1617(.A (i_DOUT_WE), .B (n_526), .C (n_983), .Y
       (g6626__7410_A));
  BUFX2 g7018(.A (drc_bufs6828_Y), .Y (g6826__1666_C));
  BUFX2 drc_bufs6735(.A (n_710), .Y (n_984));
  NAND2X1 g6893__7098(.A (i_DIN_RE), .B (io_IO_in_9), .Y (n_655));
  INVX1 g6566(.A (DOUT1), .Y (n_607));
  DFFPOSX1 DDIR_reg_12_ (.CLK (clk), .D (n_463), .Q (DDIR12));
  INVX1 g6511(.A (o_DIN_13), .Y (n_515));
  NAND2X1 g6746__5477(.A (i_DATA_26), .B (i_DOUT_WE), .Y (n_706));
  BUFX2 g7009(.A (n_985), .Y (n_986));
  OAI21X1 g6751__6260(.A (i_DOUT_WE), .B (g6540_Y), .C (g6993_Y), .Y
       (n_987));
  NAND2X1 g6827__7410(.A (i_DIN_RE), .B (io_IO_in_31), .Y
       (drc_bufs6828_A));
  NAND2X1 g6710__4319(.A (i_DATA_6), .B (i_DDIR_WE), .Y (n_751));
  INVX1 g6492(.A (DDIR23), .Y (n_565));
  DFFPOSX1 o_DIN_reg_31_ (.CLK (clk), .D (n_988), .Q (o_DIN_31));
  AND2X1 g6598__7410(.A (g6652__9315_Y), .B (n_436), .Y
       (DDIR_reg_25__D ));
  AND2X1 g6574__5107(.A (n_936), .B (n_484), .Y (n_485));
  BUFX2 g6967(.A (n_989), .Y (g6673__6783_C));
  NAND2X1 g6815__7482(.A (i_DATA_3), .B (i_DOUT_WE), .Y (n_683));
  NAND2X1 g6806__5122(.A (i_DATA_6), .B (i_DOUT_WE), .Y
       (drc_bufs6807_A));
  INVX1 g6570(.A (o_DIN_31), .Y (g6826__1666_B));
  DFFPOSX1 DOUT_reg_18_ (.CLK (clk), .D (n_990), .Q (DOUT18));
  BUFX2 g7031(.A (drc_bufs6867_Y), .Y (g6865__2883_C));
  INVX1 g6525(.A (o_DIN_8), .Y (n_593));
  AND2X1 g6587__6131(.A (g6685__6131_Y), .B (n_458), .Y (n_459));
  BUFX2 g7015(.A (n_991), .Y (n_992));
  INVX1 g6431(.A (i_arst), .Y (n_993));
  BUFX2 g6965(.A (n_994), .Y (n_884));
  OAI21X1 g6880__8428(.A (i_DIN_RE), .B (n_515), .C (n_966), .Y
       (n_995));
  AND2X1 g6930__8246(.A (n_996), .B (n_997), .Y (n_869));
  DFFPOSX1 DOUT_reg_2_ (.CLK (clk), .D (n_419), .Q (g6373_A));
  INVX1 g6476(.A (i_arst), .Y (n_484));
  INVX1 g6458(.A (i_arst), .Y (n_450));
  INVX1 g6554(.A (DOUT13), .Y (n_557));
  DFFPOSX1 DOUT_reg_16_ (.CLK (clk), .D (n_881), .Q (g6551_A));
  NAND2X1 g6743__7410(.A (i_DATA_27), .B (i_DOUT_WE), .Y (n_707));
  INVX1 g6508(.A (DDIR12), .Y (n_586));
  AND2X1 g6946__2398(.A (n_940), .B (g6389_Y), .Y (n_998));
  BUFX2 g7035(.A (drc_bufs6879_Y), .Y (n_999));
  OAI21X1 g6637__1705(.A (i_DDIR_WE), .B (g6480_Y), .C (n_1000), .Y
       (n_969));
  INVX1 g6396(.A (i_arst), .Y (n_925));
  AND2X1 g6950__8428(.A (n_918), .B (n_868), .Y (n_976));
  NAND2X1 g6920__4319(.A (i_DIN_RE), .B (io_IO_in_0), .Y (n_646));
  INVX1 g6403(.A (i_arst), .Y (n_899));
  DFFPOSX1 DOUT_reg_25_ (.CLK (clk), .D (n_902), .Q (g6357_A));
  INVX1 g6466(.A (i_arst), .Y (n_464));
  NAND2X1 g6728__1881(.A (i_DATA_0), .B (i_DDIR_WE), .Y
       (drc_bufs6729_A));
  BUFX2 drc_bufs6798(.A (n_689), .Y (g7008_A));
  NAND2X1 g6899__7482(.A (i_DIN_RE), .B (io_IO_in_7), .Y (n_653));
  TBUFX2 g23__6260(.A (g6354_Y), .EN (g6495_A), .Y (io_IO_out_21));
  OAI21X1 g6643__6131(.A (i_DDIR_WE), .B (n_555), .C (n_1001), .Y
       (n_892));
  TBUFX2 g10__7482(.A (g6376_Y), .EN (DDIR8), .Y (io_IO_out_8));
  INVX1 g6423(.A (i_arst), .Y (g6626__7410_B));
  NAND2X1 g6776__6161(.A (i_DATA_16), .B (i_DOUT_WE), .Y (n_696));
  INVX1 g6387(.A (i_arst), .Y (n_895));
  BUFX2 drc_bufs6909(.A (n_650), .Y (g7045_A));
  DFFPOSX1 DDIR_reg_9_ (.CLK (clk), .D (n_469), .Q (g11__4733_EN));
  INVX1 g6427(.A (i_arst), .Y (n_1002));
  BUFX2 g6989(.A (n_909), .Y (n_1003));
  BUFX2 drc_bufs6756(.A (n_703), .Y (n_929));
  OAI21X1 g6769__6131(.A (i_DOUT_WE), .B (n_539), .C (n_1004), .Y
       (n_1005));
  DFFPOSX1 DDIR_reg_7_ (.CLK (clk), .D (g6580__3680_Y), .Q (g6516_A));
  BUFX2 g7049(.A (n_921), .Y (n_1006));
  BUFX2 drc_bufs6651(.A (g6650__6161_Y), .Y (n_1007));
  INVX1 g6397(.A (i_arst), .Y (n_854));
  TBUFX2 g16__2346(.A (n_512), .EN (DDIR14), .Y (io_IO_out_14));
  INVX1 g6442(.A (i_arst), .Y (g6608__3680_B));
  AND2X1 g6597__1666(.A (n_1008), .B (n_438), .Y (n_439));
  BUFX2 g6996(.A (n_889), .Y (n_983));
  AND2X1 g6922__8428(.A (n_1009), .B (n_1010), .Y (n_1011));
  INVX1 g6374(.A (DOUT4), .Y (g6__7098_A));
  INVX1 g6384(.A (i_arst), .Y (n_939));
  NAND2X1 g6782__2346(.A (i_DATA_14), .B (i_DOUT_WE), .Y (n_694));
  INVX1 g6550(.A (g6366_A), .Y (n_541));
  INVX1 g6390(.A (i_arst), .Y (n_1012));
  INVX1 g6369(.A (DOUT_reg_27__Q ), .Y (n_540));
  BUFX2 g6959(.A (n_1007), .Y (n_949));
  TBUFX2 g3__1705(.A (n_489), .EN (DDIR1), .Y (io_IO_out_1));
  BUFX2 g7006(.A (n_1013), .Y (g6790__2398_C));
  BUFX2 g7046(.A (n_1014), .Y (n_978));
  DFFPOSX1 DDIR_reg_23_ (.CLK (clk), .D (n_441), .Q (DDIR23));
  INVX1 g6388(.A (i_arst), .Y (n_1015));
  AND2X1 g6609__1617(.A (n_1016), .B (n_1017), .Y (n_1018));
  INVX1 g6469(.A (i_arst), .Y (n_470));
  INVX1 g6364(.A (DOUT_reg_14__Q ), .Y (n_512));
  INVX1 g6380(.A (DOUT_reg_12__Q ), .Y (n_508));
  BUFX2 g7021(.A (n_846), .Y (n_917));
  BUFX2 drc_bufs6834(.A (g6833__5107_Y), .Y (g7020_A));
  INVX1 g6410(.A (i_arst), .Y (g6924__6783_B));
  INVX1 g6571(.A (o_DIN_11), .Y (n_551));
  INVX1 g6493(.A (DDIR22), .Y (n_567));
  NAND2X1 g6755__5526(.A (i_DATA_23), .B (i_DOUT_WE), .Y (n_703));
  INVX1 g6375(.A (DOUT7), .Y (n_499));
  INVX1 g6456(.A (i_arst), .Y (g6594__9945_B));
  NAND2X1 g6758__3680(.A (i_DATA_22), .B (i_DOUT_WE), .Y (n_702));
  BUFX2 g6957(.A (n_1019), .Y (n_1001));
  AND2X1 g6604__4319(.A (n_887), .B (g6446_Y), .Y (n_425));
  AND2X1 g6929__5122(.A (g6898__5115_Y), .B (n_1020), .Y (n_1021));
  BUFX2 g7013(.A (n_877), .Y (n_1022));
  INVX1 g6405(.A (i_arst), .Y (n_997));
  INVX1 g6477(.A (i_arst), .Y (n_486));
  AND2X1 g6607__6783(.A (n_1023), .B (n_418), .Y (n_419));
  BUFX2 drc_bufs6777(.A (n_696), .Y (n_908));
  INVX1 g6559(.A (DOUT_reg_8__Q ), .Y (n_576));
  INVX1 g6453(.A (i_arst), .Y (n_438));
  BUFX2 drc_bufs6738(.A (n_709), .Y (n_1024));
  INVX1 g6523(.A (DDIR_reg_2__Q ), .Y (n_608));
  NAND2X1 g6686__1881(.A (i_DATA_14), .B (i_DDIR_WE), .Y (n_759));
  INVX1 g6353(.A (DOUT_reg_20__Q ), .Y (g22__5107_A));
  INVX1 g6513(.A (g11__4733_EN), .Y (n_591));
  NAND2X1 g6800__3680(.A (i_DATA_8), .B (i_DOUT_WE), .Y (n_688));
  NAND2X1 g6677__2802(.A (i_DATA_17), .B (i_DDIR_WE), .Y (n_762));
  DFFPOSX1 DDIR_reg_4_ (.CLK (clk), .D (n_479), .Q (g6__7098_EN));
  INVX1 g6379(.A (DOUT11), .Y (n_507));
  BUFX2 g7010(.A (n_1025), .Y (n_1026));
  BUFX2 g7041(.A (drc_bufs6897_Y), .Y (n_1027));
  AND2X1 g6931__7098(.A (g6892__8246_Y), .B (n_1028), .Y
       (o_DIN_reg_9__D ));
  DFFPOSX1 o_DIN_reg_11_ (.CLK (clk), .D (n_1029), .Q (o_DIN_11));
  BUFX2 g6983(.A (n_1030), .Y (n_866));
  OAI21X1 g6874__2398(.A (i_DIN_RE), .B (n_612), .C (n_926), .Y
       (n_1031));
  INVX1 g6438(.A (i_arst), .Y (n_1032));
  AND2X1 g6947__5107(.A (n_1033), .B (n_1015), .Y (n_904));
  OAI21X1 g6787__6417(.A (i_DOUT_WE), .B (n_561), .C (n_1034), .Y
       (g6617__5115_A));
  DFFPOSX1 DOUT_reg_7_ (.CLK (clk), .D (n_1035), .Q (DOUT7));
  BUFX2 g6962(.A (drc_bufs6660_Y), .Y (n_930));
  NAND2X1 g6845__2802(.A (i_DIN_RE), .B (io_IO_in_25), .Y (n_671));
  OAI21X1 g6646__5115(.A (i_DDIR_WE), .B (g6485_Y), .C (g6958_Y), .Y
       (n_903));
  INVX1 g6454(.A (i_arst), .Y (n_440));
  BUFX2 drc_bufs6669(.A (n_765), .Y (n_994));
  BUFX2 g6988(.A (n_1024), .Y (n_982));
  NAND2X1 g6851__7098(.A (i_DIN_RE), .B (io_IO_in_23), .Y (n_669));
  TBUFX2 g25__8428(.A (n_533), .EN (DDIR23), .Y (io_IO_out_23));
  BUFX2 g7016(.A (n_1036), .Y (n_1037));
  INVX1 g6531(.A (g6361_A), .Y (n_495));
  BUFX2 drc_bufs6795(.A (n_690), .Y (g7007_A));
  NAND2X1 g6830__5477(.A (i_DIN_RE), .B (io_IO_in_30), .Y (n_676));
  BUFX2 drc_bufs6873(.A (g6872__5477_Y), .Y (g7033_A));
  TBUFX2 g17__1666(.A (n_514), .EN (DDIR15), .Y (io_IO_out_15));
  INVX1 g6441(.A (i_arst), .Y (n_1017));
  INVX1 g6515(.A (o_DIN_12), .Y (g6883__6783_B));
  DFFPOSX1 DOUT_reg_11_ (.CLK (clk), .D (n_1038), .Q (DOUT11));
  INVX1 g6418(.A (i_arst), .Y (n_845));
  BUFX2 g7030(.A (n_907), .Y (g6862__9315_C));
  DFFPOSX1 DOUT_reg_6_ (.CLK (clk), .D (g6611__1705_Y), .Q (DOUT6));
  DFFPOSX1 DOUT_reg_21_ (.CLK (clk), .D (g6626__7410_Y), .Q (g6354_A));
  INVX1 g6358(.A (DOUT3), .Y (g5__8246_A));
  AND2X1 g6612__5122(.A (n_1039), .B (n_1032), .Y (n_1035));
  DFFPOSX1 DDIR_reg_21_ (.CLK (clk), .D (g6594__9945_Y), .Q (g6495_A));
  INVX1 g6544(.A (g6354_A), .Y (n_526));
  BUFX2 drc_bufs6819(.A (n_682), .Y (n_991));
  NAND2X1 g6124__2802(.A (i_DATA_31), .B (i_DDIR_WE), .Y (n_776));
  BUFX2 g6975(.A (n_927), .Y (n_953));
  DFFPOSX1 DOUT_reg_0_ (.CLK (clk), .D (n_423), .Q (DOUT0));
  BUFX2 drc_bufs6702(.A (g6701__7410_Y), .Y (g6976_A));
  BUFX2 drc_bufs6696(.A (g6695__9945_Y), .Y (n_1040));
  INVX1 g6409(.A (i_arst), .Y (n_1020));
  INVX1 g6561(.A (DOUT6), .Y (n_585));
  BUFX2 g7039(.A (n_891), .Y (n_1041));
  BUFX2 drc_bufs6723(.A (n_747), .Y (n_1030));
  INVX1 g6400(.A (i_arst), .Y (n_1042));
  NAND2X1 g6662__5477(.A (i_DATA_22), .B (i_DDIR_WE), .Y (n_767));
  INVX1 g6488(.A (DDIR_reg_25__Q ), .Y (g6652__9315_B));
  AND2X1 g6623__2883(.A (n_1005), .B (n_1002), .Y (n_990));
  NAND2X1 g6647__7482(.A (i_DATA_27), .B (i_DDIR_WE), .Y (n_772));
  BUFX2 drc_bufs6858(.A (n_667), .Y (n_963));
  AND2X1 g6622__9945(.A (n_981), .B (g6428_Y), .Y (n_920));
  AND2X1 g6923__5526(.A (n_955), .B (n_914), .Y (o_DIN_reg_1__D ));
  DFFPOSX1 DOUT_reg_19_ (.CLK (clk), .D (g6624__2346_Y), .Q (g6548_A));
  AND2X1 g6130__2398(.A (n_848), .B (n_486), .Y (DDIR_reg_0__D ));
  AND2X1 g6943__7410(.A (n_1043), .B (g6392_Y), .Y (o_DIN_reg_21__D ));
  OAI21X1 g6820__9315(.A (i_DOUT_WE), .B (n_607), .C (n_1037), .Y
       (g6606__5526_A));
  AND2X1 g6933__1881(.A (n_859), .B (n_910), .Y (n_1029));
  OAI21X1 g6745__6417(.A (i_DOUT_WE), .B (n_506), .C (n_1044), .Y
       (n_971));
  OAI21X1 g6832__2398(.A (i_DIN_RE), .B (n_500), .C (g7020_Y), .Y
       (n_938));
  OAI21X1 g6919__6260(.A (i_DIN_RE), .B (g6547_Y), .C (n_1006), .Y
       (n_1009));
  AND2X1 g6928__1705(.A (n_916), .B (g6406_Y), .Y (n_931));
  BUFX2 g6974(.A (n_1040), .Y (n_864));
  DFFPOSX1 DDIR_reg_3_ (.CLK (clk), .D (n_481), .Q (g5__8246_EN));
  INVX1 g6538(.A (g6357_A), .Y (n_509));
  BUFX2 g7048(.A (n_851), .Y (n_954));
  OAI21X1 g6700__1666(.A (i_DDIR_WE), .B (n_591), .C (g6976_Y), .Y
       (n_1045));
  BUFX2 drc_bufs6681(.A (n_761), .Y (g6969_A));
  BUFX2 drc_bufs6900(.A (n_653), .Y (n_965));
  AND2X1 g6953__3680(.A (g6826__1666_Y), .B (n_0), .Y (n_988));
  BUFX2 drc_bufs6645(.A (g6644__1881_Y), .Y (n_1019));
  NAND2X1 g6914__5477(.A (i_DIN_RE), .B (io_IO_in_2), .Y (n_648));
  INVX1 g6491(.A (o_DIN_reg_21__Q ), .Y (n_563));
  DFFPOSX1 o_DIN_reg_5_ (.CLK (clk), .D (n_948), .Q (o_DIN_5));
  BUFX2 drc_bufs6705(.A (g6704__5477_Y), .Y (g6977_A));
  DFFPOSX1 DDIR_reg_31_ (.CLK (clk), .D (n_425), .Q (DDIR31));
  DFFPOSX1 DOUT_reg_5_ (.CLK (clk), .D (g6610__2802_Y), .Q (g6351_A));
  OAI21X1 g6712__8428(.A (i_DDIR_WE), .B (g6517_Y), .C (n_943), .Y
       (n_1046));
  INVX1 g6530(.A (o_DIN_6), .Y (n_516));
  BUFX2 g6954(.A (n_958), .Y (n_886));
  BUFX2 drc_bufs6912(.A (g6911__7410_Y), .Y (n_1014));
  OAI21X1 g6802__1617(.A (i_DOUT_WE), .B (n_582), .C (n_1026), .Y
       (n_1039));
  BUFX2 g7022(.A (n_860), .Y (g6838__8428_C));
  DFFPOSX1 DOUT_reg_4_ (.CLK (clk), .D (n_1018), .Q (DOUT4));
  OAI21X1 g6853__6131(.A (i_DIN_RE), .B (g6487_Y), .C (n_1047), .Y
       (n_1048));
  BUFX2 g6968(.A (n_1049), .Y (g6676__1617_C));
  OAI21X1 g6799__6783(.A (i_DOUT_WE), .B (n_576), .C (n_986), .Y
       (n_1050));
  INVX1 g6546(.A (o_DIN_reg_9__Q ), .Y (g6892__8246_B));
  DFFPOSX1 DDIR_reg_26_ (.CLK (clk), .D (n_435), .Q (DDIR26));
  INVX1 g6413(.A (i_arst), .Y (n_1010));
  OAI21X1 g6682__8246(.A (i_DDIR_WE), .B (n_580), .C (g6970_Y), .Y
       (g6588__1881_A));
  DFFPOSX1 o_DIN_reg_24_ (.CLK (clk), .D (n_998), .Q (o_DIN_24));
  BUFX2 g6991(.A (n_919), .Y (n_1044));
  OAI21X1 g6856__5115(.A (i_DIN_RE), .B (n_563), .C (n_964), .Y
       (n_1043));
  BUFX2 g6964(.A (n_923), .Y (n_1051));
  BUFX2 g7027(.A (drc_bufs6855_Y), .Y (n_1047));
  INVX1 g6434(.A (i_arst), .Y (n_1052));
  NAND2X1 g6842__3680(.A (i_DIN_RE), .B (io_IO_in_26), .Y (n_672));
  AND2X1 g6925__3680(.A (n_979), .B (n_849), .Y (o_DIN_reg_3__D ));
  AND2X1 g6599__6417(.A (n_950), .B (n_434), .Y (n_435));
  BUFX2 drc_bufs6801(.A (n_688), .Y (n_985));
  INVX1 g6567(.A (DOUT0), .Y (n_610));
  OAI21X1 g6844__1617(.A (i_DIN_RE), .B (n_530), .C (g7024_Y), .Y
       (n_1033));
  OAI21X1 g6889__1705(.A (i_DIN_RE), .B (g6519_Y), .C (n_1041), .Y
       (n_898));
  INVX1 g6367(.A (DOUT6), .Y (n_498));
  DFFPOSX1 DOUT_reg_3_ (.CLK (clk), .D (g6608__3680_Y), .Q (DOUT3));
  AND2X1 g6576__4319(.A (n_946), .B (n_480), .Y (n_481));
  NAND2X1 g6722__5122(.A (i_DATA_2), .B (i_DDIR_WE), .Y (n_747));
  DFFPOSX1 DDIR_reg_10_ (.CLK (clk), .D (n_467), .Q (g6512_A));
  OAI21X1 g6664__2398(.A (i_DDIR_WE), .B (g6495_Y), .C (n_1051), .Y
       (g6594__9945_A));
  INVX1 g6505(.A (DDIR14), .Y (g6685__6131_B));
  NAND2X1 g6692__6161(.A (i_DATA_12), .B (i_DDIR_WE), .Y (n_757));
  TBUFX2 g20__5477(.A (n_521), .EN (DDIR_reg_18__Q ), .Y
       (io_IO_out_18));
  INVX1 g6448(.A (i_arst), .Y (g6602__5107_B));
  BUFX2 drc_bufs6744(.A (n_707), .Y (n_857));
  BUFX2 g7032(.A (n_941), .Y (n_974));
  OAI21X1 g6730__5115(.A (i_DOUT_WE), .B (n_614), .C (g6986_Y), .Y
       (n_906));
  AND2X1 g6582__2802(.A (n_1045), .B (g6468_Y), .Y (n_469));
  BUFX2 drc_bufs6675(.A (g6674__3680_Y), .Y (n_989));
  AND2X1 g6937__6161(.A (n_1031), .B (n_1053), .Y (n_841));
  AND2X1 g6935__7482(.A (n_995), .B (n_1042), .Y (n_957));
  INVX1 g6451(.A (i_arst), .Y (n_434));
  BUFX2 g6961(.A (drc_bufs6657_Y), .Y (n_1054));
  DFFPOSX1 DDIR_reg_11_ (.CLK (clk), .D (n_465), .Q (DDIR11));
  BUFX2 g7000(.A (n_1055), .Y (n_980));
  OAI21X1 g6877__6260(.A (i_DIN_RE), .B (n_501), .C (n_999), .Y
       (g6936__4733_A));
  INVX1 g6398(.A (i_arst), .Y (n_1053));
  AND2X1 g6613__8246(.A (n_1050), .B (g6437_Y), .Y (DOUT_reg_8__D ));
  BUFX2 drc_bufs6822(.A (n_681), .Y (n_1036));
  OAI21X1 g6781__2883(.A (i_DOUT_WE), .B (n_553), .C (n_853), .Y
       (g6619__4733_A));
  INVX1 g6470(.A (i_arst), .Y (g6580__3680_B));
  OAI21X1 g6841__6783(.A (i_DIN_RE), .B (n_527), .C (n_1056), .Y
       (n_894));
  BUFX2 g7029(.A (drc_bufs6861_Y), .Y (g6859__4733_C));
  AND2X1 g6591__4733(.A (g6673__6783_Y), .B (n_450), .Y
       (DDIR_reg_18__D ));
  AND2X1 g6577__8428(.A (n_968), .B (n_478), .Y (n_479));
  DFFPOSX1 o_DIN_reg_0_ (.CLK (clk), .D (n_1011), .Q (o_DIN_0));
  BUFX2 drc_bufs6648(.A (n_772), .Y (g6958_A));
  INVX1 g6501(.A (o_DIN_28), .Y (n_510));
  TBUFX2 g2__2802(.A (n_613), .EN (DDIR_reg_0__Q ), .Y (io_IO_out_0));
  BUFX2 g7005(.A (drc_bufs6789_Y), .Y (n_1034));
  INVX1 g6521(.A (g6__7098_EN), .Y (n_604));
  DFFPOSX1 o_DIN_reg_14_ (.CLK (clk), .D (g6936__4733_Y), .Q
       (o_DIN_14));
  AND2X1 g6629__2398(.A (n_987), .B (n_973), .Y (n_897));
  AND2X1 g6633__8428(.A (n_1057), .B (n_873), .Y (n_945));
  BUFX2 drc_bufs6816(.A (n_683), .Y (g7014_A));
  OAI21X1 g6739__2883(.A (i_DOUT_WE), .B (n_497), .C (n_1003), .Y
       (n_1057));
  BUFX2 g6955(.A (drc_bufs6639_Y), .Y (n_1000));
  AND2X1 g6625__1666(.A (n_878), .B (n_1058), .Y (DOUT_reg_20__D ));
  DFFPOSX1 o_DIN_reg_22_ (.CLK (clk), .D (n_1059), .Q (o_DIN_22));
  BUFX2 drc_bufs6753(.A (g6752__4319_Y), .Y (g6993_A));
  BUFX2 drc_bufs6774(.A (g6773__7482_Y), .Y (n_1055));
  INVX1 g6490(.A (o_DIN_reg_29__Q ), .Y (n_500));
  BUFX2 drc_bufs6717(.A (n_749), .Y (n_977));
  NAND2X1 g6734__6161(.A (i_DATA_30), .B (i_DOUT_WE), .Y (n_710));
  INVX1 g6370(.A (DOUT0), .Y (n_613));
  OAI21X1 g6811__6131(.A (i_DOUT_WE), .B (n_592), .C (n_1022), .Y
       (n_1016));
  BUFX2 g6999(.A (drc_bufs6771_Y), .Y (n_1004));
  INVX1 g6408(.A (i_arst), .Y (g6926__1617_B));
  INVX1 g6503(.A (o_DIN_16), .Y (g6871__6417_B));
  OAI21X1 g6691__4733(.A (i_DDIR_WE), .B (n_586), .C (g6973_Y), .Y
       (n_951));
  INVX1 g6563(.A (o_DIN_26), .Y (n_527));
  AND2X1 g6945__5477(.A (g6850__8246_Y), .B (n_1012), .Y
       (o_DIN_reg_23__D ));
  INVX1 g6349(.A (i_ALT_IN), .Y (g1__1617_A));
  INVX1 g6404(.A (i_arst), .Y (n_1028));
  INVX1 g6359(.A (g6548_A), .Y (n_523));
  DFFPOSX1 DDIR_reg_24_ (.CLK (clk), .D (n_439), .Q (g26__5526_EN));
  AND2X1 g6944__6417(.A (n_1048), .B (n_882), .Y (n_1059));
  TBUFX2 g21__2398(.A (n_523), .EN (DDIR19), .Y (io_IO_out_19));
  INVX1 g6443(.A (i_arst), .Y (n_418));
  AND2X1 g6628__5477(.A (g6754__8428_Y), .B (g6425_Y), .Y (n_1060));
  TBUFX2 g27__6783(.A (g6357_Y), .EN (DDIR_reg_25__Q ), .Y
       (io_IO_out_25));
  BUFX2 g6984(.A (n_905), .Y (n_935));
  NAND2X1 g6794__4319(.A (i_DATA_10), .B (i_DOUT_WE), .Y (n_690));
  OAI21X1 g6817__4733(.A (i_DOUT_WE), .B (n_602), .C (n_992), .Y
       (n_1023));
  INVX1 g6560(.A (DOUT7), .Y (n_582));
  BUFX2 drc_bufs6687(.A (n_759), .Y (g6971_A));
  DFFPOSX1 o_DIN_reg_7_ (.CLK (clk), .D (n_1021), .Q (o_DIN_7));
  INVX1 g6534(.A (o_DIN_5), .Y (g6904__9315_B));
  AND2X1 g6589__5115(.A (n_1061), .B (n_454), .Y (n_455));
  OAI21X1 g6679__1705(.A (i_DDIR_WE), .B (n_577), .C (g6969_Y), .Y
       (n_1061));
  BUFX2 g7023(.A (n_879), .Y (n_1056));
  TBUFX2 g8__1881(.A (n_498), .EN (DDIR_reg_6__Q ), .Y (io_IO_out_6));
  INVX1 g6473(.A (i_arst), .Y (n_478));
  DFFPOSX1 DDIR_reg_8_ (.CLK (clk), .D (n_471), .Q (DDIR8));
  INVX1 g6486(.A (DDIR26), .Y (n_559));
  NAND2X1 g6698__2346(.A (i_DATA_10), .B (i_DDIR_WE), .Y (n_755));
  OAI21X1 g6895__6131(.A (i_DIN_RE), .B (n_593), .C (n_1027), .Y
       (n_996));
  OAI21X1 g6784__1666(.A (i_DOUT_WE), .B (n_557), .C (n_843), .Y
       (g6618__7482_A));
  AND2X1 g6616__1881(.A (g6790__2398_Y), .B (n_1052), .Y (n_1038));
  NAND2X1 g6797__5526(.A (i_DATA_9), .B (i_DOUT_WE), .Y (n_689));
  BUFX2 drc_bufs6894(.A (n_655), .Y (n_975));
  INVX1 g6478(.A (DDIR31), .Y (n_549));
  INVX1 g6399(.A (i_arst), .Y (g6936__4733_B));
  OAI21X1 g6778__9315(.A (i_DOUT_WE), .B (n_550), .C (n_947), .Y
       (n_1062));
  BUFX2 g7037(.A (n_1063), .Y (g6883__6783_C));
  DFFPOSX1 o_DIN_reg_26_ (.CLK (clk), .D (n_896), .Q (o_DIN_26));
  BUFX2 drc_bufs6792(.A (n_691), .Y (n_1013));
  INVX1 g6352(.A (DOUT_reg_15__Q ), .Y (n_514));
  TBUFX2 g28__3680(.A (n_538), .EN (DDIR26), .Y (io_IO_out_26));
  AND2X1 g6942__1666(.A (g6859__4733_Y), .B (n_862), .Y (n_960));
  NAND2X1 g6731__7482(.A (i_DATA_31), .B (i_DOUT_WE), .Y (n_711));
  NAND2X1 g6785__7410(.A (i_DATA_13), .B (i_DOUT_WE), .Y (n_693));
  INVX1 g6372(.A (DOUT1), .Y (n_489));
  OAI21X1 g6688__5115(.A (i_DDIR_WE), .B (n_616), .C (n_871), .Y
       (n_911));
  INVX1 g6450(.A (i_arst), .Y (n_432));
  TBUFX2 g24__4319(.A (n_532), .EN (DDIR22), .Y (io_IO_out_22));
  INVX1 g6479(.A (o_DIN_25), .Y (n_530));
  BUFX2 drc_bufs6804(.A (n_687), .Y (n_1025));
  NAND2X1 g6818__6161(.A (i_DATA_2), .B (i_DOUT_WE), .Y (n_682));
  BUFX2 drc_bufs6711(.A (n_751), .Y (g6979_A));
  NAND2X1 g6761__2802(.A (i_DATA_21), .B (i_DOUT_WE), .Y (n_701));
  BUFX2 drc_bufs6852(.A (n_669), .Y (g7026_A));
  NAND2X1 g6740__2346(.A (i_DATA_28), .B (i_DOUT_WE), .Y (n_708));
  AND2X1 g6579__6783(.A (n_913), .B (n_474), .Y (DDIR_reg_6__D ));
  INVX1 g6506(.A (o_DIN_15), .Y (n_612));
  INVX1 g6518(.A (o_DIN_27), .Y (g6838__8428_B));
  AND2X1 g6578__5526(.A (n_1046), .B (n_476), .Y (n_477));
  INVX1 g6355(.A (DOUT23), .Y (n_533));
  INVX1 g6532(.A (DOUT28), .Y (n_497));
  DFFPOSX1 DDIR_reg_16_ (.CLK (clk), .D (n_455), .Q (DDIR16));
  NAND2X1 g6749__5107(.A (i_DATA_25), .B (i_DOUT_WE), .Y (n_705));
  AND2X1 g6620__6161(.A (n_1062), .B (n_993), .Y (DOUT_reg_15__D ));
  BUFX2 g6987(.A (n_984), .Y (n_933));
  DFFPOSX1 DDIR_reg_15_ (.CLK (clk), .D (g6588__1881_Y), .Q (DDIR15));
  INVX1 g6553(.A (DOUT_reg_14__Q ), .Y (n_553));
  BUFX2 drc_bufs6786(.A (n_693), .Y (n_842));
  DFFPOSX1 DOUT_reg_23_ (.CLK (clk), .D (n_1060), .Q (DOUT23));
  DFFPOSX1 DOUT_reg_26_ (.CLK (clk), .D (n_972), .Q (DOUT26));
  BUFX2 drc_bufs6885(.A (n_658), .Y (n_1063));
  INVX1 g6475(.A (i_arst), .Y (n_482));
  INVX1 g6462(.A (i_arst), .Y (g6588__1881_B));
  INVX1 g6424(.A (i_arst), .Y (n_1058));
  OAI21X1 g6655__2883(.A (i_DDIR_WE), .B (n_562), .C (n_1054), .Y
       (n_1008));
  BUFX2 g7043(.A (n_956), .Y (n_915));
  BUFX2 drc_bufs6678(.A (n_762), .Y (n_1049));
  NAND2X1 g6737__9945(.A (i_DATA_29), .B (i_DOUT_WE), .Y (n_709));
endmodule

